AzerothCore: anonymous_namespace{CombatManagerTest.cpp} Namespace Reference
anonymous_namespace{CombatManagerTest.cpp} Namespace Reference
Classes
class CombatManagerIntegrationTest
Functions
TEST_F (CombatManagerIntegrationTest, SetInCombatWith_CreatesReference)
TEST_F (CombatManagerIntegrationTest, SetInCombatWith_SameUnit_Fails)
TEST_F (CombatManagerIntegrationTest, SetInCombatWith_DeadUnit_Fails)
TEST_F (CombatManagerIntegrationTest, SetInCombatWith_DifferentPhase_Fails)
TEST_F (CombatManagerIntegrationTest, EndAllPvECombat_ClearsAll)
TEST_F (CombatManagerIntegrationTest, EndAllPvECombat_AlsoClearsThreat)
TEST_F (CombatManagerIntegrationTest, HasCombat_ReflectsState)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_StartAndExpiry)
TEST_F (CombatManagerIntegrationTest, EvadeState_Transitions)
TEST_F (CombatManagerIntegrationTest, ContinueEvadeRegen_KeepsRegenActive)
TEST_F (CombatManagerIntegrationTest, ContinueEvadeRegen_StopEvadeClearsIt)
TEST_F (CombatManagerIntegrationTest, EvadeConstants)
TEST_F (CombatManagerIntegrationTest, EndCombat_SingleReference_KeepsOthers)
TEST_F (CombatManagerIntegrationTest, EndCombat_AlsoClearsThreatForThatRef)
TEST_F (CombatManagerIntegrationTest, EndCombat_BidirectionalCleanup)
TEST_F (CombatManagerIntegrationTest, SetImmuneToNPC_EndsCombatWithNPCs)
TEST_F (CombatManagerIntegrationTest, SetImmuneToNPC_KeepCombat_PreservesRefs)
TEST_F (CombatManagerIntegrationTest, StopAttackFaction_EndsCombatForFaction)
TEST_F (CombatManagerIntegrationTest, ClearInCombat_ClearsAllState)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_PartialCountdown_StillActive)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_FullCountdown_Expires)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_Overshoot_StillExpires)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_IncrementalCountdown_Expires)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_StopEvade_CancelsBeforeExpiry)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_RestartAfterStop_WorksAgain)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_InitialStart_NotInRegen)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_CountdownToRegenPhase)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_ContinueEvadeRegen_ResetsToRegenDelay)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_ContinueEvadeRegen_RepeatKeepsRegen)
TEST_F (CombatManagerIntegrationTest, EvadeState_SetToNone_ClearsTimer)
TEST_F (CombatManagerIntegrationTest, EvadeState_HomeState_IsInEvadeMode)
TEST_F (CombatManagerIntegrationTest, EvadeState_CombatState_IsInEvadeMode)
TEST_F (CombatManagerIntegrationTest, EvadeState_FullLifecycle)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_StopEvade_WithActiveState_ClearsState)
TEST_F (CombatManagerIntegrationTest, EvadeTimer_StopEvade_TimerAndState_ClearsBoth)
TEST_F (CombatManagerIntegrationTest, SetCannotReachTarget_StartsEvadeTimer)
TEST_F (CombatManagerIntegrationTest, SetCannotReachTarget_Clear_StopsEvade)
TEST_F (CombatManagerIntegrationTest, SetCannotReachTarget_SameTarget_NoDuplicate)
TEST_F (CombatManagerIntegrationTest, IsNotReachableAndNeedRegen_Integration)
TEST_F (CombatManagerIntegrationTest, SuppressedRef_DoesNotGenerateCombat)
TEST_F (CombatManagerIntegrationTest, GetAnyTarget_NoCombat_ReturnsNull)
TEST_F (CombatManagerIntegrationTest, GetAnyTarget_WithCombat_ReturnsTarget)
TEST_F (CombatManagerIntegrationTest, GetAnyTarget_SuppressedOnly_ReturnsNull)
TEST_F (CombatManagerIntegrationTest, HasPvECombatWithPlayers_CreaturesOnly_ReturnsFalse)
TEST_F (CombatManagerIntegrationTest, EndAllCombat_ClearsEverything)
TEST_F (CombatManagerIntegrationTest, EndAllPvPCombat_NoRefs_DoesNotCrash)
TEST_F (CombatManagerIntegrationTest, InheritCombatStatesFrom_InheritsPvERefs)
TEST_F (CombatManagerIntegrationTest, InheritCombatStatesFrom_SkipsDuplicate)
TEST_F (CombatManagerIntegrationTest, InheritCombatStatesFrom_SkipsImmuneTargets)
TEST_F (CombatManagerIntegrationTest, EndCombatBeyondRange_InRange_KeepsCombat)
TEST_F (CombatManagerIntegrationTest, EndCombatBeyondRange_OutOfRange_EndsCombat)
TEST_F (CombatManagerIntegrationTest, EndCombatBeyondRange_MixedDistances_EndsOnlyFar)
TEST_F (CombatManagerIntegrationTest, RevalidateCombat_ValidRefs_KeepsAll)
TEST_F (CombatManagerIntegrationTest, RevalidateCombat_InvalidRef_RemovesIt)
TEST_F (CombatManagerIntegrationTest, RevalidateCombat_DifferentPhase_RemovesIt)
TEST_F (CombatManagerIntegrationTest, CombatRefresh_UnsuppressesRef)
TEST_F (CombatManagerIntegrationTest, SuppressFor_SuppressesOneSide)
TEST_F (CombatManagerIntegrationTest, CanBeginCombat_UnitStateEvade_Fails)
TEST_F (CombatManagerIntegrationTest, CanBeginCombat_UnitStateInFlight_Fails)
TEST_F (CombatManagerIntegrationTest, CanBeginCombat_CombatDisallowed_Fails)
TEST_F (CombatManagerIntegrationTest, CanBeginCombat_FriendlyFactions_Fails)
TEST_F (CombatManagerIntegrationTest, CanBeginCombat_ValidUnits_Succeeds)
TEST_F (CombatManagerIntegrationTest, IsInCombatWith_ObjectGuid_Variant)
TEST_F (CombatManagerIntegrationTest, Update_NoPvPRefs_DoesNotCrash)
TEST_F (CombatManagerIntegrationTest, Update_EvadeTimerAndCombat_BothWork)
TEST_F (CombatManagerIntegrationTest, CombatReference_GetOther_ReturnsPeer)
TEST_F (CombatManagerIntegrationTest, HasPvPCombat_NoPvPRefs_ReturnsFalse)
TEST_F (CombatManagerIntegrationTest, SuppressPvPCombat_NoPvPRefs_DoesNotCrash)
TEST_F (CombatManagerIntegrationTest, SetInCombatWith_ExistingPvE_RefreshesRef)
TEST_F (CombatManagerIntegrationTest, MultipleRefs_IndependentLifecycle)
TEST_F (CombatManagerIntegrationTest, CanBeginCombat_DifferentMaps_Fails)
TEST_F (CombatManagerIntegrationTest, SetEvadeState_SameState_NoOp)
TEST_F (CombatManagerIntegrationTest, SetEvadeState_SameState_DoesNotClearTimer)
Function Documentation
TEST_F() [1/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , CanBeginCombat_CombatDisallowed_Fails)
{
    _creatureB->SetIsCombatDisallowed(true);
    EXPECT_FALSE(CombatManager::CanBeginCombat(_creatureA, _creatureB));
    _creatureB->SetIsCombatDisallowed(false);
}
References CombatManager::CanBeginCombat().
TEST_F() [2/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , CanBeginCombat_DifferentMaps_Fails)
{
    TestMap* map2 = new TestMap();
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(map2, 3, 12347);
    creatureC->SetFaction(90002);
    // A is on _map, C is on map2 — different maps
    EXPECT_NE(_creatureA->GetMap(), creatureC->GetMap());
    EXPECT_FALSE(CombatManager::CanBeginCombat(_creatureA, creatureC));
    creatureC->CleanupCombatState();
    delete creatureC;
    delete map2;
}
References CombatManager::CanBeginCombat(), TestCreature::CleanupCombatState(), WorldObject::GetMap(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [3/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , CanBeginCombat_FriendlyFactions_Fails)
{
    // Set both to same faction — they should be friendly
    _creatureB->SetFaction(90001); // same as A
    EXPECT_FALSE(CombatManager::CanBeginCombat(_creatureA, _creatureB));
}
References CombatManager::CanBeginCombat().
TEST_F() [4/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , CanBeginCombat_UnitStateEvade_Fails)
{
    _creatureB->AddUnitState(UNIT_STATE_EVADE);
    EXPECT_FALSE(CombatManager::CanBeginCombat(_creatureA, _creatureB));
    _creatureB->ClearUnitState(UNIT_STATE_EVADE);
}
References CombatManager::CanBeginCombat(), and UNIT_STATE_EVADE.
TEST_F() [5/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , CanBeginCombat_UnitStateInFlight_Fails)
{
    _creatureB->AddUnitState(UNIT_STATE_IN_FLIGHT);
    EXPECT_FALSE(CombatManager::CanBeginCombat(_creatureA, _creatureB));
    _creatureB->ClearUnitState(UNIT_STATE_IN_FLIGHT);
}
References CombatManager::CanBeginCombat(), and UNIT_STATE_IN_FLIGHT.
TEST_F() [6/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , CanBeginCombat_ValidUnits_Succeeds)
{
    EXPECT_TRUE(CombatManager::CanBeginCombat(_creatureA, _creatureB));
}
References CombatManager::CanBeginCombat().
TEST_F() [7/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , ClearInCombat_ClearsAllState)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat());
    _creatureA->ClearInCombat();
    // All combat and threat should be cleared
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasCombat());
    EXPECT_FALSE(_creatureA->IsInCombat());
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 0u);
}
TEST_F() [8/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , CombatReference_GetOther_ReturnsPeer)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    auto const& aRefs = _creatureA->TestGetCombatMgr().GetPvECombatRefs();
    ASSERT_FALSE(aRefs.empty());
    CombatReference* ref = aRefs.begin()->second;
    EXPECT_EQ(ref->GetOther(_creatureA), _creatureB);
    EXPECT_EQ(ref->GetOther(_creatureB), _creatureA);
}
References CombatReference::GetOther(), and CombatReference::second.
TEST_F() [9/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , CombatRefresh_UnsuppressesRef)
{
    // Create combat with B suppressed
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB, true);
    EXPECT_FALSE(_creatureB->TestGetCombatMgr().HasPvECombat()); // B is suppressed
    // SetInCombatWith again should refresh the existing ref (un-suppress)
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(_creatureB->TestGetCombatMgr().HasPvECombat()); // B un-suppressed
}
TEST_F() [10/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , ContinueEvadeRegen_KeepsRegenActive)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    // StartEvadeTimer begins at 10s — NOT in regen zone yet
    cm.StartEvadeTimer();
    EXPECT_TRUE(cm.IsInEvadeMode());
    EXPECT_FALSE(cm.IsEvadeRegen());
    // ContinueEvadeRegen sets timer to regen threshold
    cm.ContinueEvadeRegen();
    EXPECT_TRUE(cm.IsInEvadeMode());
    EXPECT_TRUE(cm.IsEvadeRegen());
    // After partial countdown, still in regen zone
    cm.Update(3000);
    EXPECT_TRUE(cm.IsEvadeRegen());
}
TEST_F() [11/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , ContinueEvadeRegen_StopEvadeClearsIt)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    cm.ContinueEvadeRegen();
    EXPECT_TRUE(cm.IsEvadeRegen());
    cm.StopEvade();
    EXPECT_FALSE(cm.IsEvadeRegen());
    EXPECT_FALSE(cm.IsInEvadeMode());
}
TEST_F() [12/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EndAllCombat_ClearsEverything)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetCombatMgr().SetInCombatWith(creatureC);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat());
    _creatureA->TestGetCombatMgr().EndAllCombat();
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasCombat());
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(creatureC));
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 0u);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [13/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EndAllPvECombat_AlsoClearsThreat)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    _creatureA->TestGetCombatMgr().EndAllPvECombat();
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 0u);
}
TEST_F() [14/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EndAllPvECombat_ClearsAll)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat());
    _creatureA->TestGetCombatMgr().EndAllPvECombat();
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasCombat());
}
TEST_F() [15/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EndAllPvPCombat_NoRefs_DoesNotCrash)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    // PvE combat exists but no PvP
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasPvECombat());
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasPvPCombat());
    // Should not crash, should not affect PvE
    _creatureA->TestGetCombatMgr().EndAllPvPCombat();
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasPvECombat());
}
TEST_F() [16/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EndCombat_AlsoClearsThreatForThatRef)
{
    // Add threat (which implies combat)
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    // End the combat reference directly
    auto const& refs = _creatureA->TestGetCombatMgr().GetPvECombatRefs();
    ASSERT_FALSE(refs.empty());
    auto it = refs.begin();
    it->second->EndCombat();
    // Both combat and threat should be cleared
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
}
TEST_F() [17/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EndCombat_BidirectionalCleanup)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    // End from A's side
    auto const& refs = _creatureA->TestGetCombatMgr().GetPvECombatRefs();
    ASSERT_FALSE(refs.empty());
    refs.begin()->second->EndCombat();
    // Both sides should be cleaned up
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasCombat());
    EXPECT_FALSE(_creatureB->TestGetCombatMgr().HasCombat());
}
TEST_F() [18/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EndCombat_SingleReference_KeepsOthers)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // A in combat with both B and C
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    _creatureA->TestGetCombatMgr().SetInCombatWith(creatureC);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(creatureC));
    // End only the reference with B
    auto const& refs = _creatureA->TestGetCombatMgr().GetPvECombatRefs();
    CombatReference* refToEnd = nullptr;
    for (auto const& pair : refs)
        if (pair.second->GetOther(_creatureA) == _creatureB)
            refToEnd = pair.second;
    ASSERT_NE(refToEnd, nullptr);
    refToEnd->EndCombat();
    // B reference gone, C reference remains
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(creatureC));
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat());
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), CombatReference::EndCombat(), CombatReference::second, TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [19/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EndCombatBeyondRange_InRange_KeepsCombat)
{
    // Both creatures at origin (0,0,0) — distance is 0
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    // Range of 50 — creatures are well within range
    _creatureA->TestGetCombatMgr().EndCombatBeyondRange(50.0f);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
}
TEST_F() [20/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EndCombatBeyondRange_MixedDistances_EndsOnlyFar)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // B at origin (close), C far away
    creatureC->Relocate(200.0f, 200.0f, 0.0f);
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    _creatureA->TestGetCombatMgr().SetInCombatWith(creatureC);
    _creatureA->TestGetCombatMgr().EndCombatBeyondRange(50.0f);
    // B should remain, C should be gone
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(creatureC));
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), Position::Relocate(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [21/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EndCombatBeyondRange_OutOfRange_EndsCombat)
{
    // Place B far away
    _creatureB->Relocate(200.0f, 200.0f, 0.0f);
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    // Range of 50 — B is ~283 units away
    _creatureA->TestGetCombatMgr().EndCombatBeyondRange(50.0f);
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
}
TEST_F() [22/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeConstants)
{
    constexpr uint32 duration = CombatManager::EVADE_TIMER_DURATION;
    constexpr uint32 delay = CombatManager::EVADE_REGEN_DELAY;
    constexpr uint32 pvpTimeout = PvPCombatReference::PVP_COMBAT_TIMEOUT;
    EXPECT_EQ(duration, 10000u);
    EXPECT_EQ(delay, 5000u);
    EXPECT_EQ(pvpTimeout, 5000u);
    EXPECT_EQ(delay * 2, duration);
    EXPECT_EQ(static_cast<uint8>(EVADE_STATE_NONE), 0);
    EXPECT_EQ(static_cast<uint8>(EVADE_STATE_COMBAT), 1);
    EXPECT_EQ(static_cast<uint8>(EVADE_STATE_HOME), 2);
}
References CombatManager::EVADE_REGEN_DELAY, EVADE_STATE_COMBAT, EVADE_STATE_HOME, EVADE_STATE_NONE, CombatManager::EVADE_TIMER_DURATION, and PvPCombatReference::PVP_COMBAT_TIMEOUT.
TEST_F() [23/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeState_CombatState_IsInEvadeMode)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    cm.SetEvadeState(EVADE_STATE_COMBAT);
    EXPECT_TRUE(cm.IsInEvadeMode());
    EXPECT_FALSE(cm.IsEvadingHome());
    EXPECT_TRUE(cm.IsEvadeRegen());
}
References EVADE_STATE_COMBAT.
TEST_F() [24/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeState_FullLifecycle)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    // Phase 1: Target unreachable → start evade timer
    EXPECT_EQ(cm.GetEvadeState(), EVADE_STATE_NONE);
    EXPECT_FALSE(cm.IsInEvadeMode());
    cm.StartEvadeTimer();
    EXPECT_TRUE(cm.IsInEvadeMode());
    EXPECT_FALSE(cm.IsEvadeRegen()); // Timer at 10s, above regen threshold
    EXPECT_EQ(cm.GetEvadeState(), EVADE_STATE_NONE); // State not changed yet
    // Phase 2: Timer counts down past regen threshold
    cm.Update(6000); // 4s left
    EXPECT_TRUE(cm.IsEvadeRegen());
    // Phase 3: Timer expires
    cm.Update(4000);
    EXPECT_FALSE(cm.IsInEvadeMode()); // No AI to set state
    // Phase 4: Simulate what AI would do — set state to HOME
    cm.SetEvadeState(EVADE_STATE_HOME);
    EXPECT_TRUE(cm.IsInEvadeMode());
    EXPECT_TRUE(cm.IsEvadingHome());
    // Phase 5: Creature arrives home — state cleared
    cm.SetEvadeState(EVADE_STATE_NONE);
    EXPECT_FALSE(cm.IsInEvadeMode());
    EXPECT_FALSE(cm.IsEvadingHome());
    EXPECT_FALSE(cm.IsEvadeRegen());
}
References EVADE_STATE_HOME, and EVADE_STATE_NONE.
TEST_F() [25/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeState_HomeState_IsInEvadeMode)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    cm.SetEvadeState(EVADE_STATE_HOME);
    EXPECT_TRUE(cm.IsInEvadeMode());
    EXPECT_TRUE(cm.IsEvadingHome());
    EXPECT_TRUE(cm.IsEvadeRegen()); // _evadeState != NONE triggers regen
}
References EVADE_STATE_HOME.
TEST_F() [26/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeState_SetToNone_ClearsTimer)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    cm.StartEvadeTimer();
    EXPECT_TRUE(cm.IsInEvadeMode());
    // SetEvadeState(NONE) has an early return if _evadeState is already NONE.
    // Set to HOME first so that the NONE transition actually executes.
    cm.SetEvadeState(EVADE_STATE_HOME);
    EXPECT_TRUE(cm.IsInEvadeMode());
    // Now setting to NONE should clear the timer
    cm.SetEvadeState(EVADE_STATE_NONE);
    EXPECT_FALSE(cm.IsInEvadeMode());
    EXPECT_EQ(cm.GetEvadeState(), EVADE_STATE_NONE);
}
References EVADE_STATE_HOME, and EVADE_STATE_NONE.
TEST_F() [27/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeState_Transitions)
{
    EXPECT_EQ(_creatureA->TestGetCombatMgr().GetEvadeState(), EVADE_STATE_NONE);
    _creatureA->TestGetCombatMgr().SetEvadeState(EVADE_STATE_HOME);
    EXPECT_EQ(_creatureA->TestGetCombatMgr().GetEvadeState(), EVADE_STATE_HOME);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsEvadingHome());
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInEvadeMode());
    _creatureA->TestGetCombatMgr().StopEvade();
    EXPECT_EQ(_creatureA->TestGetCombatMgr().GetEvadeState(), EVADE_STATE_NONE);
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInEvadeMode());
}
References EVADE_STATE_HOME, and EVADE_STATE_NONE.
TEST_F() [28/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_ContinueEvadeRegen_RepeatKeepsRegen)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    // In raids, ContinueEvadeRegen is called repeatedly to keep regen going
    cm.ContinueEvadeRegen();
    EXPECT_TRUE(cm.IsEvadeRegen());
    // Advance 3 seconds
    cm.Update(3000);
    EXPECT_TRUE(cm.IsEvadeRegen());
    // Call ContinueEvadeRegen again (simulates raid behavior — reset timer)
    cm.ContinueEvadeRegen();
    EXPECT_TRUE(cm.IsEvadeRegen());
    // Advance another 3 seconds (timer reset to 5s, so 3s in, still active)
    cm.Update(3000);
    EXPECT_TRUE(cm.IsEvadeRegen());
}
TEST_F() [29/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_ContinueEvadeRegen_ResetsToRegenDelay)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    // Start from a non-regen state
    cm.StartEvadeTimer();
    EXPECT_FALSE(cm.IsEvadeRegen());
    // ContinueEvadeRegen jumps the timer directly to the regen delay value
    cm.ContinueEvadeRegen();
    EXPECT_TRUE(cm.IsEvadeRegen());
    EXPECT_TRUE(cm.IsInEvadeMode());
    // Advance 4 seconds — timer at 1000, still regen
    cm.Update(4000);
    EXPECT_TRUE(cm.IsEvadeRegen());
    // Advance final 1 second — timer expires
    cm.Update(1000);
    EXPECT_FALSE(cm.IsInEvadeMode());
    EXPECT_FALSE(cm.IsEvadeRegen());
}
TEST_F() [30/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_CountdownToRegenPhase)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    cm.StartEvadeTimer();
    // Advance 5 seconds — timer is now at exactly EVADE_REGEN_DELAY (5000)
    cm.Update(CombatManager::EVADE_TIMER_DURATION - CombatManager::EVADE_REGEN_DELAY);
    EXPECT_TRUE(cm.IsInEvadeMode());
    EXPECT_TRUE(cm.IsEvadeRegen()); // timer <= EVADE_REGEN_DELAY
    // Advance 1 more second — timer at 4000, still in regen
    cm.Update(1000);
    EXPECT_TRUE(cm.IsEvadeRegen());
}
References CombatManager::EVADE_REGEN_DELAY, and CombatManager::EVADE_TIMER_DURATION.
TEST_F() [31/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_FullCountdown_Expires)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    cm.StartEvadeTimer();
    EXPECT_TRUE(cm.IsInEvadeMode());
    // Advance the full 10 seconds — timer should expire
    // Note: EvadeTimerExpired would be called but no AI is set in tests,
    // so it's a no-op. We verify the timer state itself.
    cm.Update(CombatManager::EVADE_TIMER_DURATION);
    // Timer has expired and no evade state was set by AI callback
    EXPECT_FALSE(cm.IsInEvadeMode());
}
References CombatManager::EVADE_TIMER_DURATION.
TEST_F() [32/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_IncrementalCountdown_Expires)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    cm.StartEvadeTimer();
    // Advance in 1-second increments
    for (uint32 i = 0; i < 9; ++i)
    {
        cm.Update(1000);
        EXPECT_TRUE(cm.IsInEvadeMode()) << "Timer should be active at " << (i + 1) << "s";
    }
    // 10th second — should expire
    cm.Update(1000);
    EXPECT_FALSE(cm.IsInEvadeMode());
}
TEST_F() [33/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_InitialStart_NotInRegen)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    // StartEvadeTimer sets timer to 10s — above the 5s regen threshold
    cm.StartEvadeTimer();
    EXPECT_TRUE(cm.IsInEvadeMode());
    EXPECT_FALSE(cm.IsEvadeRegen());
}
TEST_F() [34/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_Overshoot_StillExpires)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    cm.StartEvadeTimer();
    // Advance more than the timer duration
    cm.Update(CombatManager::EVADE_TIMER_DURATION + 5000);
    EXPECT_FALSE(cm.IsInEvadeMode());
}
References CombatManager::EVADE_TIMER_DURATION.
TEST_F() [35/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_PartialCountdown_StillActive)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    cm.StartEvadeTimer();
    EXPECT_TRUE(cm.IsInEvadeMode());
    // Advance 3 seconds — timer started at 10s, should still be active
    cm.Update(3000);
    EXPECT_TRUE(cm.IsInEvadeMode());
    // Advance another 3 seconds — 6s total, still active
    cm.Update(3000);
    EXPECT_TRUE(cm.IsInEvadeMode());
    cm.StopEvade();
}
TEST_F() [36/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_RestartAfterStop_WorksAgain)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    cm.StartEvadeTimer();
    cm.Update(5000);
    cm.StopEvade();
    EXPECT_FALSE(cm.IsInEvadeMode());
    // Restart the timer
    cm.StartEvadeTimer();
    EXPECT_TRUE(cm.IsInEvadeMode());
    cm.Update(5000);
    EXPECT_TRUE(cm.IsInEvadeMode()); // Still active — 5s into new 10s timer
    cm.Update(5000);
    EXPECT_FALSE(cm.IsInEvadeMode()); // Expired
}
TEST_F() [37/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_StartAndExpiry)
{
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInEvadeMode());
    _creatureA->TestGetCombatMgr().StartEvadeTimer();
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInEvadeMode());
}
TEST_F() [38/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_StopEvade_CancelsBeforeExpiry)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    cm.StartEvadeTimer();
    cm.Update(5000); // 5 seconds in
    EXPECT_TRUE(cm.IsInEvadeMode());
    cm.StopEvade();
    EXPECT_FALSE(cm.IsInEvadeMode());
    // Further updates should not re-trigger anything
    cm.Update(10000);
    EXPECT_FALSE(cm.IsInEvadeMode());
}
TEST_F() [39/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_StopEvade_TimerAndState_ClearsBoth)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    // Both timer and state active
    cm.StartEvadeTimer();
    cm.SetEvadeState(EVADE_STATE_COMBAT);
    EXPECT_TRUE(cm.IsInEvadeMode());
    // StopEvade clears both timer and state in a single call
    cm.StopEvade();
    EXPECT_FALSE(cm.IsInEvadeMode());
    EXPECT_EQ(cm.GetEvadeState(), EVADE_STATE_NONE);
}
References EVADE_STATE_COMBAT, and EVADE_STATE_NONE.
TEST_F() [40/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , EvadeTimer_StopEvade_WithActiveState_ClearsState)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    // Set evade state (no timer involved)
    cm.SetEvadeState(EVADE_STATE_HOME);
    EXPECT_TRUE(cm.IsInEvadeMode());
    // StopEvade should clear the state
    cm.StopEvade();
    EXPECT_FALSE(cm.IsInEvadeMode());
    EXPECT_EQ(cm.GetEvadeState(), EVADE_STATE_NONE);
}
References EVADE_STATE_HOME, and EVADE_STATE_NONE.
TEST_F() [41/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , GetAnyTarget_NoCombat_ReturnsNull)
{
    EXPECT_EQ(_creatureA->TestGetCombatMgr().GetAnyTarget(), nullptr);
}
TEST_F() [42/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , GetAnyTarget_SuppressedOnly_ReturnsNull)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB, true);
    // A's ref is not suppressed, but B's is
    EXPECT_NE(_creatureA->TestGetCombatMgr().GetAnyTarget(), nullptr);
    // B's only ref is suppressed, so GetAnyTarget skips it
    EXPECT_EQ(_creatureB->TestGetCombatMgr().GetAnyTarget(), nullptr);
}
TEST_F() [43/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , GetAnyTarget_WithCombat_ReturnsTarget)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    Unit* target = _creatureA->TestGetCombatMgr().GetAnyTarget();
    EXPECT_EQ(target, _creatureB);
}
TEST_F() [44/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , HasCombat_ReflectsState)
{
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasCombat());
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat());
    _creatureA->TestGetCombatMgr().EndAllPvECombat();
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasCombat());
}
TEST_F() [45/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , HasPvECombatWithPlayers_CreaturesOnly_ReturnsFalse)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    // All our units are creatures, not players
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasPvECombatWithPlayers());
}
TEST_F() [46/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , HasPvPCombat_NoPvPRefs_ReturnsFalse)
{
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasPvPCombat());
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    // Creatures create PvE refs, not PvP
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasPvPCombat());
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasPvECombat());
}
TEST_F() [47/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , InheritCombatStatesFrom_InheritsPvERefs)
{
    // C must be faction 90001 (hostile to B's 90002) so it can enter combat with B
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90001);
    // A is in combat with B
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_FALSE(creatureC->TestGetCombatMgr().IsInCombatWith(_creatureB));
    // C inherits A's combat states — should now be in combat with B
    creatureC->TestGetCombatMgr().InheritCombatStatesFrom(_creatureA);
    EXPECT_TRUE(creatureC->TestGetCombatMgr().IsInCombatWith(_creatureB));
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), CombatManager::InheritCombatStatesFrom(), CombatManager::IsInCombatWith(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and TestCreature::TestGetCombatMgr().
TEST_F() [48/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , InheritCombatStatesFrom_SkipsDuplicate)
{
    // C must be faction 90001 (hostile to B's 90002) so it can enter combat with B
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90001);
    // Both A and C already in combat with B
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    creatureC->TestGetCombatMgr().SetInCombatWith(_creatureB);
    // Should be a no-op (already in combat with B)
    creatureC->TestGetCombatMgr().InheritCombatStatesFrom(_creatureA);
    EXPECT_TRUE(creatureC->TestGetCombatMgr().IsInCombatWith(_creatureB));
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), CombatManager::InheritCombatStatesFrom(), CombatManager::IsInCombatWith(), TestCreature::SetFaction(), CombatManager::SetInCombatWith(), TestCreature::SetupForCombatTest(), and TestCreature::TestGetCombatMgr().
TEST_F() [49/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , InheritCombatStatesFrom_SkipsImmuneTargets)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    // Make C immune to NPCs — should skip inheriting combat with B
    creatureC->SetImmuneToNPC(true, false);
    creatureC->TestGetCombatMgr().InheritCombatStatesFrom(_creatureA);
    EXPECT_FALSE(creatureC->TestGetCombatMgr().IsInCombatWith(_creatureB));
    creatureC->SetImmuneToNPC(false, false);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), CombatManager::InheritCombatStatesFrom(), CombatManager::IsInCombatWith(), TestCreature::SetFaction(), Unit::SetImmuneToNPC(), TestCreature::SetupForCombatTest(), and TestCreature::TestGetCombatMgr().
TEST_F() [50/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , IsInCombatWith_ObjectGuid_Variant)
{
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB->GetGUID()));
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB->GetGUID()));
}
TEST_F() [51/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , IsNotReachableAndNeedRegen_Integration)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    EXPECT_FALSE(_creatureA->IsNotReachableAndNeedRegen());
    // Set unreachable — starts timer at 10s, not in regen yet
    _creatureA->SetCannotReachTarget(_creatureB->GetGUID());
    EXPECT_FALSE(_creatureA->IsNotReachableAndNeedRegen());
    // Advance past the regen threshold
    cm.Update(6000); // 4s left, within regen range
    EXPECT_TRUE(_creatureA->IsNotReachableAndNeedRegen());
    // Clear unreachable — regen stops
    _creatureA->SetCannotReachTarget();
    EXPECT_FALSE(_creatureA->IsNotReachableAndNeedRegen());
}
TEST_F() [52/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , MultipleRefs_IndependentLifecycle)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002);
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    _creatureA->TestGetCombatMgr().SetInCombatWith(creatureC);
    _creatureA->TestGetCombatMgr().SetInCombatWith(creatureD);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(creatureC));
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(creatureD));
    // End combat with C only
    auto const& refs = _creatureA->TestGetCombatMgr().GetPvECombatRefs();
    for (auto const& pair : refs)
    {
        if (pair.second->GetOther(_creatureA) == creatureC)
        {
            pair.second->EndCombat();
            break;
        }
    }
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(creatureC));
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(creatureD));
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat());
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [53/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , RevalidateCombat_DifferentPhase_RemovesIt)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    _creatureB->SetPhase(2);
    _creatureA->TestGetCombatMgr().RevalidateCombat();
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
}
TEST_F() [54/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , RevalidateCombat_InvalidRef_RemovesIt)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    // Make B dead — CanBeginCombat will now return false
    _creatureB->SetAlive(false);
    _creatureA->TestGetCombatMgr().RevalidateCombat();
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    _creatureB->SetAlive(true);
}
TEST_F() [55/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , RevalidateCombat_ValidRefs_KeepsAll)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    _creatureA->TestGetCombatMgr().RevalidateCombat();
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
}
TEST_F() [56/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SetCannotReachTarget_Clear_StopsEvade)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    _creatureA->SetCannotReachTarget(_creatureB->GetGUID());
    EXPECT_TRUE(cm.IsInEvadeMode());
    // Clear unreachable target — should stop evade
    _creatureA->SetCannotReachTarget();
    EXPECT_FALSE(cm.IsInEvadeMode());
    EXPECT_FALSE(_creatureA->CanNotReachTarget());
}
TEST_F() [57/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SetCannotReachTarget_SameTarget_NoDuplicate)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    _creatureA->SetCannotReachTarget(_creatureB->GetGUID());
    EXPECT_TRUE(cm.IsInEvadeMode());
    // Count down 5 seconds
    cm.Update(5000);
    // Setting the same target again should be a no-op (early return)
    _creatureA->SetCannotReachTarget(_creatureB->GetGUID());
    // Timer should NOT have been restarted — still mid-countdown
    // Advance 5 more seconds, timer should expire (was at 5s remaining)
    cm.Update(5000);
    EXPECT_FALSE(cm.IsInEvadeMode());
}
TEST_F() [58/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SetCannotReachTarget_StartsEvadeTimer)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    EXPECT_FALSE(cm.IsInEvadeMode());
    // Setting a target as unreachable starts the evade timer
    _creatureA->SetCannotReachTarget(_creatureB->GetGUID());
    EXPECT_TRUE(cm.IsInEvadeMode());
    EXPECT_TRUE(_creatureA->CanNotReachTarget());
}
TEST_F() [59/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SetEvadeState_SameState_DoesNotClearTimer)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    // Start evade timer (sets timer to 10s) and set evade state to COMBAT
    cm.StartEvadeTimer();
    cm.SetEvadeState(EVADE_STATE_COMBAT);
    EXPECT_TRUE(cm.IsInEvadeMode());
    // Set to COMBAT again — should be no-op, timer should NOT be affected
    cm.SetEvadeState(EVADE_STATE_COMBAT);
    EXPECT_TRUE(cm.IsInEvadeMode());
    // Timer should still be counting down normally
    cm.Update(5000);
    EXPECT_TRUE(cm.IsInEvadeMode());
    cm.StopEvade();
}
References EVADE_STATE_COMBAT.
TEST_F() [60/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SetEvadeState_SameState_NoOp)
{
    auto& cm = _creatureA->TestGetCombatMgr();
    // Set to HOME
    cm.SetEvadeState(EVADE_STATE_HOME);
    EXPECT_EQ(cm.GetEvadeState(), EVADE_STATE_HOME);
    EXPECT_TRUE(cm.IsEvadingHome());
    // Set to HOME again — early return, no crash, state unchanged
    cm.SetEvadeState(EVADE_STATE_HOME);
    EXPECT_EQ(cm.GetEvadeState(), EVADE_STATE_HOME);
    EXPECT_TRUE(cm.IsEvadingHome());
    // Same for NONE (after transitioning away first)
    cm.SetEvadeState(EVADE_STATE_NONE);
    EXPECT_EQ(cm.GetEvadeState(), EVADE_STATE_NONE);
    // NONE → NONE early return
    cm.SetEvadeState(EVADE_STATE_NONE);
    EXPECT_EQ(cm.GetEvadeState(), EVADE_STATE_NONE);
    EXPECT_FALSE(cm.IsInEvadeMode());
}
References EVADE_STATE_HOME, and EVADE_STATE_NONE.
TEST_F() [61/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SetImmuneToNPC_EndsCombatWithNPCs)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // A in combat with both B and C (all NPCs, none have UNIT_FLAG_PLAYER_CONTROLLED)
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    _creatureA->TestGetCombatMgr().SetInCombatWith(creatureC);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat());
    // SetImmuneToNPC should end combat with non-player-controlled units
    _creatureA->SetImmuneToNPC(true, false);
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(creatureC));
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasCombat());
    _creatureA->SetImmuneToNPC(false, false);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [62/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SetImmuneToNPC_KeepCombat_PreservesRefs)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat());
    // keepCombat=true should not end any combat
    _creatureA->SetImmuneToNPC(true, true);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    _creatureA->SetImmuneToNPC(false, false);
}
TEST_F() [63/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SetInCombatWith_CreatesReference)
{
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasCombat());
    bool result = _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(result);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat());
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    // Combat is bidirectional
    EXPECT_TRUE(_creatureB->TestGetCombatMgr().HasCombat());
    EXPECT_TRUE(_creatureB->TestGetCombatMgr().IsInCombatWith(_creatureA));
}
TEST_F() [64/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SetInCombatWith_DeadUnit_Fails)
{
    _creatureB->SetAlive(false);
    EXPECT_FALSE(CombatManager::CanBeginCombat(_creatureA, _creatureB));
}
References CombatManager::CanBeginCombat().
TEST_F() [65/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SetInCombatWith_DifferentPhase_Fails)
{
    _creatureB->SetPhase(2);
    EXPECT_FALSE(CombatManager::CanBeginCombat(_creatureA, _creatureB));
}
References CombatManager::CanBeginCombat().
TEST_F() [66/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SetInCombatWith_ExistingPvE_RefreshesRef)
{
    // Create initial combat with B suppressed
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB, true);
    EXPECT_FALSE(_creatureB->TestGetCombatMgr().HasPvECombat()); // suppressed
    // SetInCombatWith again (existing ref path) — should un-suppress via Refresh
    bool result = _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(result);
    EXPECT_TRUE(_creatureB->TestGetCombatMgr().HasPvECombat()); // refreshed
}
TEST_F() [67/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SetInCombatWith_SameUnit_Fails)
{
    EXPECT_FALSE(CombatManager::CanBeginCombat(_creatureA, _creatureA));
}
References CombatManager::CanBeginCombat().
TEST_F() [68/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , StopAttackFaction_EndsCombatForFaction)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90001); // same faction as A
    // A in combat with B (faction 90002), threat too
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    // Also have C fight B
    creatureC->TestGetThreatMgr().AddThreat(_creatureB, 200.0f);
    EXPECT_TRUE(creatureC->TestGetCombatMgr().IsInCombatWith(_creatureB));
    // A stops attacking faction 90002 (B's faction)
    _creatureA->StopAttackFaction(90002);
    // A should no longer be in combat with B, and threat should be cleared
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    // C's combat with B should be unaffected
    EXPECT_TRUE(creatureC->TestGetCombatMgr().IsInCombatWith(_creatureB));
    creatureC->CleanupCombatState();
    delete creatureC;
}
References ThreatManager::AddThreat(), TestCreature::CleanupCombatState(), CombatManager::IsInCombatWith(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), TestCreature::TestGetCombatMgr(), and TestCreature::TestGetThreatMgr().
TEST_F() [69/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SuppressedRef_DoesNotGenerateCombat)
{
    // Create combat with second unit suppressed
    bool result = _creatureA->TestGetCombatMgr().SetInCombatWith(
        _creatureB, /* addSecondUnitSuppressed */ true);
    EXPECT_TRUE(result);
    // A should be in combat (not suppressed)
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasPvECombat());
    // B's side is suppressed — check HasPvECombat (which skips suppressed refs)
    EXPECT_FALSE(_creatureB->TestGetCombatMgr().HasPvECombat());
    // But the reference still exists on both sides
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_TRUE(_creatureB->TestGetCombatMgr().IsInCombatWith(_creatureA));
}
TEST_F() [70/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SuppressFor_SuppressesOneSide)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasPvECombat());
    EXPECT_TRUE(_creatureB->TestGetCombatMgr().HasPvECombat());
    // Suppress B's side
    auto const& refs = _creatureA->TestGetCombatMgr().GetPvECombatRefs();
    ASSERT_FALSE(refs.empty());
    refs.begin()->second->SuppressFor(_creatureB);
    // A still in combat, B no longer
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasPvECombat());
    EXPECT_FALSE(_creatureB->TestGetCombatMgr().HasPvECombat());
    // But reference still exists on both sides
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    EXPECT_TRUE(_creatureB->TestGetCombatMgr().IsInCombatWith(_creatureA));
}
TEST_F() [71/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , SuppressPvPCombat_NoPvPRefs_DoesNotCrash)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    // Should not crash with no PvP refs
    _creatureA->TestGetCombatMgr().SuppressPvPCombat();
    // PvE combat should be unaffected
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasPvECombat());
}
TEST_F() [72/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , Update_EvadeTimerAndCombat_BothWork)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    _creatureA->TestGetCombatMgr().StartEvadeTimer();
    // Both combat and evade timer are active
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat());
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInEvadeMode());
    // Update ticks both
    _creatureA->TestGetCombatMgr().Update(5000);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat()); // combat unchanged
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInEvadeMode()); // timer still active
}
TEST_F() [73/73]
anonymous_namespace{CombatManagerTest.cpp}::TEST_F (CombatManagerIntegrationTest , Update_NoPvPRefs_DoesNotCrash)
{
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    // Update should handle PvP iteration gracefully when no PvP refs exist
    _creatureA->TestGetCombatMgr().Update(1000);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat());
}