AzerothCore: anonymous_namespace{GmVisibleCommandTest.cpp} Namespace Reference
anonymous_namespace{GmVisibleCommandTest.cpp} Namespace Reference
Classes
class GmVisibleCommandTest
class TestPlayer
class TestVisibilityScript
Functions
TEST_F (GmVisibleCommandTest, SetsPlayerInvisibleAndInvokesHook)
TEST_F (GmVisibleCommandTest, SetsPlayerVisibleAndInvokesHook)
Function Documentation
TEST_F() [1/2]
anonymous_namespace{GmVisibleCommandTest.cpp}::TEST_F (GmVisibleCommandTest , SetsPlayerInvisibleAndInvokesHook)
{
    ExecuteCommand(".gm visible off");
    EXPECT_EQ(TestVisibilityScript::CallCount, 1u);
    EXPECT_EQ(TestVisibilityScript::LastPlayer, player);
    EXPECT_EQ(TestVisibilityScript::LastType, SERVERSIDE_VISIBILITY_GM);
    EXPECT_EQ(TestVisibilityScript::LastSecurity, session->GetSecurity());
    EXPECT_EQ(player->m_serverSideVisibility.GetValue(SERVERSIDE_VISIBILITY_GM), uint32(session->GetSecurity()));
    EXPECT_FALSE(player->isGMVisible());
}
References anonymous_namespace{GmVisibleCommandTest.cpp}::TestVisibilityScript::CallCount, anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest::ExecuteCommand(), anonymous_namespace{GmVisibleCommandTest.cpp}::TestVisibilityScript::LastPlayer, anonymous_namespace{GmVisibleCommandTest.cpp}::TestVisibilityScript::LastSecurity, anonymous_namespace{GmVisibleCommandTest.cpp}::TestVisibilityScript::LastType, and SERVERSIDE_VISIBILITY_GM.
TEST_F() [2/2]
anonymous_namespace{GmVisibleCommandTest.cpp}::TEST_F (GmVisibleCommandTest , SetsPlayerVisibleAndInvokesHook)
{
    // Ensure the player starts from invisible state to test the opposite transition as well.
    ExecuteCommand(".gm visible off");
    TestVisibilityScript::Reset();
    ExecuteCommand(".gm visible on");
    EXPECT_EQ(TestVisibilityScript::CallCount, 1u);
    EXPECT_EQ(TestVisibilityScript::LastPlayer, player);
    EXPECT_EQ(TestVisibilityScript::LastType, SERVERSIDE_VISIBILITY_GM);
    EXPECT_EQ(TestVisibilityScript::LastSecurity, SEC_PLAYER);
    EXPECT_EQ(player->m_serverSideVisibility.GetValue(SERVERSIDE_VISIBILITY_GM), uint32(SEC_PLAYER));
    EXPECT_TRUE(player->isGMVisible());
}
References anonymous_namespace{GmVisibleCommandTest.cpp}::TestVisibilityScript::CallCount, anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest::ExecuteCommand(), anonymous_namespace{GmVisibleCommandTest.cpp}::TestVisibilityScript::LastPlayer, anonymous_namespace{GmVisibleCommandTest.cpp}::TestVisibilityScript::LastSecurity, anonymous_namespace{GmVisibleCommandTest.cpp}::TestVisibilityScript::LastType, anonymous_namespace{GmVisibleCommandTest.cpp}::TestVisibilityScript::Reset(), SEC_PLAYER, and SERVERSIDE_VISIBILITY_GM.