AzerothCore: azerothcore-wotlk/src/test/server/game/Spells/SpellImmunityTest.cpp File Reference
SpellImmunityTest.cpp File Reference
Tests for spell immunity mechanics.
#include "gtest/gtest.h"
#include <algorithm>
#include <array>
#include <cstdint>
#include "Unit.h"
Classes
struct anonymous_namespace{SpellImmunityTest.cpp}::EffectDesc
struct anonymous_namespace{SpellImmunityTest.cpp}::SpellDesc
struct anonymous_namespace{SpellImmunityTest.cpp}::EffectApplyResult
Namespaces
namespace anonymous_namespace{SpellImmunityTest.cpp}
Enumerations
enum anonymous_namespace{SpellImmunityTest.cpp}::EffectType : uint8_t {
anonymous_namespace{SpellImmunityTest.cpp}::EFFECT_NONE ,
anonymous_namespace{SpellImmunityTest.cpp}::EFFECT_SCHOOL_DAMAGE ,
anonymous_namespace{SpellImmunityTest.cpp}::EFFECT_HEALTH_LEECH ,
anonymous_namespace{SpellImmunityTest.cpp}::EFFECT_POWER_DRAIN ,
anonymous_namespace{SpellImmunityTest.cpp}::EFFECT_POWER_BURN ,
anonymous_namespace{SpellImmunityTest.cpp}::EFFECT_NORMALIZED_WEAPON_DMG ,
anonymous_namespace{SpellImmunityTest.cpp}::EFFECT_WEAPON_PERCENT_DAMAGE ,
anonymous_namespace{SpellImmunityTest.cpp}::EFFECT_APPLY_AURA ,
anonymous_namespace{SpellImmunityTest.cpp}::EFFECT_DUMMY
}
enum anonymous_namespace{SpellImmunityTest.cpp}::AuraType : uint8_t {
anonymous_namespace{SpellImmunityTest.cpp}::AURA_NONE ,
anonymous_namespace{SpellImmunityTest.cpp}::AURA_MOD_DECREASE_SPEED ,
anonymous_namespace{SpellImmunityTest.cpp}::AURA_PERIODIC_DAMAGE ,
anonymous_namespace{SpellImmunityTest.cpp}::AURA_TRANSFORM ,
anonymous_namespace{SpellImmunityTest.cpp}::AURA_MOD_STUN
}
Functions
bool anonymous_namespace{SpellImmunityTest.cpp}::IsDamageEffect (EffectType effect)
bool anonymous_namespace{SpellImmunityTest.cpp}::HasOnlyDamageEffects (SpellDesc const &spell)
bool anonymous_namespace{SpellImmunityTest.cpp}::IsStunSpell (SpellDesc const &spell)
bool anonymous_namespace{SpellImmunityTest.cpp}::IsEffectBlockedByStunImmunity (EffectDesc const &effect, bool immuneToStun)
bool anonymous_namespace{SpellImmunityTest.cpp}::IsFullyImmunedByStunImmunity (SpellDesc const &spell, bool immuneToStun)
bool anonymous_namespace{SpellImmunityTest.cpp}::IsBlockedBySchoolImmunity (bool casterFriendly, bool immunityAppliesToFriendly)
SpellMissInfo anonymous_namespace{SpellImmunityTest.cpp}::ComputeSpellHitResult (bool isImmunedToSpell, bool isImmunedToDamage, SpellDesc const &spell, bool immuneToStun=false)
EffectApplyResult anonymous_namespace{SpellImmunityTest.cpp}::ApplyEffectsWithMovementImmunity (SpellDesc const &spell, bool immuneToMovementImpairing)
SpellDesc anonymous_namespace{SpellImmunityTest.cpp}::MakeDamageOnlySpell ()
SpellDesc anonymous_namespace{SpellImmunityTest.cpp}::MakeFrostboltLikeSpell ()
SpellDesc anonymous_namespace{SpellImmunityTest.cpp}::MakeCycloneLikeSpell ()
SpellDesc anonymous_namespace{SpellImmunityTest.cpp}::MakeSlowOnlySpell ()
TEST (SpellImmunityTest, HasOnlyDamageEffects_TrueForPureDamage)
TEST (SpellImmunityTest, HasOnlyDamageEffects_FalseForDamagePlusAura)
TEST (SpellImmunityTest, SpellImmunity_BlocksAllSpells)
TEST (SpellImmunityTest, DamageImmunity_BlocksDamageOnlySpell)
TEST (SpellImmunityTest, SelfInvulnerability_BlocksMeleeDamage)
TEST (SpellImmunityTest, DamageImmunity_DoesNotMissMixedSpell)
TEST (SpellImmunityTest, HandOfFreedomStyle_MovementImmunity_AllowsDamageBlocksSlow)
TEST (SpellImmunityTest, NoMovementImmunity_FrostboltStyle_AppliesDamageAndSlow)
TEST (SpellImmunityTest, CycloneLikeSpell_DivineShieldStyle_Immune)
TEST (SpellImmunityTest, SpellImmunity_BlocksSlowOnlySpell)
TEST (SpellImmunityTest, DamageImmunity_DoesNotBlockSlowOnlySpell)
TEST (SpellImmunityTest, ImmunityMask_PartialOverlapDoesNotCount)
TEST (SpellImmunityTest, ImmunityMask_FullCoverageAccepted)
TEST (SpellImmunityTest, ImmunityMask_SupersetMatches)
TEST (SpellImmunityTest, Bladestorm_ImmuneToStun)
TEST (SpellImmunityTest, StunImmunity_DoesNotFullyBlockMixedSpell)
TEST (SpellImmunityTest, SchoolImmunity_TemplateStyle_AllowsFriendlySpell)
TEST (SpellImmunityTest, SchoolImmunity_ExplicitFriendlyBlockStillApplies)
TEST (SpellImmunityTest, SchoolImmunity_BlocksHostileSpell)
Detailed Description
Tests for spell immunity mechanics.
Definition in file SpellImmunityTest.cpp.
Function Documentation
TEST() [1/19]
TEST (SpellImmunityTest , Bladestorm_ImmuneToStun)
{
    SpellDesc stunSpell;
    stunSpell.effects[0] = {EFFECT_APPLY_AURA, AURA_MOD_STUN};
    // without any special immunity the stun should land
    EXPECT_EQ(ComputeSpellHitResult(false, false, stunSpell), SPELL_MISS_NONE);
    // with a bladestorm‑style stun immunity it is blocked
    EXPECT_EQ(ComputeSpellHitResult(false, false, stunSpell, true), SPELL_MISS_IMMUNE);
}
References anonymous_namespace{SpellImmunityTest.cpp}::AURA_MOD_STUN, anonymous_namespace{SpellImmunityTest.cpp}::ComputeSpellHitResult(), anonymous_namespace{SpellImmunityTest.cpp}::EFFECT_APPLY_AURA, SPELL_MISS_IMMUNE, and SPELL_MISS_NONE.
TEST() [2/19]
TEST (SpellImmunityTest , CycloneLikeSpell_DivineShieldStyle_Immune)
{
    SpellDesc cycloneLike = MakeCycloneLikeSpell();
    EXPECT_EQ(ComputeSpellHitResult(true, false, cycloneLike), SPELL_MISS_IMMUNE);
}
References anonymous_namespace{SpellImmunityTest.cpp}::ComputeSpellHitResult(), anonymous_namespace{SpellImmunityTest.cpp}::MakeCycloneLikeSpell(), and SPELL_MISS_IMMUNE.
TEST() [3/19]
TEST (SpellImmunityTest , DamageImmunity_BlocksDamageOnlySpell)
{
    SpellDesc damageOnly = MakeDamageOnlySpell();
    EXPECT_EQ(ComputeSpellHitResult(false, true, damageOnly), SPELL_MISS_IMMUNE);
}
References anonymous_namespace{SpellImmunityTest.cpp}::ComputeSpellHitResult(), anonymous_namespace{SpellImmunityTest.cpp}::MakeDamageOnlySpell(), and SPELL_MISS_IMMUNE.
TEST() [4/19]
TEST (SpellImmunityTest , DamageImmunity_DoesNotBlockSlowOnlySpell)
{
    SpellDesc slowOnly = MakeSlowOnlySpell();
    EXPECT_EQ(ComputeSpellHitResult(false, true, slowOnly), SPELL_MISS_NONE);
}
References anonymous_namespace{SpellImmunityTest.cpp}::ComputeSpellHitResult(), anonymous_namespace{SpellImmunityTest.cpp}::MakeSlowOnlySpell(), and SPELL_MISS_NONE.
TEST() [5/19]
TEST (SpellImmunityTest , DamageImmunity_DoesNotMissMixedSpell)
{
    // This is the key fix: damage immunity must not force SPELL_MISS_IMMUNE
    // for mixed spells that include non-damage effects.
    SpellDesc frostboltLike = MakeFrostboltLikeSpell();
    EXPECT_EQ(ComputeSpellHitResult(false, true, frostboltLike), SPELL_MISS_NONE);
}
References anonymous_namespace{SpellImmunityTest.cpp}::ComputeSpellHitResult(), anonymous_namespace{SpellImmunityTest.cpp}::MakeFrostboltLikeSpell(), and SPELL_MISS_NONE.
TEST() [6/19]
TEST (SpellImmunityTest , HandOfFreedomStyle_MovementImmunity_AllowsDamageBlocksSlow)
{
    SpellDesc frostboltLike = MakeFrostboltLikeSpell();
    EffectApplyResult result = ApplyEffectsWithMovementImmunity(frostboltLike, true);
    EXPECT_TRUE(result.damageApplied);
    EXPECT_FALSE(result.slowApplied);
}
References anonymous_namespace{SpellImmunityTest.cpp}::ApplyEffectsWithMovementImmunity(), and anonymous_namespace{SpellImmunityTest.cpp}::MakeFrostboltLikeSpell().
TEST() [7/19]
TEST (SpellImmunityTest , HasOnlyDamageEffects_FalseForDamagePlusAura)
{
    SpellDesc spell = MakeFrostboltLikeSpell();
    EXPECT_FALSE(HasOnlyDamageEffects(spell));
}
References anonymous_namespace{SpellImmunityTest.cpp}::HasOnlyDamageEffects(), and anonymous_namespace{SpellImmunityTest.cpp}::MakeFrostboltLikeSpell().
TEST() [8/19]
TEST (SpellImmunityTest , HasOnlyDamageEffects_TrueForPureDamage)
{
    SpellDesc spell = MakeDamageOnlySpell();
    EXPECT_TRUE(HasOnlyDamageEffects(spell));
}
References anonymous_namespace{SpellImmunityTest.cpp}::HasOnlyDamageEffects(), and anonymous_namespace{SpellImmunityTest.cpp}::MakeDamageOnlySpell().
TEST() [9/19]
TEST (SpellImmunityTest , ImmunityMask_FullCoverageAccepted)
{
    SpellSchoolMask immune = SPELL_SCHOOL_MASK_MAGIC; // holy+spell
    SpellSchoolMask checkMagic = SPELL_SCHOOL_MASK_MAGIC;
    SpellSchoolMask checkSpell = SPELL_SCHOOL_MASK_SPELL;
    EXPECT_TRUE(Unit::IsImmuneMaskFully(immune, checkMagic));
    EXPECT_TRUE(Unit::IsImmuneMaskFully(immune, checkSpell));
}
References Unit::IsImmuneMaskFully(), SPELL_SCHOOL_MASK_MAGIC, and SPELL_SCHOOL_MASK_SPELL.
TEST() [10/19]
TEST (SpellImmunityTest , ImmunityMask_PartialOverlapDoesNotCount)
{
    SpellSchoolMask immune = SPELL_SCHOOL_MASK_FROST;
    SpellSchoolMask checkAll = SPELL_SCHOOL_MASK_ALL;
    // a frost-only immunity should *not* make you immune to all damage
    EXPECT_FALSE(Unit::IsImmuneMaskFully(immune, checkAll));
}
References Unit::IsImmuneMaskFully(), SPELL_SCHOOL_MASK_ALL, and SPELL_SCHOOL_MASK_FROST.
TEST() [11/19]
TEST (SpellImmunityTest , ImmunityMask_SupersetMatches)
{
    SpellSchoolMask immune = SPELL_SCHOOL_MASK_ALL;
    SpellSchoolMask checkMagic = SPELL_SCHOOL_MASK_MAGIC;
    EXPECT_TRUE(Unit::IsImmuneMaskFully(immune, checkMagic));
}
References Unit::IsImmuneMaskFully(), SPELL_SCHOOL_MASK_ALL, and SPELL_SCHOOL_MASK_MAGIC.
TEST() [12/19]
TEST (SpellImmunityTest , NoMovementImmunity_FrostboltStyle_AppliesDamageAndSlow)
{
    SpellDesc frostboltLike = MakeFrostboltLikeSpell();
    EffectApplyResult result = ApplyEffectsWithMovementImmunity(frostboltLike, false);
    EXPECT_TRUE(result.damageApplied);
    EXPECT_TRUE(result.slowApplied);
}
References anonymous_namespace{SpellImmunityTest.cpp}::ApplyEffectsWithMovementImmunity(), and anonymous_namespace{SpellImmunityTest.cpp}::MakeFrostboltLikeSpell().
TEST() [13/19]
TEST (SpellImmunityTest , SchoolImmunity_BlocksHostileSpell)
{
    EXPECT_TRUE(IsBlockedBySchoolImmunity(false, false));
}
References anonymous_namespace{SpellImmunityTest.cpp}::IsBlockedBySchoolImmunity().
TEST() [14/19]
TEST (SpellImmunityTest , SchoolImmunity_ExplicitFriendlyBlockStillApplies)
{
    EXPECT_TRUE(IsBlockedBySchoolImmunity(true, true));
}
References anonymous_namespace{SpellImmunityTest.cpp}::IsBlockedBySchoolImmunity().
TEST() [15/19]
TEST (SpellImmunityTest , SchoolImmunity_TemplateStyle_AllowsFriendlySpell)
{
    EXPECT_FALSE(IsBlockedBySchoolImmunity(true, false));
}
References anonymous_namespace{SpellImmunityTest.cpp}::IsBlockedBySchoolImmunity().
TEST() [16/19]
TEST (SpellImmunityTest , SelfInvulnerability_BlocksMeleeDamage)
{
    SpellDesc meleeAttack = MakeDamageOnlySpell();
    // simulate physical damage coming from a rogue melee ability
    EXPECT_EQ(ComputeSpellHitResult(false, true, meleeAttack), SPELL_MISS_IMMUNE);
}
References anonymous_namespace{SpellImmunityTest.cpp}::ComputeSpellHitResult(), anonymous_namespace{SpellImmunityTest.cpp}::MakeDamageOnlySpell(), and SPELL_MISS_IMMUNE.
TEST() [17/19]
TEST (SpellImmunityTest , SpellImmunity_BlocksAllSpells)
{
    SpellDesc damageOnly = MakeDamageOnlySpell();
    SpellDesc cycloneLike = MakeCycloneLikeSpell();
    EXPECT_EQ(ComputeSpellHitResult(true, false, damageOnly), SPELL_MISS_IMMUNE);
    EXPECT_EQ(ComputeSpellHitResult(true, false, cycloneLike), SPELL_MISS_IMMUNE);
}
References anonymous_namespace{SpellImmunityTest.cpp}::ComputeSpellHitResult(), anonymous_namespace{SpellImmunityTest.cpp}::MakeCycloneLikeSpell(), anonymous_namespace{SpellImmunityTest.cpp}::MakeDamageOnlySpell(), and SPELL_MISS_IMMUNE.
TEST() [18/19]
TEST (SpellImmunityTest , SpellImmunity_BlocksSlowOnlySpell)
{
    SpellDesc slowOnly = MakeSlowOnlySpell();
    EXPECT_EQ(ComputeSpellHitResult(true, false, slowOnly), SPELL_MISS_IMMUNE);
}
References anonymous_namespace{SpellImmunityTest.cpp}::ComputeSpellHitResult(), anonymous_namespace{SpellImmunityTest.cpp}::MakeSlowOnlySpell(), and SPELL_MISS_IMMUNE.
TEST() [19/19]
TEST (SpellImmunityTest , StunImmunity_DoesNotFullyBlockMixedSpell)
{
    SpellDesc mixedSpell;
    mixedSpell.effects[0] = { EFFECT_SCHOOL_DAMAGE, AURA_NONE };
    mixedSpell.effects[1] = { EFFECT_APPLY_AURA, AURA_MOD_STUN };
    // This models partial immunity: stun effect is blocked, damage still hits.
    EXPECT_TRUE(IsStunSpell(mixedSpell));
    EXPECT_EQ(ComputeSpellHitResult(false, false, mixedSpell, true), SPELL_MISS_NONE);
}
References anonymous_namespace{SpellImmunityTest.cpp}::AURA_MOD_STUN, anonymous_namespace{SpellImmunityTest.cpp}::AURA_NONE, anonymous_namespace{SpellImmunityTest.cpp}::ComputeSpellHitResult(), anonymous_namespace{SpellImmunityTest.cpp}::EFFECT_APPLY_AURA, anonymous_namespace{SpellImmunityTest.cpp}::EFFECT_SCHOOL_DAMAGE, anonymous_namespace{SpellImmunityTest.cpp}::IsStunSpell(), and SPELL_MISS_NONE.