AzerothCore: OutdoorPvPEP Class Reference
OutdoorPvPEP Class Reference
#include "OutdoorPvPEP.h"
Public Member Functions
OutdoorPvPEP ()
bool SetupOutdoorPvP () override
void HandlePlayerEnterZone (Player *player, uint32 zone) override
void HandlePlayerLeaveZone (Player *player, uint32 zone) override
bool Update (uint32 diff) override
void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &packet) override
void SendRemoveWorldStates (Player *player) override
void BuffTeams ()
void SetControlledState (uint32 index, TeamId teamId)
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()=default
~OutdoorPvP () override
void DeleteSpawns ()
virtual void FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates &)
virtual bool HandleAreaTrigger (Player *player, uint32 trigger)
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual bool HandleOpenGo (Player *player, GameObject *go)
virtual bool SetupOutdoorPvP ()
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void SendUpdateWorldState (uint32 field, uint32 value)
virtual bool Update (uint32 diff)
virtual void HandleKill (Player *killer, Unit *killed)
virtual void HandleKillImpl (Player *, Unit *)
bool IsInsideObjective (Player *player) const
virtual void AwardKillBonus (Player *)
uint32 GetTypeId () const
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipId)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
void TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2=0, Player *sameMapPlr=nullptr)
Map * GetMap () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual void OnCreatureEvade (Creature *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
TeamId EP_ControlsId [EP_TOWER_NUM]
uint32 m_AllianceTowersControlled
uint32 m_HordeTowersControlled
Additional Inherited Members
Public Types inherited from OutdoorPvP
typedef std::map< ObjectGuid::LowType, OPvPCapturePoint * > OPvPCapturePointMap
typedef std::pair< ObjectGuid::LowType, GameObject * > GoScriptPair
typedef std::pair< ObjectGuid::LowType, Creature * > CreatureScriptPair
Protected Member Functions inherited from OutdoorPvP
void BroadcastPacket (WorldPacket &data) const
virtual void SendRemoveWorldStates (Player *)
virtual void HandlePlayerEnterZone (Player *player, uint32 zone)
virtual void HandlePlayerLeaveZone (Player *player, uint32 zone)
virtual void HandlePlayerResurrects (Player *player, uint32 zone)
void AddCapturePoint (OPvPCapturePoint *cp)
OPvPCapturePoint * GetCapturePoint (ObjectGuid::LowType spawnId) const
void RegisterZone (uint32 zoneid)
bool HasPlayer (Player const *player) const
void TeamCastSpell (TeamId team, int32 spellId, Player *sameMapPlr=nullptr)
void SetMapFromZone (uint32 zone)
Protected Attributes inherited from OutdoorPvP
OPvPCapturePointMap _capturePoints
std::array< PlayerSet, 2 > _players
uint32 _typeId {}
bool _sendUpdate { true }
Map * _map {}
std::unordered_map< ObjectGuid::LowType, GameObject * > _goScriptStore
std::unordered_map< ObjectGuid::LowType, Creature * > _creatureScriptStore
Detailed Description
Constructor & Destructor Documentation
OutdoorPvPEP()
OutdoorPvPEP::OutdoorPvPEP ()
{
    _typeId = OUTDOOR_PVP_EP;
    memset(EP_ControlsId, TEAM_NEUTRAL, sizeof(EP_ControlsId));
    m_AllianceTowersControlled = 0;
    m_HordeTowersControlled = 0;
}
References OutdoorPvP::_typeId, EP_ControlsId, m_AllianceTowersControlled, m_HordeTowersControlled, OUTDOOR_PVP_EP, and TEAM_NEUTRAL.
Member Function Documentation
BuffTeams()
void OutdoorPvPEP::BuffTeams ()
{
    for (PlayerSet::iterator itr = _players[0].begin(); itr != _players[0].end(); ++itr)
    {
        if (Player* player = ObjectAccessor::FindPlayer(*itr))
        {
            for (int i = 0; i < 4; ++i)
                player->RemoveAurasDueToSpell(EP_AllianceBuffs[i]);
            if (m_AllianceTowersControlled && m_AllianceTowersControlled < 5)
                player->CastSpell(player, EP_AllianceBuffs[m_AllianceTowersControlled - 1], true);
        }
    }
    for (PlayerSet::iterator itr = _players[1].begin(); itr != _players[1].end(); ++itr)
    {
        if (Player* player = ObjectAccessor::FindPlayer(*itr))
        {
            for (int i = 0; i < 4; ++i)
                player->RemoveAurasDueToSpell(EP_HordeBuffs[i]);
            if (m_HordeTowersControlled && m_HordeTowersControlled < 5)
                player->CastSpell(player, EP_HordeBuffs[m_HordeTowersControlled - 1], true);
        }
    }
}
References OutdoorPvP::_players, EP_AllianceBuffs, EP_HordeBuffs, ObjectAccessor::FindPlayer(), m_AllianceTowersControlled, and m_HordeTowersControlled.
Referenced by Update().
FillInitialWorldStates()
void OutdoorPvPEP::FillInitialWorldStates (WorldPackets::WorldState::InitWorldStates & packet) override virtual
Reimplemented from OutdoorPvP.
{
    packet.Worldstates.reserve(5);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_A, m_AllianceTowersControlled);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_H, m_HordeTowersControlled);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_DISPLAY, 0);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_POS, 50);
    packet.Worldstates.emplace_back(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_N, 100);
    for (OPvPCapturePointMap::iterator itr = _capturePoints.begin(); itr != _capturePoints.end(); ++itr)
    {
        itr->second->FillInitialWorldStates(packet);
    }
}
References OutdoorPvP::_capturePoints, m_AllianceTowersControlled, m_HordeTowersControlled, WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_A, WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_H, WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_DISPLAY, WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_N, WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_POS, and WorldPackets::WorldState::InitWorldStates::Worldstates.
HandlePlayerEnterZone()
void OutdoorPvPEP::HandlePlayerEnterZone (Player * player, uint32 zone) override virtual
Reimplemented from OutdoorPvP.
{
    // add buffs
    if (player->GetTeamId() == TEAM_ALLIANCE)
    {
        if (m_AllianceTowersControlled && m_AllianceTowersControlled < 5)
            player->CastSpell(player, EP_AllianceBuffs[m_AllianceTowersControlled - 1], true);
    }
    else
    {
        if (m_HordeTowersControlled && m_HordeTowersControlled < 5)
            player->CastSpell(player, EP_HordeBuffs[m_HordeTowersControlled - 1], true);
    }
    OutdoorPvP::HandlePlayerEnterZone(player, zone);
}
References Unit::CastSpell(), EP_AllianceBuffs, EP_HordeBuffs, Player::GetTeamId(), OutdoorPvP::HandlePlayerEnterZone(), m_AllianceTowersControlled, m_HordeTowersControlled, and TEAM_ALLIANCE.
HandlePlayerLeaveZone()
void OutdoorPvPEP::HandlePlayerLeaveZone (Player * player, uint32 zone) override virtual
Reimplemented from OutdoorPvP.
{
    // remove buffs
    if (player->GetTeamId() == TEAM_ALLIANCE)
    {
        for (int i = 0; i < 4; ++i)
            player->RemoveAurasDueToSpell(EP_AllianceBuffs[i]);
    }
    else
    {
        for (int i = 0; i < 4; ++i)
            player->RemoveAurasDueToSpell(EP_HordeBuffs[i]);
    }
    OutdoorPvP::HandlePlayerLeaveZone(player, zone);
}
References EP_AllianceBuffs, EP_HordeBuffs, Player::GetTeamId(), OutdoorPvP::HandlePlayerLeaveZone(), Unit::RemoveAurasDueToSpell(), and TEAM_ALLIANCE.
SendRemoveWorldStates()
void OutdoorPvPEP::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
{
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_A, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_H, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_DISPLAY, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_POS, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_N, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_EASTWALLTOWER_A, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_EASTWALLTOWER_H, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_EASTWALLTOWER_N, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_EASTWALLTOWER_N_A, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_EASTWALLTOWER_N_H, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_A, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_H, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_A, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_H, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_NORTHPASSTOWER_A, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_NORTHPASSTOWER_H, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_NORTHPASSTOWER_N, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_NORTHPASSTOWER_N_A, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_NORTHPASSTOWER_N_H, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_A, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_H, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_N, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_N_A, 0);
    player->SendUpdateWorldState(WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_N_H, 0);
}
References Player::SendUpdateWorldState(), WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_A, WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_H, WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_N, WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_N_A, WORLD_STATE_OPVP_EP_CROWNGUARDTOWER_N_H, WORLD_STATE_OPVP_EP_EASTWALLTOWER_A, WORLD_STATE_OPVP_EP_EASTWALLTOWER_H, WORLD_STATE_OPVP_EP_EASTWALLTOWER_N, WORLD_STATE_OPVP_EP_EASTWALLTOWER_N_A, WORLD_STATE_OPVP_EP_EASTWALLTOWER_N_H, WORLD_STATE_OPVP_EP_NORTHPASSTOWER_A, WORLD_STATE_OPVP_EP_NORTHPASSTOWER_H, WORLD_STATE_OPVP_EP_NORTHPASSTOWER_N, WORLD_STATE_OPVP_EP_NORTHPASSTOWER_N_A, WORLD_STATE_OPVP_EP_NORTHPASSTOWER_N_H, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_A, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_H, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_A, WORLD_STATE_OPVP_EP_PLAGUEWOODTOWER_N_H, WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_A, WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_H, WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_DISPLAY, WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_N, and WORLD_STATE_OPVP_EP_UI_TOWER_SLIDER_POS.
SetControlledState()
void OutdoorPvPEP::SetControlledState (uint32 index, TeamId teamId)
{
    EP_ControlsId[index] = teamId;
}
References EP_ControlsId.
SetupOutdoorPvP()
bool OutdoorPvPEP::SetupOutdoorPvP () override virtual
Reimplemented from OutdoorPvP.
{
    for (uint8 i = 0; i < EPBuffZonesNum; ++i)
        RegisterZone(EPBuffZones[i]);
    SetMapFromZone(EPBuffZones[0]);
    AddCapturePoint(new OPvPCapturePointEP_EWT(this));
    AddCapturePoint(new OPvPCapturePointEP_PWT(this));
    AddCapturePoint(new OPvPCapturePointEP_CGT(this));
    AddCapturePoint(new OPvPCapturePointEP_NPT(this));
    return true;
}
References OutdoorPvP::AddCapturePoint(), EPBuffZones, EPBuffZonesNum, OutdoorPvP::RegisterZone(), and OutdoorPvP::SetMapFromZone().
Update()
bool OutdoorPvPEP::Update (uint32 diff) override virtual
Reimplemented from OutdoorPvP.
{
    if (OutdoorPvP::Update(diff))
    {
        m_AllianceTowersControlled = 0;
        m_HordeTowersControlled = 0;
        for (int i = 0; i < EP_TOWER_NUM; ++i)
        {
            if (EP_ControlsId[i] == TEAM_ALLIANCE)
                ++m_AllianceTowersControlled;
            else if (EP_ControlsId[i] == TEAM_HORDE)
                ++m_HordeTowersControlled;
            SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_A, m_AllianceTowersControlled);
            SendUpdateWorldState(WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_H, m_HordeTowersControlled);
            BuffTeams();
        }
        return true;
    }
    return false;
}
References BuffTeams(), EP_ControlsId, EP_TOWER_NUM, m_AllianceTowersControlled, m_HordeTowersControlled, OutdoorPvP::SendUpdateWorldState(), TEAM_ALLIANCE, TEAM_HORDE, OutdoorPvP::Update(), WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_A, and WORLD_STATE_OPVP_EP_UI_TOWER_COUNT_H.
Member Data Documentation
EP_ControlsId
TeamId OutdoorPvPEP::EP_ControlsId[EP_TOWER_NUM] private
Referenced by OutdoorPvPEP(), SetControlledState(), and Update().
m_AllianceTowersControlled
uint32 OutdoorPvPEP::m_AllianceTowersControlled private
Referenced by BuffTeams(), FillInitialWorldStates(), HandlePlayerEnterZone(), OutdoorPvPEP(), and Update().
m_HordeTowersControlled
uint32 OutdoorPvPEP::m_HordeTowersControlled private
Referenced by BuffTeams(), FillInitialWorldStates(), HandlePlayerEnterZone(), OutdoorPvPEP(), and Update().