AzerothCore: azerothcore-wotlk/src/server/scripts/Commands/cs_script_loader.cpp File Reference
cs_script_loader.cpp File Reference
Functions
void AddSC_account_commandscript ()
void AddSC_achievement_commandscript ()
void AddSC_arena_commandscript ()
void AddSC_autobroadcast_commandscript ()
void AddSC_bag_commandscript ()
void AddSC_ban_commandscript ()
void AddSC_bf_commandscript ()
void AddSC_cast_commandscript ()
void AddSC_character_commandscript ()
void AddSC_cheat_commandscript ()
void AddSC_debug_commandscript ()
void AddSC_deserter_commandscript ()
void AddSC_disable_commandscript ()
void AddSC_event_commandscript ()
void AddSC_gear_commandscript ()
void AddSC_gm_commandscript ()
void AddSC_go_commandscript ()
void AddSC_gobject_commandscript ()
void AddSC_group_commandscript ()
void AddSC_guild_commandscript ()
void AddSC_honor_commandscript ()
void AddSC_instance_commandscript ()
void AddSC_inventory_commandscript ()
void AddSC_learn_commandscript ()
void AddSC_lfg_commandscript ()
void AddSC_list_commandscript ()
void AddSC_lookup_commandscript ()
void AddSC_mail_commandscript ()
void AddSC_message_commandscript ()
void AddSC_misc_commandscript ()
void AddSC_mmaps_commandscript ()
void AddSC_modify_commandscript ()
void AddSC_npc_commandscript ()
void AddSC_pet_commandscript ()
void AddSC_player_commandscript ()
void AddSC_pool_commandscript ()
void AddSC_pooltools_commandscript ()
void AddSC_quest_commandscript ()
void AddSC_rbac_commandscript ()
void AddSC_reload_commandscript ()
void AddSC_reset_commandscript ()
void AddSC_send_commandscript ()
void AddSC_server_commandscript ()
void AddSC_spectator_commandscript ()
void AddSC_spellinfo_commandscript ()
void AddSC_tele_commandscript ()
void AddSC_ticket_commandscript ()
void AddSC_titles_commandscript ()
void AddSC_wp_commandscript ()
void AddSC_cache_commandscript ()
void AddSC_item_commandscript ()
void AddSC_player_settings_commandscript ()
void AddSC_worldstate_commandscript ()
void AddCommandsScripts ()
Function Documentation
AddCommandsScripts()
void AddCommandsScripts ()
{
    AddSC_account_commandscript();
    AddSC_achievement_commandscript();
    AddSC_arena_commandscript();
    AddSC_autobroadcast_commandscript();
    AddSC_bag_commandscript();
    AddSC_ban_commandscript();
    AddSC_bf_commandscript();
    AddSC_cast_commandscript();
    AddSC_character_commandscript();
    AddSC_cheat_commandscript();
    AddSC_debug_commandscript();
    AddSC_deserter_commandscript();
    AddSC_disable_commandscript();
    AddSC_event_commandscript();
    AddSC_gear_commandscript();
    AddSC_gm_commandscript();
    AddSC_go_commandscript();
    AddSC_gobject_commandscript();
    AddSC_group_commandscript();
    AddSC_guild_commandscript();
    AddSC_honor_commandscript();
    AddSC_instance_commandscript();
    AddSC_inventory_commandscript();
    AddSC_learn_commandscript();
    AddSC_lfg_commandscript();
    AddSC_list_commandscript();
    AddSC_lookup_commandscript();
    AddSC_mail_commandscript();
    AddSC_message_commandscript();
    AddSC_misc_commandscript();
    AddSC_mmaps_commandscript();
    AddSC_modify_commandscript();
    AddSC_npc_commandscript();
    AddSC_pet_commandscript();
    AddSC_player_commandscript();
    AddSC_pool_commandscript();
    AddSC_pooltools_commandscript();
    AddSC_quest_commandscript();
    AddSC_rbac_commandscript();
    AddSC_reload_commandscript();
    AddSC_reset_commandscript();
    AddSC_send_commandscript();
    AddSC_server_commandscript();
    AddSC_spectator_commandscript();
    AddSC_spellinfo_commandscript();
    AddSC_tele_commandscript();
    AddSC_ticket_commandscript();
    AddSC_titles_commandscript();
    AddSC_wp_commandscript();
    AddSC_cache_commandscript();
    AddSC_item_commandscript();
    AddSC_player_settings_commandscript();
    AddSC_worldstate_commandscript();
}
References AddSC_account_commandscript(), AddSC_achievement_commandscript(), AddSC_arena_commandscript(), AddSC_autobroadcast_commandscript(), AddSC_bag_commandscript(), AddSC_ban_commandscript(), AddSC_bf_commandscript(), AddSC_cache_commandscript(), AddSC_cast_commandscript(), AddSC_character_commandscript(), AddSC_cheat_commandscript(), AddSC_debug_commandscript(), AddSC_deserter_commandscript(), AddSC_disable_commandscript(), AddSC_event_commandscript(), AddSC_gear_commandscript(), AddSC_gm_commandscript(), AddSC_go_commandscript(), AddSC_gobject_commandscript(), AddSC_group_commandscript(), AddSC_guild_commandscript(), AddSC_honor_commandscript(), AddSC_instance_commandscript(), AddSC_inventory_commandscript(), AddSC_item_commandscript(), AddSC_learn_commandscript(), AddSC_lfg_commandscript(), AddSC_list_commandscript(), AddSC_lookup_commandscript(), AddSC_mail_commandscript(), AddSC_message_commandscript(), AddSC_misc_commandscript(), AddSC_mmaps_commandscript(), AddSC_modify_commandscript(), AddSC_npc_commandscript(), AddSC_pet_commandscript(), AddSC_player_commandscript(), AddSC_player_settings_commandscript(), AddSC_pool_commandscript(), AddSC_pooltools_commandscript(), AddSC_quest_commandscript(), AddSC_rbac_commandscript(), AddSC_reload_commandscript(), AddSC_reset_commandscript(), AddSC_send_commandscript(), AddSC_server_commandscript(), AddSC_spectator_commandscript(), AddSC_spellinfo_commandscript(), AddSC_tele_commandscript(), AddSC_ticket_commandscript(), AddSC_titles_commandscript(), AddSC_worldstate_commandscript(), and AddSC_wp_commandscript().
AddSC_account_commandscript()
void AddSC_account_commandscript ()
{
    new account_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_achievement_commandscript()
void AddSC_achievement_commandscript ()
{
    new achievement_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_arena_commandscript()
void AddSC_arena_commandscript ()
{
    new arena_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_autobroadcast_commandscript()
void AddSC_autobroadcast_commandscript ()
{
    new autobroadcast_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_bag_commandscript()
void AddSC_bag_commandscript ()
{
    new bg_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_ban_commandscript()
void AddSC_ban_commandscript ()
{
    new ban_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_bf_commandscript()
void AddSC_bf_commandscript ()
{
    new bf_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_cache_commandscript()
void AddSC_cache_commandscript ()
{
    new cache_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_cast_commandscript()
void AddSC_cast_commandscript ()
{
    new cast_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_character_commandscript()
void AddSC_character_commandscript ()
{
    new character_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_cheat_commandscript()
void AddSC_cheat_commandscript ()
{
    new cheat_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_debug_commandscript()
void AddSC_debug_commandscript ()
{
    new debug_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_deserter_commandscript()
void AddSC_deserter_commandscript ()
{
    new deserter_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_disable_commandscript()
void AddSC_disable_commandscript ()
{
    new disable_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_event_commandscript()
void AddSC_event_commandscript ()
{
    new event_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_gear_commandscript()
void AddSC_gear_commandscript ()
{
    new gear_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_gm_commandscript()
void AddSC_gm_commandscript ()
{
    new gm_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_go_commandscript()
void AddSC_go_commandscript ()
{
    new go_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_gobject_commandscript()
void AddSC_gobject_commandscript ()
{
    new gobject_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_group_commandscript()
void AddSC_group_commandscript ()
{
    new group_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_guild_commandscript()
void AddSC_guild_commandscript ()
{
    new guild_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_honor_commandscript()
void AddSC_honor_commandscript ()
{
    new honor_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_instance_commandscript()
void AddSC_instance_commandscript ()
{
    new instance_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_inventory_commandscript()
void AddSC_inventory_commandscript ()
{
    new inventory_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_item_commandscript()
void AddSC_item_commandscript ()
{
    new item_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_learn_commandscript()
void AddSC_learn_commandscript ()
{
    new learn_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_lfg_commandscript()
void AddSC_lfg_commandscript ()
{
    new lfg_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_list_commandscript()
void AddSC_list_commandscript ()
{
    new list_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_lookup_commandscript()
void AddSC_lookup_commandscript ()
{
    new lookup_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_mail_commandscript()
void AddSC_mail_commandscript ()
{
    new mail_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_message_commandscript()
void AddSC_message_commandscript ()
{
    new message_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_misc_commandscript()
void AddSC_misc_commandscript ()
{
    new misc_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_mmaps_commandscript()
void AddSC_mmaps_commandscript ()
{
    new mmaps_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_modify_commandscript()
void AddSC_modify_commandscript ()
{
    new modify_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_npc_commandscript()
void AddSC_npc_commandscript ()
{
    new npc_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_pet_commandscript()
void AddSC_pet_commandscript ()
{
    new pet_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_player_commandscript()
void AddSC_player_commandscript ()
{
    new player_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_player_settings_commandscript()
void AddSC_player_settings_commandscript ()
{
    new player_settings_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_pool_commandscript()
void AddSC_pool_commandscript ()
{
    new pool_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_pooltools_commandscript()
void AddSC_pooltools_commandscript ()
{
    new pooltools_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_quest_commandscript()
void AddSC_quest_commandscript ()
{
    new quest_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_rbac_commandscript()
void AddSC_rbac_commandscript ()
{
    new rbac_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_reload_commandscript()
void AddSC_reload_commandscript ()
{
    new reload_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_reset_commandscript()
void AddSC_reset_commandscript ()
{
    new reset_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_send_commandscript()
void AddSC_send_commandscript ()
{
    new send_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_server_commandscript()
void AddSC_server_commandscript ()
{
    new server_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_spectator_commandscript()
void AddSC_spectator_commandscript ()
{
    new spectator_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_spellinfo_commandscript()
void AddSC_spellinfo_commandscript ()
{
    new spellinfo_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_tele_commandscript()
void AddSC_tele_commandscript ()
{
    new tele_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_ticket_commandscript()
void AddSC_ticket_commandscript ()
{
    new ticket_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_titles_commandscript()
void AddSC_titles_commandscript ()
{
    new titles_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_worldstate_commandscript()
void AddSC_worldstate_commandscript ()
{
    new worldstate_commandscript();
}
Referenced by AddCommandsScripts().
AddSC_wp_commandscript()
void AddSC_wp_commandscript ()
{
    new wp_commandscript();
}
Referenced by AddCommandsScripts().