AzerothCore: anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest Class Reference
anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
uint32 CountQuestOnCreature (uint32 creatureId, uint32 questId)
Helper: count how many times quest appears on a creature in the quest relation map.
void SimulateSpawn1Object (uint32 questId)
void SimulateReload ()
Protected Attributes
QuestRelations * creatureQuestMap = nullptr
Detailed Description
Member Function Documentation
CountQuestOnCreature()
uint32 anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::CountQuestOnCreature (uint32 creatureId, uint32 questId) inline protected
Helper: count how many times quest appears on a creature in the quest relation map.
    {
        uint32 count = 0;
        auto range = creatureQuestMap->equal_range(creatureId);
        for (auto it = range.first; it != range.second; ++it)
            if (it->second == questId)
                ++count;
        return count;
    }
Referenced by anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_F().
SetUp()
void anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::SetUp () inline override protected
    {
        creatureQuestMap = sObjectMgr->GetCreatureQuestRelationMap();
        // Establish the pool-side mapping: quest -> creature
        // This is what LoadQuestRelationsHelper populates for pooled quests
        sPoolMgr->mQuestCreatureRelation.insert(
            PooledQuestRelation::value_type(TEST_QUEST_ID, TEST_CREATURE_ID));
    }
References sObjectMgr, sPoolMgr, anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_CREATURE_ID, and anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_QUEST_ID.
SimulateReload()
void anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::SimulateReload () inline protected
Simulate what LoadQuestRelationsHelper does on reload:
Clear the creature quest relation map
Clear and repopulate mQuestCreatureRelation Non-pooled quests would be re-added to the creature map, but pooled quests only go into mQuestCreatureRelation.
    {
        // Step 1: map.clear() — line 8589 of ObjectMgr.cpp
        creatureQuestMap->clear();
        // Step 2: poolRelationMap->clear() — line 8604 of ObjectMgr.cpp
        sPoolMgr->mQuestCreatureRelation.clear();
        // Step 3: Repopulate poolRelationMap from DB
        // (In the real code this re-reads creature_queststarter LEFT JOIN pool_quest)
        sPoolMgr->mQuestCreatureRelation.insert(
            PooledQuestRelation::value_type(TEST_QUEST_ID, TEST_CREATURE_ID));
        // NOTE: The real reload handler does NOT call Spawn1Object here.
        // That is the bug.
    }
References sPoolMgr, anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_CREATURE_ID, and anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_QUEST_ID.
Referenced by anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_F().
SimulateSpawn1Object()
void anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::SimulateSpawn1Object (uint32 questId) inline protected
Simulate what Spawn1Object does: copy the active pool quest from mQuestCreatureRelation into the creature quest relation map
    {
        PoolGroup<Quest> poolGroup;
        PoolObject obj(questId, 0.0f);
        poolGroup.Spawn1Object(&obj);
    }
References PoolGroup< T >::Spawn1Object().
Referenced by anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_F().
TearDown()
void anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::TearDown () inline override protected
    {
        // Clean up: remove test entries from both maps
        auto range = sPoolMgr->mQuestCreatureRelation.equal_range(TEST_QUEST_ID);
        sPoolMgr->mQuestCreatureRelation.erase(range.first, range.second);
        // Remove any test entries left in creature quest relations
        auto crRange = creatureQuestMap->equal_range(TEST_CREATURE_ID);
        for (auto it = crRange.first; it != crRange.second; )
        {
            if (it->second == TEST_QUEST_ID)
                it = creatureQuestMap->erase(it);
            else
                ++it;
        }
    }
References sPoolMgr, anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_CREATURE_ID, and anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_QUEST_ID.
Member Data Documentation
creatureQuestMap
QuestRelations* anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::creatureQuestMap = nullptr protected