AzerothCore: npc_rookery_hatcher Struct Reference
npc_rookery_hatcher Struct Reference
Public Member Functions
npc_rookery_hatcher (Creature *creature)
void InitializeAI () override
void JustEngagedWith (Unit *) override
Called for reaction when initially engaged - this happens after JustEnteredCombat.
void UpdateAI (uint32 diff) override
Use to start attacking a target. Called just before JustEngagedWith()
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr, Milliseconds delay=0ms)
Causes the creature to talk/say the text assigned to their entry in the creature_text database table.
void Talk (uint8 id, Milliseconds delay)
WorldObject * GetSummoner () const
Returns the summoner creature/object, if the creature is a temporary summon.
CreatureAI (Creature *creature)
~CreatureAI () override
bool IsEngaged () const
Check if creature is currently engaged in combat.
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual bool IsEscortNPC (bool=true) const
virtual void EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
void JustEnteredCombat (Unit *who) override
Called when the unit enters combat.
virtual void JustStartedThreateningMe (Unit *who)
virtual void JustEngagedWith (Unit *)
Called for reaction when initially engaged - this happens after JustEnteredCombat.
void EngagementStart (Unit *who)
void EngagementOver ()
void JustExitedCombat () override
Called when the unit leaves combat.
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (WorldObject *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SummonedCreatureEvade (Creature *)
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void OnSpellStart (SpellInfo const *)
virtual void OnSpellCast (SpellInfo const *)
virtual void OnSpellFailed (SpellInfo const *)
virtual void OnChannelFinished (SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void PathEndReached (uint32)
virtual void WaypointPathStarted (uint32)
== Waypoints system =============================
virtual void WaypointStarted (uint32, uint32)
virtual void WaypointReached (uint32, uint32)
virtual void WaypointPathEnded (uint32, uint32)
void OnCharmed (bool apply) override
Called when unit is charmed.
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *attacker)
virtual void OwnerAttacked (Unit *target)
void OnOwnerCombatInteraction (Unit *target)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual bool BeforeSpellClick (Unit *)
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
virtual bool CanAlwaysBeDetectable (WorldObject const *)
virtual void PetStopAttack ()
int32 VisualizeBoundary (uint32 duration, Unit *owner=nullptr, bool fill=false, bool checkZ=false) const
virtual bool CheckInRoom ()
CreatureBoundary const * GetBoundary () const
void SetBoundary (CreatureBoundary const *boundary, bool negativeBoundaries=false)
bool IsInBoundary (Position const *who=nullptr) const
virtual void CalculateThreat (Unit *, float &, SpellInfo const *)
virtual bool OnTeleportUnreacheablePlayer (Player *)
virtual void OnAuraRemove (AuraApplication *, AuraRemoveMode)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
Use to start attacking a target. Called just before JustEngagedWith()
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
Called when unit is charmed.
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid const &, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, bool withTank=true, int32 aura=0)
Select the best (up to) <num> targets (in <targetType> order) from the threat list that fulfill the following:
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectTargetMethod targetType, uint32 position, PREDICATE const &predicate)
virtual void JustEnteredCombat (Unit *)
Called when the unit enters combat.
virtual void JustExitedCombat ()
Called when the unit leaves combat.
virtual void EvadeTimerExpired ()
Called when evade timer expires (target unreachable for too long)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
Called at any Damage from any attacker (before damage apply)
virtual void HealReceived (Unit *, uint32 &)
Called when the creature receives heal.
virtual void OnPowerUpdate (Powers, int32, int32, uint32)
Called when the creature power updates.
virtual void HealDone (Unit *, uint32 &)
Called when the unit heals.
virtual void OnCalculateMeleeDamageReceived (uint32 &, Unit *)
Called during damage calculations.
virtual void OnCalculateSpellDamageReceived (int32 &, Unit *)
virtual void OnCalculatePeriodicTickReceived (uint32 &, Unit *)
Called during calculation when receiving periodic healing or damage (DoT or HoT)
void AttackStartCaster (Unit *victim, float dist)
SpellCastResult DoAddAuraToAllHostilePlayers (uint32 spellid)
SpellCastResult DoCast (uint32 spellId)
SpellCastResult DoCast (Unit *victim, uint32 spellId, bool triggered=false)
SpellCastResult DoCastSelf (uint32 spellId, bool triggered=false)
SpellCastResult DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
To specify the caster as target if the spell is self-cast.
SpellCastResult DoCastVictim (uint32 spellId, bool triggered=false)
SpellCastResult DoCastAOE (uint32 spellId, bool triggered=false)
SpellCastResult DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false, bool withTank=true)
Cast the spell on a random unit from the threat list.
SpellCastResult DoCastMaxThreat (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
Cast spell on the top threat target, which may not be the current victim.
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
void DoSpellAttackToRandomTargetIfReady (uint32 spell, uint32 threatTablePosition=0, float dist=0.f, bool playerOnly=true)
virtual void SummonMovementInform (Creature *, uint32, uint32)
Called when a summon reaches a waypoint or point movement finished.
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
virtual std::string GetDebugInfo () const
Public Attributes
EventMap events
GameObject * targetEgg
Position targetPosition
Additional Inherited Members
Public Types inherited from CreatureAI
enum EvadeReason {
EVADE_REASON_NO_HOSTILES ,
EVADE_REASON_BOUNDARY ,
EVADE_REASON_SEQUENCE_BREAK ,
EVADE_REASON_NO_PATH ,
EVADE_REASON_OTHER
}
Static Public Member Functions inherited from CreatureAI
static bool IsInBounds (CreatureBoundary const &boundary, Position const *who)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode (EvadeReason why=EVADE_REASON_OTHER)
Protected Attributes inherited from CreatureAI
Creature *const me
EventMap events
TaskScheduler scheduler
CreatureBoundary const * _boundary
bool _negateBoundary
bool _isEngaged
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Constructor & Destructor Documentation
npc_rookery_hatcher()
npc_rookery_hatcher::npc_rookery_hatcher (Creature * creature) inline
: CreatureAI(creature) {}
Member Function Documentation
InitializeAI()
void npc_rookery_hatcher::InitializeAI () inline override virtual
Reimplemented from UnitAI.
    {
        CreatureAI::InitializeAI();
        DoZoneInCombat(nullptr, 100.0f);
        targetEgg = nullptr;
    }
References CreatureAI::DoZoneInCombat(), UnitAI::InitializeAI(), and targetEgg.
JustEngagedWith()
void npc_rookery_hatcher::JustEngagedWith (Unit *) inline override virtual
Called for reaction when initially engaged - this happens after JustEnteredCombat.
Reimplemented from CreatureAI.
    {
        events.ScheduleEvent(SPELL_HATCH_EGG, 1s);
    }
References SPELL_HATCH_EGG.
UpdateAI()
void npc_rookery_hatcher::UpdateAI (uint32) inline override virtual
Use to start attacking a target. Called just before JustEngagedWith()
Implements UnitAI.
    {
        std::list<GameObject*> nearbyEggs;
        float                  tempDist = 20;
        float                  minDist  = 25;
        std::list<Creature*>   nearbyWhelps;
        if (!UpdateVictim())
            return;
        GetCreatureListWithEntryInGrid(nearbyWhelps, me, NPC_ROOKERY_WHELP, RANGE_WHELP_CALL_HELP);
        for (auto const& whelp : nearbyWhelps)
        {
            if (!whelp->IsInCombat())
            {
                whelp->SetInCombatWith(me->GetVictim());
                whelp->AI()->AttackStart(me->GetVictim());
            }
        }
        if (me->HasUnitState(UNIT_STATE_CASTING))
            return;
        events.Update(diff);
        while (uint32 eventId = events.ExecuteEvent())
        {
            switch (eventId)
            {
                case SPELL_HATCH_EGG:
                    if (!targetEgg) // no target, try to find one
                    {
                        minDist = 50;
                        tempDist = 50;
                        me->GetGameObjectListWithEntryInGrid(nearbyEggs, GO_ROOKERY_EGG, 40);
                        for (auto const& egg : nearbyEggs)
{
                            if (egg->isSpawned() && egg->getLootState() == GO_READY)
{
                                tempDist = me->GetDistance2d(egg);
                                if (tempDist < minDist)
{
                                    minDist   = tempDist;
                                    targetEgg = egg;
                                }
                            }
                        }
                    }
                    if (targetEgg) //have a target, go to it and cast it
                        me->GetMotionMaster()->MovePoint(0, targetEgg->GetPosition());
                    break;
                default:
                    break;
            }
        }
        // cast takes 1.5second, during which we don't have a target
        if (targetEgg && targetEgg->getLootState() == GO_READY && me->GetDistance2d(targetEgg) < RANGE_SPELL_HATCH_EGG)
        {
            me->StopMovingOnCurrentPos();
            me->SetFacingToObject(targetEgg);
            targetPosition = me->GetPosition();
            DoCast(SPELL_HATCH_EGG);
            targetEgg = nullptr;
            events.ScheduleEvent(SPELL_HATCH_EGG, 6s, 8s);
        }
        else if (!me->HasUnitState(UNIT_STATE_CASTING)  && !targetEgg)
        {
            if (Unit* victim = me->GetVictim())
                AttackStart(victim);
            if (me->GetDistance2d(me->GetVictim()) > me->GetMeleeReach())
                me->GetMotionMaster()->MovePoint(0, me->GetVictim()->GetPosition()); // a bit hacky, but needed to start moving once we've summoned an egg
        }
        DoMeleeAttackIfReady();
    }
References UnitAI::AttackStart(), UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), GetCreatureListWithEntryInGrid(), WorldObject::GetDistance2d(), WorldObject::GetGameObjectListWithEntryInGrid(), GameObject::getLootState(), Unit::GetMeleeReach(), Unit::GetMotionMaster(), Position::GetPosition(), Unit::GetVictim(), GO_READY, GO_ROOKERY_EGG, Unit::HasUnitState(), CreatureAI::me, MotionMaster::MovePoint(), NPC_ROOKERY_WHELP, RANGE_SPELL_HATCH_EGG, RANGE_WHELP_CALL_HELP, Unit::SetFacingToObject(), SPELL_HATCH_EGG, Unit::StopMovingOnCurrentPos(), targetEgg, targetPosition, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap npc_rookery_hatcher::events
targetEgg
GameObject* npc_rookery_hatcher::targetEgg
Referenced by InitializeAI(), and UpdateAI().
targetPosition
Position npc_rookery_hatcher::targetPosition
Referenced by UpdateAI().