AzerothCore: Acore::WorldObjectSpellTrajTargetCheck Struct Reference
Acore::WorldObjectSpellTrajTargetCheck Struct Reference
#include "Spell.h"
Public Member Functions
WorldObjectSpellTrajTargetCheck (float range, Position const *position, Unit *caster, SpellInfo const *spellInfo, SpellTargetCheckTypes selectionType, ConditionList *condList)
bool operator() (WorldObject *target)
Public Member Functions inherited from Acore::WorldObjectSpellAreaTargetCheck
WorldObjectSpellAreaTargetCheck (float range, Position const *position, Unit *caster, Unit *referer, SpellInfo const *spellInfo, SpellTargetCheckTypes selectionType, ConditionList *condList)
bool operator() (WorldObject *target)
Public Member Functions inherited from Acore::WorldObjectSpellTargetCheck
WorldObjectSpellTargetCheck (Unit *caster, Unit *referer, SpellInfo const *spellInfo, SpellTargetCheckTypes selectionType, ConditionList *condList)
~WorldObjectSpellTargetCheck ()
bool operator() (WorldObject *target)
Additional Inherited Members
Public Attributes inherited from Acore::WorldObjectSpellAreaTargetCheck
float _range
Position const * _position
Public Attributes inherited from Acore::WorldObjectSpellTargetCheck
Unit * _caster
Unit * _referer
SpellInfo const * _spellInfo
SpellTargetCheckTypes _targetSelectionType
ConditionSourceInfo * _condSrcInfo
ConditionList * _condList
Detailed Description
Constructor & Destructor Documentation
WorldObjectSpellTrajTargetCheck()
Acore::WorldObjectSpellTrajTargetCheck::WorldObjectSpellTrajTargetCheck (float range, Position const * position, Unit * caster, SpellInfo const * spellInfo, SpellTargetCheckTypes selectionType, ConditionList * condList)
        : WorldObjectSpellAreaTargetCheck(range, position, caster, caster, spellInfo, selectionType, condList)
    {
    }
Member Function Documentation
operator()()
bool Acore::WorldObjectSpellTrajTargetCheck::operator() (WorldObject * target)
    {
        // return all targets on missile trajectory (0 - size of a missile)
        if (!_caster->HasInLine(target, target->GetCombatReach(), TRAJECTORY_MISSILE_SIZE))
            return false;
        if (target->GetExactDist2d(_position) > _range)
            return false;
        return WorldObjectSpellTargetCheck::operator ()(target);
    }
References Acore::WorldObjectSpellTargetCheck::_caster, Acore::WorldObjectSpellAreaTargetCheck::_position, Acore::WorldObjectSpellAreaTargetCheck::_range, WorldObject::GetCombatReach(), Position::GetExactDist2d(), Position::HasInLine(), Acore::WorldObjectSpellTargetCheck::operator()(), and TRAJECTORY_MISSILE_SIZE.