AzerothCore: spell_dru_t9_feral_relic Class Reference
spell_dru_t9_feral_relic Class Reference
Private Member Functions
PrepareAuraScript (spell_dru_t9_feral_relic)
bool Validate (SpellInfo const *) override
bool CheckProc (ProcEventInfo &eventInfo)
void HandleProc (AuraEffect const *aurEff, ProcEventInfo &eventInfo)
void Register () override
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual void Register ()=0
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< CheckEffectProcHandler > DoCheckEffectProc
HookList< AfterCheckProcHandler > DoAfterCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
virtual bool _Validate (SpellInfo const *entry)
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Member Function Documentation
CheckProc()
bool spell_dru_t9_feral_relic::CheckProc (ProcEventInfo & eventInfo) inline private
    {
        Unit* target = eventInfo.GetActor();
        switch (target->GetShapeshiftForm())
        {
            case FORM_BEAR:
            case FORM_DIREBEAR:
            case FORM_CAT:
                return true;
            default:
                break;
        }
        return false;
    }
References FORM_BEAR, FORM_CAT, FORM_DIREBEAR, ProcEventInfo::GetActor(), and Unit::GetShapeshiftForm().
Referenced by Register().
HandleProc()
void spell_dru_t9_feral_relic::HandleProc (AuraEffect const * aurEff, ProcEventInfo & eventInfo) inline private
    {
        PreventDefaultAction();
        uint32 triggerspell = 0;
        Unit* target = eventInfo.GetActor();
        switch (target->GetShapeshiftForm())
        {
            case FORM_BEAR:
            case FORM_DIREBEAR:
                triggerspell = SPELL_DRUID_T9_FERAL_RELIC_BEAR;
                break;
            case FORM_CAT:
                triggerspell = SPELL_DRUID_T9_FERAL_RELIC_CAT;
                break;
            default:
                return;
        }
        target->CastSpell(target, triggerspell, true, nullptr, aurEff);
    }
References Unit::CastSpell(), FORM_BEAR, FORM_CAT, FORM_DIREBEAR, ProcEventInfo::GetActor(), Unit::GetShapeshiftForm(), AuraScript::PreventDefaultAction(), SPELL_DRUID_T9_FERAL_RELIC_BEAR, and SPELL_DRUID_T9_FERAL_RELIC_CAT.
Referenced by Register().
PrepareAuraScript()
spell_dru_t9_feral_relic::PrepareAuraScript (spell_dru_t9_feral_relic) private
Register()
void spell_dru_t9_feral_relic::Register () inline override private virtual
Implements _SpellScript.
    {
        DoCheckProc += AuraCheckProcFn(spell_dru_t9_feral_relic::CheckProc);
        OnEffectProc += AuraEffectProcFn(spell_dru_t9_feral_relic::HandleProc, EFFECT_0, SPELL_AURA_PROC_TRIGGER_SPELL);
    }
References AuraCheckProcFn, AuraEffectProcFn, CheckProc(), AuraScript::DoCheckProc, EFFECT_0, HandleProc(), AuraScript::OnEffectProc, and SPELL_AURA_PROC_TRIGGER_SPELL.
Validate()
bool spell_dru_t9_feral_relic::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
    {
        return ValidateSpellInfo({
            SPELL_DRUID_T9_FERAL_RELIC_BEAR,
            SPELL_DRUID_T9_FERAL_RELIC_CAT
        });
    }
References SPELL_DRUID_T9_FERAL_RELIC_BEAR, SPELL_DRUID_T9_FERAL_RELIC_CAT, and _SpellScript::ValidateSpellInfo().