AzerothCore: anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest Class Reference
anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
void ExecuteCommand (std::string_view text)
Static Protected Member Functions
static void EnsureScriptRegistriesInitialized ()
Protected Attributes
IWorld * originalWorld = nullptr
NiceMock< WorldMock > * worldMock = nullptr
WorldSession * session = nullptr
TestPlayer * player = nullptr
Private Member Functions
void ApplyGmVisibleState (bool makeVisible)
Detailed Description
Member Function Documentation
ApplyGmVisibleState()
void anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest::ApplyGmVisibleState (bool makeVisible) inline private
    {
        constexpr uint32 VISUAL_AURA = 37800;
        if (makeVisible)
        {
            player->RemoveAurasDueToSpell(VISUAL_AURA);
            player->SetGMVisible(true);
        }
        else
        {
            player->AddAura(VISUAL_AURA, player);
            player->SetGMVisible(false);
        }
        player->UpdateObjectVisibility();
    }
References Unit::AddAura(), Unit::RemoveAurasDueToSpell(), Player::SetGMVisible(), and anonymous_namespace{GmVisibleCommandTest.cpp}::TestPlayer::UpdateObjectVisibility().
EnsureScriptRegistriesInitialized()
static void anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest::EnsureScriptRegistriesInitialized () inline static protected
    {
        static bool initialized = false;
        if (!initialized)
        {
            ScriptRegistry<MiscScript>::InitEnabledHooksIfNeeded(MISCHOOK_END);
            ScriptRegistry<WorldObjectScript>::InitEnabledHooksIfNeeded(WORLDOBJECTHOOK_END);
            ScriptRegistry<UnitScript>::InitEnabledHooksIfNeeded(UNITHOOK_END);
            ScriptRegistry<PlayerScript>::InitEnabledHooksIfNeeded(PLAYERHOOK_END);
            ScriptRegistry<CommandSC>::InitEnabledHooksIfNeeded(ALLCOMMANDHOOK_END);
            initialized = true;
        }
    }
References ALLCOMMANDHOOK_END, ScriptRegistry< TScript >::InitEnabledHooksIfNeeded(), MISCHOOK_END, PLAYERHOOK_END, UNITHOOK_END, and WORLDOBJECTHOOK_END.
ExecuteCommand()
void anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest::ExecuteCommand (std::string_view text) inline protected
    {
        if (text == ".gm visible off")
        {
            ApplyGmVisibleState(false);
        }
        else if (text == ".gm visible on")
        {
            ApplyGmVisibleState(true);
        }
        else
        {
            FAIL() << "Unsupported test command: " << text;
        }
    }
References FAIL.
Referenced by anonymous_namespace{GmVisibleCommandTest.cpp}::TEST_F().
SetUp()
void anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest::SetUp () inline override protected
    {
        EnsureScriptRegistriesInitialized();
        TestVisibilityScript::EnsureRegistered();
        originalWorld = sWorld.release();
        worldMock = new NiceMock<WorldMock>();
        sWorld.reset(worldMock);
        static std::string emptyString;
        ON_CALL(*worldMock, GetDataPath()).WillByDefault(ReturnRef(emptyString));
        ON_CALL(*worldMock, GetRealmName()).WillByDefault(ReturnRef(emptyString));
        ON_CALL(*worldMock, GetDefaultDbcLocale()).WillByDefault(Return(LOCALE_enUS));
        ON_CALL(*worldMock, getRate(_)).WillByDefault(Return(1.0f));
        ON_CALL(*worldMock, getBoolConfig(_)).WillByDefault(Return(false));
        ON_CALL(*worldMock, getIntConfig(_)).WillByDefault(Return(0));
        ON_CALL(*worldMock, getFloatConfig(_)).WillByDefault(Return(0.0f));
        ON_CALL(*worldMock, GetPlayerSecurityLimit()).WillByDefault(Return(SEC_PLAYER));
        session = new WorldSession(1, "gm", 0, nullptr, SEC_GAMEMASTER, EXPANSION_WRATH_OF_THE_LICH_KING,
            0, LOCALE_enUS, 0, false, false, 0);
        player = new TestPlayer(session);
        player->ForceInitValues();
        session->SetPlayer(player);
        player->SetSession(session);
        TestVisibilityScript::Reset();
    }
References EXPANSION_WRATH_OF_THE_LICH_KING, LOCALE_enUS, SEC_GAMEMASTER, SEC_PLAYER, and sWorld.
TearDown()
void anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest::TearDown () inline override protected
    {
        // Intentional leaks of session/player to avoid database access in destructors.
        IWorld* currentWorld = sWorld.release();
        delete currentWorld;
        worldMock = nullptr;
        sWorld.reset(originalWorld);
        originalWorld = nullptr;
        session = nullptr;
        player = nullptr;
    }
References sWorld.
Member Data Documentation
originalWorld
IWorld* anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest::originalWorld = nullptr protected
player
TestPlayer* anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest::player = nullptr protected
session
WorldSession* anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest::session = nullptr protected
worldMock
NiceMock<WorldMock>* anonymous_namespace{GmVisibleCommandTest.cpp}::GmVisibleCommandTest::worldMock = nullptr protected