AzerothCore: anonymous_namespace{ThreatManagerTest.cpp} Namespace Reference
anonymous_namespace{ThreatManagerTest.cpp} Namespace Reference
Classes
class ThreatManagerIntegrationTest
Functions
TEST_F (ThreatManagerIntegrationTest, CanHaveThreatList_NullUnit_ReturnsFalse)
TEST_F (ThreatManagerIntegrationTest, CanHaveThreatList_InitializedCreature_ReturnsTrue)
TEST_F (ThreatManagerIntegrationTest, AddThreat_CreatesThreatEntry)
TEST_F (ThreatManagerIntegrationTest, AddThreat_ImpliesCombat)
TEST_F (ThreatManagerIntegrationTest, ScaleThreat_DoublesAmount)
TEST_F (ThreatManagerIntegrationTest, ScaleThreat_ZeroFactor_ZerosThreat)
TEST_F (ThreatManagerIntegrationTest, ClearThreat_RemovesEntry)
TEST_F (ThreatManagerIntegrationTest, ClearAllThreat_EmptiesList)
TEST_F (ThreatManagerIntegrationTest, GetCurrentVictim_ReturnsHighestThreat)
TEST_F (ThreatManagerIntegrationTest, FixateTarget_OverridesSelection)
TEST_F (ThreatManagerIntegrationTest, ResetAllThreat_ZerosAllEntries)
TEST_F (ThreatManagerIntegrationTest, CompareReferences_OnlineStatePrecedence)
TEST_F (ThreatManagerIntegrationTest, ThreatConstants)
TEST_F (ThreatManagerIntegrationTest, GetThreatListPlayerCount_CreatureOnlyList_ReturnsZero)
TEST_F (ThreatManagerIntegrationTest, ResetAllMyThreatOnOthers_ZerosThreatOnAllCreatures)
TEST_F (ThreatManagerIntegrationTest, ResetAllMyThreatOnOthers_NoEntries_DoesNothing)
TEST_F (ThreatManagerIntegrationTest, SendThreatList_HighestThreatUpdate_Path)
TEST_F (ThreatManagerIntegrationTest, SendThreatList_ThreatUpdate_Path)
TEST_F (ThreatManagerIntegrationTest, TauntState_OverridesHigherThreat)
TEST_F (ThreatManagerIntegrationTest, TauntState_DoesNotClobberFixate)
TEST_F (ThreatManagerIntegrationTest, Detaunt_LowersPriority)
TEST_F (ThreatManagerIntegrationTest, CanHaveThreatList_ConsistentBetweenUnitAndThreatMgr)
TEST_F (ThreatManagerIntegrationTest, CanHaveThreatList_DeadCreature_ReturnsFalse)
TEST_F (ThreatManagerIntegrationTest, MatchUnitThreatToHighestThreat_SetsToHighest)
TEST_F (ThreatManagerIntegrationTest, MatchUnitThreatToHighestThreat_AlreadyHighest_NoChange)
TEST_F (ThreatManagerIntegrationTest, RedirectThreat_RegisterAndUnregister_PerSpell)
TEST_F (ThreatManagerIntegrationTest, RedirectThreat_UnregisterOneSpell_KeepsOther)
TEST_F (ThreatManagerIntegrationTest, RedirectThreat_ResetAllRedirects_ClearsAll)
TEST_F (ThreatManagerIntegrationTest, IsEngagedBy_UsesThreatListForCreatures)
TEST_F (ThreatManagerIntegrationTest, IsEngagedBy_CombatWithoutThreat_NotEngaged)
TEST_F (ThreatManagerIntegrationTest, SpellSchoolModifiers_DefaultIsUnmodified)
TEST_F (ThreatManagerIntegrationTest, PhaseChange_PutsThreatsOffline)
TEST_F (ThreatManagerIntegrationTest, RedirectThreat_AddThreat_SplitsBetweenTargetAndRedirect)
TEST_F (ThreatManagerIntegrationTest, RedirectThreat_FullRedirect_AllThreatGoesToTarget)
TEST_F (ThreatManagerIntegrationTest, RedirectThreat_TwoSpells_BothRedirect)
TEST_F (ThreatManagerIntegrationTest, RedirectThreat_NegativeAmount_NoRedirect)
TEST_F (ThreatManagerIntegrationTest, RedirectThreat_AfterUnregister_NoMoreRedirect)
TEST_F (ThreatManagerIntegrationTest, RedirectThreat_UnregisterPerSpellPerVictim)
TEST_F (ThreatManagerIntegrationTest, ForwardThreat_SingleCreature_AllThreatToAssistant)
TEST_F (ThreatManagerIntegrationTest, ForwardThreat_MultipleCreatures_SplitsEvenly)
TEST_F (ThreatManagerIntegrationTest, ForwardThreat_CCTarget_GetsZeroThreat)
TEST_F (ThreatManagerIntegrationTest, ForwardThreat_NoThreatenedBy_DoesNothing)
TEST_F (ThreatManagerIntegrationTest, ForwardThreat_ZeroAmount_StillEntersCombat)
TEST_F (ThreatManagerIntegrationTest, EvaluateSuppressed_NoRefs_DoesNotCrash)
TEST_F (ThreatManagerIntegrationTest, EvaluateSuppressed_OnlineRefs_RemainOnline)
TEST_F (ThreatManagerIntegrationTest, EvaluateSuppressed_DamageImmunity_SetsSuppressed)
TEST_F (ThreatManagerIntegrationTest, EvaluateSuppressed_CanExpire_RestoresOnline)
TEST_F (ThreatManagerIntegrationTest, EvaluateSuppressed_TauntedVictim_NeverSuppressed)
TEST_F (ThreatManagerIntegrationTest, EvaluateSuppressed_MultipleRefs_EachEvaluatedIndependently)
TEST_F (ThreatManagerIntegrationTest, ReselectVictim_Below110Percent_KeepsOldVictim)
TEST_F (ThreatManagerIntegrationTest, ReselectVictim_MeleeAt110Percent_Switches)
TEST_F (ThreatManagerIntegrationTest, ReselectVictim_MeleeAt130Percent_AlsoSwitches)
TEST_F (ThreatManagerIntegrationTest, ReselectVictim_MeleeThirdTarget_AboveThreshold_Switches)
TEST_F (ThreatManagerIntegrationTest, ReselectVictim_NoOldVictim_PicksHighest)
TEST_F (ThreatManagerIntegrationTest, ReselectVictim_EqualThreat_KeepsCurrentVictim)
TEST_F (ThreatManagerIntegrationTest, Update_TimerDrivenReselection)
TEST_F (ThreatManagerIntegrationTest, Update_ZeroDiff_DoesNotCrash)
TEST_F (ThreatManagerIntegrationTest, Update_EmptyThreatList_DoesNotCrash)
TEST_F (ThreatManagerIntegrationTest, ModifyThreatByPercent_Increase)
TEST_F (ThreatManagerIntegrationTest, ModifyThreatByPercent_Decrease)
TEST_F (ThreatManagerIntegrationTest, ModifyThreatByPercent_Minus100_ZerosThreat)
TEST_F (ThreatManagerIntegrationTest, ModifyThreatByPercent_ZeroPercent_NoChange)
TEST_F (ThreatManagerIntegrationTest, ModifyThreatByPercent_Plus100_Doubles)
TEST_F (ThreatManagerIntegrationTest, GetThreat_NonexistentTarget_ReturnsZero)
TEST_F (ThreatManagerIntegrationTest, GetThreat_OfflineTarget_ExcludedByDefault)
TEST_F (ThreatManagerIntegrationTest, IsThreatListEmpty_EmptyList_ReturnsTrue)
TEST_F (ThreatManagerIntegrationTest, IsThreatListEmpty_WithEntries_ReturnsFalse)
TEST_F (ThreatManagerIntegrationTest, IsThreatListEmpty_AllOffline_TrueWithoutOfflineFlag)
TEST_F (ThreatManagerIntegrationTest, IsThreatenedBy_OfflineTarget_Variants)
TEST_F (ThreatManagerIntegrationTest, IsThreateningAnyone_NoEntries_ReturnsFalse)
TEST_F (ThreatManagerIntegrationTest, IsThreateningAnyone_WithEntries_ReturnsTrue)
TEST_F (ThreatManagerIntegrationTest, IsThreateningAnyone_AllOffline_FalseWithoutFlag)
TEST_F (ThreatManagerIntegrationTest, IsThreateningTo_SpecificTarget)
TEST_F (ThreatManagerIntegrationTest, IsThreateningTo_ObjectGuidVariant)
TEST_F (ThreatManagerIntegrationTest, RemoveMeFromThreatLists_RemovesFromAllLists)
TEST_F (ThreatManagerIntegrationTest, RemoveMeFromThreatLists_NoEntries_DoesNotCrash)
TEST_F (ThreatManagerIntegrationTest, GetAnyTarget_EmptyList_ReturnsNull)
TEST_F (ThreatManagerIntegrationTest, GetAnyTarget_WithEntries_ReturnsNonNull)
TEST_F (ThreatManagerIntegrationTest, GetAnyTarget_AllOffline_ReturnsNull)
TEST_F (ThreatManagerIntegrationTest, GetLastVictim_NoVictim_ReturnsNull)
TEST_F (ThreatManagerIntegrationTest, GetLastVictim_WithVictim_ReturnsCached)
TEST_F (ThreatManagerIntegrationTest, GetLastVictim_OfflineVictim_ReturnsNull)
TEST_F (ThreatManagerIntegrationTest, GetSortedThreatList_ReturnsSortedByThreat)
TEST_F (ThreatManagerIntegrationTest, GetUnsortedThreatList_ReturnsAllEntries)
TEST_F (ThreatManagerIntegrationTest, GetModifiableThreatList_ReturnsCopy)
TEST_F (ThreatManagerIntegrationTest, MultipleTaunts_LastTauntWins)
TEST_F (ThreatManagerIntegrationTest, AddThreat_NegativeAmount_ReducesThreat)
TEST_F (ThreatManagerIntegrationTest, AddThreat_NegativeBeyondZero_ClampsToZero)
TEST_F (ThreatManagerIntegrationTest, AddThreat_DeadTarget_NoCombatOrThreat)
TEST_F (ThreatManagerIntegrationTest, AddThreat_DifferentPhaseTarget_NoCombatOrThreat)
TEST_F (ThreatManagerIntegrationTest, GetFixateTarget_NoFixate_ReturnsNull)
TEST_F (ThreatManagerIntegrationTest, GetFixateTarget_WithFixate_ReturnsTarget)
TEST_F (ThreatManagerIntegrationTest, ThreatReference_GetOwnerAndVictim)
TEST_F (ThreatManagerIntegrationTest, ThreatReference_ScaleThreat_Directly)
TEST_F (ThreatManagerIntegrationTest, MatchUnitThreatToHighestThreat_HighestIsTaunted_UsesNextEntry)
TEST_F (ThreatManagerIntegrationTest, MatchUnitThreatToHighestThreat_TauntedIsAlsoHighest_UsesTauntedThreat)
TEST_F (ThreatManagerIntegrationTest, AddThreat_SuppressedRef_UnsuppressesOnNewThreat)
TEST_F (ThreatManagerIntegrationTest, AddThreat_SuppressedRef_StillSuppressed_NoTransition)
TEST_F (ThreatManagerIntegrationTest, RedirectThreat_TotalExceeds100_CappedAt100)
TEST_F (ThreatManagerIntegrationTest, RedirectThreat_Exactly100Percent_AllRedirected)
TEST_F (ThreatManagerIntegrationTest, ThreatReference_ScaleThreat_Factor1_NoOp)
TEST_F (ThreatManagerIntegrationTest, ThreatReference_AddThreat_ZeroAmount_NoOp)
TEST_F (ThreatManagerIntegrationTest, ThreatReference_ClearThreat_DirectCall_RemovesEntry)
TEST_F (ThreatManagerIntegrationTest, FixateTarget_NotOnThreatList_ClearsFixate)
TEST_F (ThreatManagerIntegrationTest, FixateTarget_NotOnThreatList_ClearsExistingFixate)
TEST_F (ThreatManagerIntegrationTest, UpdateVictim_ImmediateReselectAfterTauntState)
TEST_F (ThreatManagerIntegrationTest, UpdateVictim_Idempotent_MultipleCalls)
TEST_F (ThreatManagerIntegrationTest, UpdateVictim_RapidTauntToggle_NoCrash)
TEST_F (ThreatManagerIntegrationTest, UpdateVictim_WithConcurrentThreatChanges_NoCrash)
TEST_F (ThreatManagerIntegrationTest, UpdateVictim_MultipleTaunters_HighestStateWins)
TEST_F (ThreatManagerIntegrationTest, UpdateVictim_FixateStillTakesPrecedence)
TEST_F (ThreatManagerIntegrationTest, TauntUpdate_EmptyThreatList_NoCrash)
TEST_F (ThreatManagerIntegrationTest, TauntUpdate_RapidCalls_NoCrash)
Function Documentation
TEST_F() [1/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , AddThreat_CreatesThreatEntry)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 100.0f);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 1u);
}
TEST_F() [2/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , AddThreat_DeadTarget_NoCombatOrThreat)
{
    _creatureB->SetAlive(false);
    // Dead targets should fail CanBeginCombat and thus not get threat
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasCombat());
}
TEST_F() [3/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , AddThreat_DifferentPhaseTarget_NoCombatOrThreat)
{
    _creatureB->SetPhase(2);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasCombat());
}
TEST_F() [4/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , AddThreat_ImpliesCombat)
{
    EXPECT_FALSE(_creatureA->TestGetCombatMgr().HasCombat());
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 50.0f);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().HasCombat());
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
}
TEST_F() [5/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , AddThreat_NegativeAmount_ReducesThreat)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, -30.0f);
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 70.0f);
}
TEST_F() [6/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , AddThreat_NegativeBeyondZero_ClampsToZero)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 50.0f);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, -100.0f);
    // ThreatReference::GetThreat clamps to 0 via max(baseAmount + tempMod, 0)
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 0.0f);
}
TEST_F() [7/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , AddThreat_SuppressedRef_StillSuppressed_NoTransition)
{
    // A has B on threat list
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // Make B immune → suppress
    _creatureB->ApplySpellImmune(1, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, true);
    _creatureB->TestGetThreatMgr().EvaluateSuppressed();
    // Add more threat while B is still immune — should stay SUPPRESSED
    // and threat should NOT be applied (AddThreat only adds to ONLINE refs)
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 50.0f, nullptr, true);
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
        if (ref->GetVictim() == _creatureB)
            EXPECT_TRUE(ref->IsSuppressed());
    // Threat should be unchanged (AddThreat skips non-online refs)
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 100.0f);
    _creatureB->ApplySpellImmune(1, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, false);
}
References IMMUNITY_DAMAGE, and SPELL_SCHOOL_MASK_NORMAL.
TEST_F() [8/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , AddThreat_SuppressedRef_UnsuppressesOnNewThreat)
{
    // A has B on threat list
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // Make B immune → suppress B's ref on A's list
    _creatureB->ApplySpellImmune(1, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, true);
    _creatureB->TestGetThreatMgr().EvaluateSuppressed();
    // Verify B is SUPPRESSED
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
        if (ref->GetVictim() == _creatureB)
            EXPECT_TRUE(ref->IsSuppressed());
    // Remove immunity (but do NOT call EvaluateSuppressed)
    _creatureB->ApplySpellImmune(1, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, false);
    // Add more threat — the AddThreat path should detect that the ref
    // no longer ShouldBeSuppressed() and transition it to ONLINE
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 50.0f, nullptr, true);
    // Verify B is now ONLINE and threat was applied
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
    {
        if (ref->GetVictim() == _creatureB)
        {
            EXPECT_TRUE(ref->IsOnline());
            EXPECT_FALSE(ref->IsSuppressed());
        }
    }
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 150.0f);
}
References IMMUNITY_DAMAGE, and SPELL_SCHOOL_MASK_NORMAL.
TEST_F() [9/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , CanHaveThreatList_ConsistentBetweenUnitAndThreatMgr)
{
    // Both should agree for a valid, alive creature
    EXPECT_TRUE(_creatureA->CanHaveThreatList());
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().CanHaveThreatList());
    EXPECT_TRUE(_creatureB->CanHaveThreatList());
    EXPECT_TRUE(_creatureB->TestGetThreatMgr().CanHaveThreatList());
}
TEST_F() [10/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , CanHaveThreatList_DeadCreature_ReturnsFalse)
{
    _creatureA->SetAlive(false);
    // Unit::CanHaveThreatList checks alive state on top of ThreatMgr
    EXPECT_FALSE(_creatureA->CanHaveThreatList());
    // ThreatManager cached value doesn't track alive state
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().CanHaveThreatList());
    // But skipAliveCheck should bypass the alive check
    EXPECT_TRUE(_creatureA->CanHaveThreatList(true));
}
TEST_F() [11/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , CanHaveThreatList_InitializedCreature_ReturnsTrue)
{
    EXPECT_TRUE(ThreatManager::CanHaveThreatList(_creatureA));
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().CanHaveThreatList());
}
References ThreatManager::CanHaveThreatList().
TEST_F() [12/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , CanHaveThreatList_NullUnit_ReturnsFalse)
{
    EXPECT_FALSE(ThreatManager::CanHaveThreatList(nullptr));
}
References ThreatManager::CanHaveThreatList().
TEST_F() [13/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ClearAllThreat_EmptiesList)
{
    // Add a third creature for multi-target test
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 200.0f);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 2u);
    _creatureA->TestGetThreatMgr().ClearAllThreat();
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 0u);
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatListEmpty());
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [14/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ClearThreat_RemovesEntry)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 1u);
    _creatureA->TestGetThreatMgr().ClearThreat(_creatureB);
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 0u);
}
TEST_F() [15/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , CompareReferences_OnlineStatePrecedence)
{
    // OnlineState enum ordering: ONLINE > SUPPRESSED > OFFLINE
    EXPECT_GT(ThreatReference::ONLINE_STATE_ONLINE,
              ThreatReference::ONLINE_STATE_SUPPRESSED);
    EXPECT_GT(ThreatReference::ONLINE_STATE_SUPPRESSED,
              ThreatReference::ONLINE_STATE_OFFLINE);
}
References ThreatReference::ONLINE_STATE_OFFLINE, ThreatReference::ONLINE_STATE_ONLINE, and ThreatReference::ONLINE_STATE_SUPPRESSED.
TEST_F() [16/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , Detaunt_LowersPriority)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // B and C have same threat
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 100.0f);
    // Detaunt B — C should be selected
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_DETAUNT);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureC);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), ThreatReference::TAUNT_STATE_DETAUNT, and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [17/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , EvaluateSuppressed_CanExpire_RestoresOnline)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // Apply immunity to suppress
    _creatureB->ApplySpellImmune(1, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, true);
    _creatureB->TestGetThreatMgr().EvaluateSuppressed();
    // Verify suppressed
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
        if (ref->GetVictim() == _creatureB)
            EXPECT_TRUE(ref->IsSuppressed());
    // Remove immunity
    _creatureB->ApplySpellImmune(1, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, false);
    // EvaluateSuppressed with canExpire=false should NOT restore to online
    _creatureB->TestGetThreatMgr().EvaluateSuppressed(false);
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
        if (ref->GetVictim() == _creatureB)
            EXPECT_TRUE(ref->IsSuppressed()); // still suppressed
    // EvaluateSuppressed with canExpire=true SHOULD restore to online
    _creatureB->TestGetThreatMgr().EvaluateSuppressed(true);
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
    {
        if (ref->GetVictim() == _creatureB)
        {
            EXPECT_TRUE(ref->IsOnline());
            EXPECT_FALSE(ref->IsSuppressed());
        }
    }
}
References IMMUNITY_DAMAGE, and SPELL_SCHOOL_MASK_NORMAL.
TEST_F() [18/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , EvaluateSuppressed_DamageImmunity_SetsSuppressed)
{
    // A has B on threat list
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // Verify B's ref starts as ONLINE
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
        if (ref->GetVictim() == _creatureB)
            EXPECT_TRUE(ref->IsOnline());
    // Make B immune to physical damage (A's melee school is SPELL_SCHOOL_MASK_NORMAL)
    // This triggers ShouldBeSuppressed via IsImmunedToDamage
    _creatureB->ApplySpellImmune(1, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, true);
    // EvaluateSuppressed checks each ref in _threatenedByMe
    _creatureB->TestGetThreatMgr().EvaluateSuppressed();
    // B's ref on A's threat list should now be SUPPRESSED
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
    {
        if (ref->GetVictim() == _creatureB)
        {
            EXPECT_TRUE(ref->IsSuppressed());
            EXPECT_FALSE(ref->IsOnline());
            EXPECT_TRUE(ref->IsAvailable()); // SUPPRESSED is still available
        }
    }
    // Threat value should still be retrievable (SUPPRESSED is available)
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 100.0f);
    // Cleanup immunity
    _creatureB->ApplySpellImmune(1, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, false);
}
References IMMUNITY_DAMAGE, and SPELL_SCHOOL_MASK_NORMAL.
TEST_F() [19/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , EvaluateSuppressed_MultipleRefs_EachEvaluatedIndependently)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90001); // Same faction as A
    // Both A and C have B on their threat lists
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    creatureC->TestGetThreatMgr().AddThreat(_creatureB, 200.0f);
    // Apply immunity on B
    _creatureB->ApplySpellImmune(1, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, true);
    _creatureB->TestGetThreatMgr().EvaluateSuppressed();
    // Both refs should be suppressed
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
        if (ref->GetVictim() == _creatureB)
            EXPECT_TRUE(ref->IsSuppressed());
    for (ThreatReference const* ref : creatureC->TestGetThreatMgr().GetUnsortedThreatList())
        if (ref->GetVictim() == _creatureB)
            EXPECT_TRUE(ref->IsSuppressed());
    // Remove immunity and expire
    _creatureB->ApplySpellImmune(1, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, false);
    _creatureB->TestGetThreatMgr().EvaluateSuppressed(true);
    // Both should be online again
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
        if (ref->GetVictim() == _creatureB)
            EXPECT_TRUE(ref->IsOnline());
    for (ThreatReference const* ref : creatureC->TestGetThreatMgr().GetUnsortedThreatList())
        if (ref->GetVictim() == _creatureB)
            EXPECT_TRUE(ref->IsOnline());
    creatureC->CleanupCombatState();
    delete creatureC;
}
References ThreatManager::AddThreat(), TestCreature::CleanupCombatState(), ThreatManager::GetUnsortedThreatList(), IMMUNITY_DAMAGE, TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), SPELL_SCHOOL_MASK_NORMAL, and TestCreature::TestGetThreatMgr().
TEST_F() [20/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , EvaluateSuppressed_NoRefs_DoesNotCrash)
{
    // B is not on anyone's threat list — EvaluateSuppressed should be a no-op
    EXPECT_FALSE(_creatureB->TestGetThreatMgr().IsThreateningAnyone());
    _creatureB->TestGetThreatMgr().EvaluateSuppressed();
    _creatureB->TestGetThreatMgr().EvaluateSuppressed(true);
}
TEST_F() [21/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , EvaluateSuppressed_OnlineRefs_RemainOnline)
{
    // A has B on threat list — B's ref on A's list should be ONLINE
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // EvaluateSuppressed on B (the victim) should not change anything
    // since B is not immune to anything
    _creatureB->TestGetThreatMgr().EvaluateSuppressed();
    // Verify ref is still available (ONLINE or SUPPRESSED both pass)
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB, false));
    // Verify it's specifically online by checking it's not suppressed
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
    {
        if (ref->GetVictim() == _creatureB)
        {
            EXPECT_TRUE(ref->IsOnline());
            EXPECT_FALSE(ref->IsSuppressed());
        }
    }
}
TEST_F() [22/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , EvaluateSuppressed_TauntedVictim_NeverSuppressed)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // Taunt B
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_TAUNT);
    // Apply damage immunity — normally would suppress
    _creatureB->ApplySpellImmune(1, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, true);
    _creatureB->TestGetThreatMgr().EvaluateSuppressed();
    // Taunted victims should never be suppressed (ShouldBeSuppressed returns false)
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
        if (ref->GetVictim() == _creatureB)
            EXPECT_TRUE(ref->IsOnline());
    // Cleanup
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_NONE);
    _creatureB->ApplySpellImmune(1, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, false);
}
References IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, ThreatReference::TAUNT_STATE_NONE, and ThreatReference::TAUNT_STATE_TAUNT.
TEST_F() [23/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , FixateTarget_NotOnThreatList_ClearsExistingFixate)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // Both B and C are on the threat list
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // Set a valid fixate first
    _creatureA->TestGetThreatMgr().FixateTarget(_creatureB);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetFixateTarget(), _creatureB);
    // Now fixate on C (not on threat list) — should clear the existing fixate
    _creatureA->TestGetThreatMgr().FixateTarget(creatureC);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetFixateTarget(), nullptr);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [24/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , FixateTarget_NotOnThreatList_ClearsFixate)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // B is on the threat list, C is NOT
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatenedBy(creatureC));
    // Fixate on C (not on threat list) — should result in nullptr fixate
    _creatureA->TestGetThreatMgr().FixateTarget(creatureC);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetFixateTarget(), nullptr);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [25/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , FixateTarget_OverridesSelection)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    // Force a threat update cycle so ReselectVictim() applies the 110%/130% switching rules
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    // Without fixate, highest threat (creatureC) is selected
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), creatureC);
    // Fixate on lower-threat target
    _creatureA->TestGetThreatMgr().FixateTarget(_creatureB);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), _creatureB);
    // Clear fixate returns to normal selection
    _creatureA->TestGetThreatMgr().ClearFixate();
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), creatureC);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [26/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ForwardThreat_CCTarget_GetsZeroThreat)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90001); // Same faction as A
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002); // The healer
    // A has B on threat list, C also has B
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    creatureC->TestGetThreatMgr().AddThreat(_creatureB, 200.0f);
    // A is under CC (UNIT_STATE_CONTROLLED) — should get 0 threat
    _creatureA->AddUnitState(UNIT_STATE_CONTROLLED);
    _creatureB->TestGetThreatMgr().ForwardThreatForAssistingMe(
        creatureD, 100.0f);
    // Only C is not CC'd, so it gets all 100 (100 / 1 non-CC target)
    EXPECT_FLOAT_EQ(
        creatureC->TestGetThreatMgr().GetThreat(creatureD), 100.0f);
    // A gets 0 threat (CC'd creatures still get combat but 0 threat)
    float aThreatForD = _creatureA->TestGetThreatMgr().GetThreat(creatureD);
    EXPECT_FLOAT_EQ(aThreatForD, 0.0f);
    _creatureA->ClearUnitState(UNIT_STATE_CONTROLLED);
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References ThreatManager::AddThreat(), TestCreature::CleanupCombatState(), ThreatManager::GetThreat(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), TestCreature::TestGetThreatMgr(), and UNIT_STATE_CONTROLLED.
TEST_F() [27/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ForwardThreat_MultipleCreatures_SplitsEvenly)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90001); // Same faction as A (so it can also threat B)
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002); // The healer
    // A (boss1) and C (boss2) both have B on their threat lists
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    creatureC->TestGetThreatMgr().AddThreat(_creatureB, 200.0f);
    // B is "healed" by D — forward 100 assist threat
    // Should split evenly: 50 to A, 50 to C
    _creatureB->TestGetThreatMgr().ForwardThreatForAssistingMe(
        creatureD, 100.0f);
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(creatureD), 50.0f);
    EXPECT_FLOAT_EQ(
        creatureC->TestGetThreatMgr().GetThreat(creatureD), 50.0f);
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References ThreatManager::AddThreat(), TestCreature::CleanupCombatState(), ThreatManager::GetThreat(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and TestCreature::TestGetThreatMgr().
TEST_F() [28/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ForwardThreat_NoThreatenedBy_DoesNothing)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // B is not on anyone's threat list
    EXPECT_FALSE(_creatureB->TestGetThreatMgr().IsThreateningAnyone());
    // Forward should be a no-op
    _creatureB->TestGetThreatMgr().ForwardThreatForAssistingMe(
        creatureC, 100.0f);
    // A should have no threat entries
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 0u);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [29/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ForwardThreat_SingleCreature_AllThreatToAssistant)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // A (boss) has B on its threat list
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // B is "healed" — forward 50 assist threat from C (the healer)
    // ForwardThreat iterates _threatenedByMe (creatures threatening B)
    // and adds threat for the assistant (C) on those creatures' lists
    _creatureB->TestGetThreatMgr().ForwardThreatForAssistingMe(
        creatureC, 50.0f);
    // C should now have 50 threat on A's threat list
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(creatureC));
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(creatureC), 50.0f);
    // B's threat should be unchanged
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 100.0f);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [30/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ForwardThreat_ZeroAmount_StillEntersCombat)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // A has B on threat list
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // Forward 0 threat — should still create combat reference
    _creatureB->TestGetThreatMgr().ForwardThreatForAssistingMe(
        creatureC, 0.0f);
    // C should be in combat with A (threat of 0 but combat ref exists)
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(creatureC));
    // Threat value should be 0
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(creatureC), 0.0f);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [31/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetAnyTarget_AllOffline_ReturnsNull)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureB->SetPhase(2);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetAnyTarget(), nullptr);
}
References ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [32/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetAnyTarget_EmptyList_ReturnsNull)
{
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetAnyTarget(), nullptr);
}
TEST_F() [33/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetAnyTarget_WithEntries_ReturnsNonNull)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_NE(_creatureA->TestGetThreatMgr().GetAnyTarget(), nullptr);
}
TEST_F() [34/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetCurrentVictim_ReturnsHighestThreat)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    // Force a threat update cycle so ReselectVictim() applies the 110%/130% switching rules
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    Unit* victim = _creatureA->TestGetThreatMgr().GetCurrentVictim();
    EXPECT_EQ(victim, creatureC);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [35/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetFixateTarget_NoFixate_ReturnsNull)
{
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetFixateTarget(), nullptr);
}
TEST_F() [36/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetFixateTarget_WithFixate_ReturnsTarget)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().FixateTarget(_creatureB);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetFixateTarget(), _creatureB);
    _creatureA->TestGetThreatMgr().ClearFixate();
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetFixateTarget(), nullptr);
}
TEST_F() [37/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetLastVictim_NoVictim_ReturnsNull)
{
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetLastVictim(), nullptr);
}
TEST_F() [38/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetLastVictim_OfflineVictim_ReturnsNull)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    _creatureB->SetPhase(2);
    // GetLastVictim checks ShouldBeOffline on cached ref
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetLastVictim(), nullptr);
}
References ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [39/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetLastVictim_WithVictim_ReturnsCached)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetLastVictim(), _creatureB);
}
References ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [40/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetModifiableThreatList_ReturnsCopy)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 50.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 200.0f);
    auto list = _creatureA->TestGetThreatMgr().GetModifiableThreatList();
    EXPECT_EQ(list.size(), 2u);
    // Verify it's sorted (highest first)
    EXPECT_GE(list[0]->GetThreat(), list[1]->GetThreat());
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [41/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetSortedThreatList_ReturnsSortedByThreat)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 50.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 200.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureD, 100.0f);
    float prevThreat = std::numeric_limits<float>::max();
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetSortedThreatList())
    {
        EXPECT_LE(ref->GetThreat(), prevThreat);
        prevThreat = ref->GetThreat();
    }
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [42/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetThreat_NonexistentTarget_ReturnsZero)
{
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 0.0f);
}
TEST_F() [43/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetThreat_OfflineTarget_ExcludedByDefault)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // Move B offline via phase change
    _creatureB->SetPhase(2);
    // Force re-evaluation
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    // Default (includeOffline=false) should return 0
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB, false), 0.0f);
    // includeOffline=true should return the threat value
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB, true), 100.0f);
}
References ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [44/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetThreatListPlayerCount_CreatureOnlyList_ReturnsZero)
{
    // All entries are creatures, not players — count should be 0
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 200.0f);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 2u);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListPlayerCount(), 0u);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListPlayerCount(true), 0u);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [45/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , GetUnsortedThreatList_ReturnsAllEntries)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 50.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 200.0f);
    size_t count = 0;
    for ([[maybe_unused]] ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
        ++count;
    EXPECT_EQ(count, 2u);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [46/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , IsEngagedBy_CombatWithoutThreat_NotEngaged)
{
    // Combat reference without threat entry
    _creatureA->TestGetCombatMgr().SetInCombatWith(_creatureB);
    EXPECT_TRUE(_creatureA->TestGetCombatMgr().IsInCombatWith(_creatureB));
    // IsEngagedBy checks threat list for creatures, not combat refs
    EXPECT_FALSE(_creatureA->IsEngagedBy(_creatureB));
}
TEST_F() [47/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , IsEngagedBy_UsesThreatListForCreatures)
{
    // Before any threat, not engaged
    EXPECT_FALSE(_creatureA->IsEngagedBy(_creatureB));
    // AddThreat creates a threat reference (and combat reference)
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // IsEngagedBy should check threat list for creatures with threat lists
    EXPECT_TRUE(_creatureA->IsEngagedBy(_creatureB));
    // B is on A's threat list but A is NOT on B's threat list
    // (threat is directional: A threatens B, not vice versa unless B also AddThreats A)
    EXPECT_FALSE(_creatureB->IsEngagedBy(_creatureA));
}
TEST_F() [48/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , IsThreatenedBy_OfflineTarget_Variants)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureB->SetPhase(2);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    // Default (online only) — should be false
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB, false));
    // Including offline — should be true
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB, true));
}
References ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [49/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , IsThreateningAnyone_AllOffline_FalseWithoutFlag)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // Make B's ref on A's list go offline
    _creatureB->SetPhase(2);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    // B is still threatening A, but the ref is offline
    EXPECT_FALSE(_creatureB->TestGetThreatMgr().IsThreateningAnyone(false));
    EXPECT_TRUE(_creatureB->TestGetThreatMgr().IsThreateningAnyone(true));
}
References ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [50/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , IsThreateningAnyone_NoEntries_ReturnsFalse)
{
    EXPECT_FALSE(_creatureB->TestGetThreatMgr().IsThreateningAnyone());
    EXPECT_FALSE(_creatureB->TestGetThreatMgr().IsThreateningAnyone(true));
}
TEST_F() [51/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , IsThreateningAnyone_WithEntries_ReturnsTrue)
{
    // A adds threat against B → B appears in A's threat list
    // B is a "victim" on A's list → B._threatenedByMe has an entry for A
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_TRUE(_creatureB->TestGetThreatMgr().IsThreateningAnyone());
    EXPECT_TRUE(_creatureB->TestGetThreatMgr().IsThreateningAnyone(true));
}
TEST_F() [52/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , IsThreateningTo_ObjectGuidVariant)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_TRUE(_creatureB->TestGetThreatMgr().IsThreateningTo(_creatureA->GetGUID()));
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreateningTo(_creatureB->GetGUID()));
}
TEST_F() [53/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , IsThreateningTo_SpecificTarget)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // B is threatening A (B appears on A's threat list)
    EXPECT_TRUE(_creatureB->TestGetThreatMgr().IsThreateningTo(_creatureA));
    // A is NOT threatening B (A does not appear on B's threat list)
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreateningTo(_creatureB));
}
TEST_F() [54/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , IsThreatListEmpty_AllOffline_TrueWithoutOfflineFlag)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // Move B offline
    _creatureB->SetPhase(2);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    // Online-only should be empty
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatListEmpty(false));
    // Including offline should not be empty
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatListEmpty(true));
}
References ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [55/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , IsThreatListEmpty_EmptyList_ReturnsTrue)
{
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatListEmpty());
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatListEmpty(true));
}
TEST_F() [56/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , IsThreatListEmpty_WithEntries_ReturnsFalse)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatListEmpty());
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatListEmpty(true));
}
TEST_F() [57/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , MatchUnitThreatToHighestThreat_AlreadyHighest_NoChange)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 500.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 100.0f);
    // B is already highest — should stay at 500
    _creatureA->TestGetThreatMgr().MatchUnitThreatToHighestThreat(_creatureB);
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 500.0f);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [58/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , MatchUnitThreatToHighestThreat_HighestIsTaunted_UsesNextEntry)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002);
    // B has low threat (100), C has high threat (500), D has none yet
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureD, 10.0f);
    // Taunt B — B becomes heap top (taunt state wins over threat value)
    // but B's actual threat is only 100.
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_TAUNT);
    // MatchUnitThreatToHighestThreat should skip the taunted entry (B=100)
    // and use C's 500 as the real highest.
    _creatureA->TestGetThreatMgr().MatchUnitThreatToHighestThreat(creatureD);
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(creatureD), 500.0f);
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_NONE);
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), ThreatReference::TAUNT_STATE_NONE, and ThreatReference::TAUNT_STATE_TAUNT.
TEST_F() [59/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , MatchUnitThreatToHighestThreat_SetsToHighest)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // C has highest threat, B has low threat
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 50.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    // Match B's threat to highest (C's 500)
    _creatureA->TestGetThreatMgr().MatchUnitThreatToHighestThreat(_creatureB);
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB),
        _creatureA->TestGetThreatMgr().GetThreat(creatureC));
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [60/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , MatchUnitThreatToHighestThreat_TauntedIsAlsoHighest_UsesTauntedThreat)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002);
    // B has highest threat AND is taunted — no skip needed
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 500.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureD, 10.0f);
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_TAUNT);
    _creatureA->TestGetThreatMgr().MatchUnitThreatToHighestThreat(creatureD);
    // B's 500 is the real highest — D should get 500
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(creatureD), 500.0f);
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_NONE);
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), ThreatReference::TAUNT_STATE_NONE, and ThreatReference::TAUNT_STATE_TAUNT.
TEST_F() [61/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ModifyThreatByPercent_Decrease)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // -30% → 70
    _creatureA->TestGetThreatMgr().ModifyThreatByPercent(_creatureB, -30);
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 70.0f);
}
TEST_F() [62/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ModifyThreatByPercent_Increase)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // +50% → 150
    _creatureA->TestGetThreatMgr().ModifyThreatByPercent(_creatureB, 50);
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 150.0f);
}
TEST_F() [63/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ModifyThreatByPercent_Minus100_ZerosThreat)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // -100% → 0
    _creatureA->TestGetThreatMgr().ModifyThreatByPercent(_creatureB, -100);
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 0.0f);
    // Entry should still exist
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
}
TEST_F() [64/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ModifyThreatByPercent_Plus100_Doubles)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // +100% → 200
    _creatureA->TestGetThreatMgr().ModifyThreatByPercent(_creatureB, 100);
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 200.0f);
}
TEST_F() [65/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ModifyThreatByPercent_ZeroPercent_NoChange)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // 0% change — should be a no-op
    _creatureA->TestGetThreatMgr().ModifyThreatByPercent(_creatureB, 0);
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 100.0f);
}
TEST_F() [66/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , MultipleTaunts_LastTauntWins)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 50.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureD, 25.0f);
    // Taunt from C
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        creatureC, ThreatReference::TAUNT_STATE_TAUNT);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), creatureC);
    // Also taunt from D — both taunted, but D has lower threat
    // With equal taunt state, higher threat wins → C still selected
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        creatureD, ThreatReference::TAUNT_STATE_TAUNT);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), creatureC);
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), ThreatReference::TAUNT_STATE_TAUNT, and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [67/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , PhaseChange_PutsThreatsOffline)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    // B is online on A's threat list
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatListEmpty(false));
    // Move B to a different phase
    _creatureB->SetPhase(2);
    // B should now be offline on A's threat list (different phases)
    // The list is not empty if we include offline, but empty if we don't
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB, true));  // includeOffline
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatListEmpty(false));          // online only
}
TEST_F() [68/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RedirectThreat_AddThreat_SplitsBetweenTargetAndRedirect)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // Pre-establish C on A's threat list (ObjectAccessor unavailable in tests)
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 0.0f, nullptr, true, true);
    // B registers 50% redirect to C (e.g. Misdirection)
    _creatureB->TestGetThreatMgr().RegisterRedirectThreat(
        34477, creatureC->GetGUID(), 50);
    // A adds 100 threat against B — 50% should redirect to C
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f, nullptr, true);
    // B should have 50 threat (100 - 50% redirected)
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 50.0f);
    // C should have 50 threat (the redirected portion)
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(creatureC));
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(creatureC), 50.0f);
    _creatureB->TestGetThreatMgr().UnregisterRedirectThreat(34477);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), Object::GetGUID(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [69/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RedirectThreat_AfterUnregister_NoMoreRedirect)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // Pre-establish C on A's threat list (ObjectAccessor unavailable in tests)
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 0.0f, nullptr, true, true);
    _creatureB->TestGetThreatMgr().RegisterRedirectThreat(
        34477, creatureC->GetGUID(), 50);
    // First add — should redirect
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f, nullptr, true);
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 50.0f);
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(creatureC), 50.0f);
    // Unregister redirect
    _creatureB->TestGetThreatMgr().UnregisterRedirectThreat(34477);
    // Second add — should NOT redirect, all goes to B
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f, nullptr, true);
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 150.0f);
    // C should still have 50 from before
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(creatureC), 50.0f);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), Object::GetGUID(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [70/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RedirectThreat_Exactly100Percent_AllRedirected)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002);
    // Pre-establish C and D on A's threat list
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 0.0f, nullptr, true, true);
    _creatureA->TestGetThreatMgr().AddThreat(creatureD, 0.0f, nullptr, true, true);
    // Register redirects totaling exactly 100% (60% + 40%)
    _creatureB->TestGetThreatMgr().RegisterRedirectThreat(
        34477, creatureC->GetGUID(), 60);
    _creatureB->TestGetThreatMgr().RegisterRedirectThreat(
        57934, creatureD->GetGUID(), 40);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 200.0f, nullptr, true);
    // B should get 0 (all redirected)
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 0.0f);
    // C + D should have 200 total
    float cThreat = _creatureA->TestGetThreatMgr().GetThreat(creatureC);
    float dThreat = _creatureA->TestGetThreatMgr().GetThreat(creatureD);
    EXPECT_FLOAT_EQ(cThreat + dThreat, 200.0f);
    _creatureB->TestGetThreatMgr().UnregisterRedirectThreat(34477);
    _creatureB->TestGetThreatMgr().UnregisterRedirectThreat(57934);
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References TestCreature::CleanupCombatState(), Object::GetGUID(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [71/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RedirectThreat_FullRedirect_AllThreatGoesToTarget)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // Pre-establish C on A's threat list (ObjectAccessor unavailable in tests)
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 0.0f, nullptr, true, true);
    // B registers 100% redirect to C
    _creatureB->TestGetThreatMgr().RegisterRedirectThreat(
        34477, creatureC->GetGUID(), 100);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 200.0f, nullptr, true);
    // B should have 0 threat (all redirected)
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 0.0f);
    // C should have all 200 threat
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(creatureC), 200.0f);
    _creatureB->TestGetThreatMgr().UnregisterRedirectThreat(34477);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), Object::GetGUID(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [72/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RedirectThreat_NegativeAmount_NoRedirect)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // Establish initial threat
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 200.0f, nullptr, true);
    // Register redirect and apply negative threat (threat reduction)
    _creatureB->TestGetThreatMgr().RegisterRedirectThreat(
        34477, creatureC->GetGUID(), 50);
    // Negative threat should NOT be redirected (code checks amount > 0)
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, -50.0f, nullptr, true);
    // B should have 150 (200 - 50), C should have no entry or 0
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 150.0f);
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatenedBy(creatureC));
    _creatureB->TestGetThreatMgr().UnregisterRedirectThreat(34477);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), Object::GetGUID(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [73/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RedirectThreat_RegisterAndUnregister_PerSpell)
{
    // Register two different spell redirects
    _creatureA->TestGetThreatMgr().RegisterRedirectThreat(
        34477, _creatureB->GetGUID(), 70);  // Misdirection
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().HasRedirects());
    // Unregister only Misdirection
    _creatureA->TestGetThreatMgr().UnregisterRedirectThreat(34477);
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().HasRedirects());
}
TEST_F() [74/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RedirectThreat_ResetAllRedirects_ClearsAll)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().RegisterRedirectThreat(
        34477, _creatureB->GetGUID(), 70);
    _creatureA->TestGetThreatMgr().RegisterRedirectThreat(
        57934, creatureC->GetGUID(), 30);
    _creatureA->TestGetThreatMgr().ResetAllRedirects();
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().HasRedirects());
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), Object::GetGUID(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [75/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RedirectThreat_TotalExceeds100_CappedAt100)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002);
    // Pre-establish C and D on A's threat list
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 0.0f, nullptr, true, true);
    _creatureA->TestGetThreatMgr().AddThreat(creatureD, 0.0f, nullptr, true, true);
    // Register redirects totaling 130% (70% + 60%)
    _creatureB->TestGetThreatMgr().RegisterRedirectThreat(
        34477, creatureC->GetGUID(), 70);
    _creatureB->TestGetThreatMgr().RegisterRedirectThreat(
        57934, creatureD->GetGUID(), 60);
    // Add 100 threat from A to B
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f, nullptr, true);
    // Total redirected should be capped at 100%, so B gets 0
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 0.0f);
    // C + D together should have exactly 100 (the full amount)
    float cThreat = _creatureA->TestGetThreatMgr().GetThreat(creatureC);
    float dThreat = _creatureA->TestGetThreatMgr().GetThreat(creatureD);
    EXPECT_FLOAT_EQ(cThreat + dThreat, 100.0f);
    // First redirect should get its full 70%, second gets capped to 30%
    // (iteration order of unordered_map may vary, so check the sum is correct
    // and each individual value is within expected bounds)
    EXPECT_GE(cThreat, 0.0f);
    EXPECT_LE(cThreat, 100.0f);
    EXPECT_GE(dThreat, 0.0f);
    EXPECT_LE(dThreat, 100.0f);
    _creatureB->TestGetThreatMgr().UnregisterRedirectThreat(34477);
    _creatureB->TestGetThreatMgr().UnregisterRedirectThreat(57934);
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References TestCreature::CleanupCombatState(), Object::GetGUID(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [76/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RedirectThreat_TwoSpells_BothRedirect)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002);
    // Pre-establish C and D on A's threat list
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 0.0f, nullptr, true, true);
    _creatureA->TestGetThreatMgr().AddThreat(creatureD, 0.0f, nullptr, true, true);
    // B registers two redirects that total 60% (no cap issue)
    _creatureB->TestGetThreatMgr().RegisterRedirectThreat(
        34477, creatureC->GetGUID(), 30);  // Misdirection 30%
    _creatureB->TestGetThreatMgr().RegisterRedirectThreat(
        57934, creatureD->GetGUID(), 30);  // Tricks of the Trade 30%
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f, nullptr, true);
    // B should have 40 threat (100 - 30 - 30)
    EXPECT_FLOAT_EQ(
        _creatureA->TestGetThreatMgr().GetThreat(_creatureB), 40.0f);
    // C and D should each have 30 threat
    float cThreat = _creatureA->TestGetThreatMgr().GetThreat(creatureC);
    float dThreat = _creatureA->TestGetThreatMgr().GetThreat(creatureD);
    // Due to unordered_map iteration, we verify total redirected = 60
    EXPECT_FLOAT_EQ(cThreat + dThreat, 60.0f);
    EXPECT_FLOAT_EQ(cThreat, 30.0f);
    EXPECT_FLOAT_EQ(dThreat, 30.0f);
    _creatureB->TestGetThreatMgr().UnregisterRedirectThreat(34477);
    _creatureB->TestGetThreatMgr().UnregisterRedirectThreat(57934);
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References TestCreature::CleanupCombatState(), Object::GetGUID(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [77/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RedirectThreat_UnregisterOneSpell_KeepsOther)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // Register two different spell redirects to different targets
    _creatureA->TestGetThreatMgr().RegisterRedirectThreat(
        34477, _creatureB->GetGUID(), 70);  // Misdirection
    _creatureA->TestGetThreatMgr().RegisterRedirectThreat(
        57934, creatureC->GetGUID(), 30);   // Tricks of the Trade
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().HasRedirects());
    // Unregister only Misdirection — Tricks should remain
    _creatureA->TestGetThreatMgr().UnregisterRedirectThreat(34477);
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().HasRedirects());
    // Unregister Tricks — now empty
    _creatureA->TestGetThreatMgr().UnregisterRedirectThreat(57934);
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().HasRedirects());
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), Object::GetGUID(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [78/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RedirectThreat_UnregisterPerSpellPerVictim)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002);
    // Register same spell with two different victims
    _creatureB->TestGetThreatMgr().RegisterRedirectThreat(
        34477, creatureC->GetGUID(), 30);
    _creatureB->TestGetThreatMgr().RegisterRedirectThreat(
        34477, creatureD->GetGUID(), 20);
    EXPECT_TRUE(_creatureB->TestGetThreatMgr().HasRedirects());
    // Unregister only the C victim for spell 34477
    _creatureB->TestGetThreatMgr().UnregisterRedirectThreat(
        34477, creatureC->GetGUID());
    // D's redirect should still be active
    EXPECT_TRUE(_creatureB->TestGetThreatMgr().HasRedirects());
    // Unregister D — now empty
    _creatureB->TestGetThreatMgr().UnregisterRedirectThreat(
        34477, creatureD->GetGUID());
    EXPECT_FALSE(_creatureB->TestGetThreatMgr().HasRedirects());
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References TestCreature::CleanupCombatState(), Object::GetGUID(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [79/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RemoveMeFromThreatLists_NoEntries_DoesNotCrash)
{
    // B is not on anyone's threat list — should be safe no-op
    _creatureB->TestGetThreatMgr().RemoveMeFromThreatLists();
    EXPECT_FALSE(_creatureB->TestGetThreatMgr().IsThreateningAnyone());
}
TEST_F() [80/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , RemoveMeFromThreatLists_RemovesFromAllLists)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90001);
    // A and C both have B on their threat lists
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    creatureC->TestGetThreatMgr().AddThreat(_creatureB, 200.0f);
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    EXPECT_TRUE(creatureC->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    // B removes itself from all threat lists
    _creatureB->TestGetThreatMgr().RemoveMeFromThreatLists();
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    EXPECT_FALSE(creatureC->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    EXPECT_FALSE(_creatureB->TestGetThreatMgr().IsThreateningAnyone());
    creatureC->CleanupCombatState();
    delete creatureC;
}
References ThreatManager::AddThreat(), TestCreature::CleanupCombatState(), ThreatManager::IsThreatenedBy(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and TestCreature::TestGetThreatMgr().
TEST_F() [81/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ReselectVictim_Below110Percent_KeepsOldVictim)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // B gets threat first and becomes initial victim
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), _creatureB);
    // C gets 109% of B's threat — below 110% threshold, should NOT switch
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 109.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), _creatureB);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [82/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ReselectVictim_EqualThreat_KeepsCurrentVictim)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // B is initial victim
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), _creatureB);
    // C gets exactly equal threat — should NOT switch (need >110%)
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 100.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), _creatureB);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [83/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ReselectVictim_MeleeAt110Percent_Switches)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // Both creatures at same position (0,0,0) = within melee range
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), _creatureB);
    // C gets 111% of B's threat and is melee — should switch
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 111.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), creatureC);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [84/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ReselectVictim_MeleeAt130Percent_AlsoSwitches)
{
    // Verify that a melee target above 130% also switches (melee only needs
    // 110%, so 130% should certainly work too)
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), _creatureB);
    // C gets 131% threat — well above melee 110% threshold, should switch
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 131.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), creatureC);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [85/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ReselectVictim_MeleeThirdTarget_AboveThreshold_Switches)
{
    // Three melee targets — verify correct switching with multiple candidates
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002);
    // B is current victim with 100 threat
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), _creatureB);
    // C has 105% — below 110% threshold, won't switch
    // D has 115% — above 110% threshold, should switch to D
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 105.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureD, 115.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    // Should pick D (highest above threshold)
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), creatureD);
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [86/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ReselectVictim_NoOldVictim_PicksHighest)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // Add both at the same time — no previous victim
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 50.0f);
    // First victim selection — should pick highest regardless of thresholds
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), _creatureB);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [87/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ResetAllMyThreatOnOthers_NoEntries_DoesNothing)
{
    // creatureB is not on anyone's threat list
    EXPECT_FALSE(_creatureB->TestGetThreatMgr().IsThreateningAnyone());
    // Should not crash or assert
    _creatureB->TestGetThreatMgr().ResetAllMyThreatOnOthers();
}
TEST_F() [88/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ResetAllMyThreatOnOthers_ZerosThreatOnAllCreatures)
{
    // creatureA and creatureC both add threat against creatureB
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90001);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    creatureC->TestGetThreatMgr().AddThreat(_creatureB, 200.0f);
    // creatureB appears on both A's and C's threat lists
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 100.0f);
    EXPECT_FLOAT_EQ(creatureC->TestGetThreatMgr().GetThreat(_creatureB), 200.0f);
    // Reset creatureB's threat on all others' lists
    _creatureB->TestGetThreatMgr().ResetAllMyThreatOnOthers();
    // creatureB's threat should be zeroed on both lists
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 0.0f);
    EXPECT_FLOAT_EQ(creatureC->TestGetThreatMgr().GetThreat(_creatureB), 0.0f);
    // Entries still exist — only zeroed, not removed
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    EXPECT_TRUE(creatureC->TestGetThreatMgr().IsThreatenedBy(_creatureB));
    creatureC->CleanupCombatState();
    delete creatureC;
}
References ThreatManager::AddThreat(), TestCreature::CleanupCombatState(), ThreatManager::GetThreat(), ThreatManager::IsThreatenedBy(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and TestCreature::TestGetThreatMgr().
TEST_F() [89/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ResetAllThreat_ZerosAllEntries)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    _creatureA->TestGetThreatMgr().ResetAllThreat();
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 0.0f);
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(creatureC), 0.0f);
    // Entries still exist, just zeroed
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 2u);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), and TestCreature::SetupForCombatTest().
TEST_F() [90/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ScaleThreat_DoublesAmount)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().ScaleThreat(_creatureB, 2.0f);
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 200.0f);
}
TEST_F() [91/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ScaleThreat_ZeroFactor_ZerosThreat)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().ScaleThreat(_creatureB, 0.0f);
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 0.0f);
    // Entry still exists (ScaleThreat doesn't remove)
    EXPECT_TRUE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
}
TEST_F() [92/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , SendThreatList_HighestThreatUpdate_Path)
{
    // SMSG_HIGHEST_THREAT_UPDATE is sent when victim changes
    // (newHighest=true in UpdateVictim)
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    // Update forces ReselectVictim → victim switches from B
    // to C → newHighest=true → SendThreatListToClients(true)
    // exercises the SMSG_HIGHEST_THREAT_UPDATE packet path
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureC);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [93/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , SendThreatList_ThreatUpdate_Path)
{
    // SMSG_THREAT_UPDATE is sent when _needClientUpdate=true
    // but victim doesn't change (newHighest=false)
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // Add lower threat — victim stays as B,
    // but PutThreatListRef sets _needClientUpdate=true
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 50.0f);
    // Update → victim unchanged (B still highest) →
    // newHighest=false, _needClientUpdate=true →
    // SendThreatListToClients(false)
    // exercises the SMSG_THREAT_UPDATE packet path
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        _creatureB);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [94/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , SpellSchoolModifiers_DefaultIsUnmodified)
{
    // Default modifier should be 1.0 (no modification)
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_FLOAT_EQ(_creatureA->TestGetThreatMgr().GetThreat(_creatureB), 100.0f);
}
TEST_F() [95/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , TauntState_DoesNotClobberFixate)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 200.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureD, 300.0f);
    // Script fixate on C
    _creatureA->TestGetThreatMgr().FixateTarget(creatureC);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureC);
    // Taunt from B — fixate should still win
    // (fixate is checked before heap in ReselectVictim)
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_TAUNT);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureC);
    // Fixate ref should still be intact
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetFixateTarget(),
        creatureC);
    // Clear taunt — fixate still holds
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_NONE);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureC);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetFixateTarget(),
        creatureC);
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), ThreatReference::TAUNT_STATE_NONE, ThreatReference::TAUNT_STATE_TAUNT, and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [96/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , TauntState_OverridesHigherThreat)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // B has low threat, C has high threat
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureC);
    // Taunt B — should override despite lower threat
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_TAUNT);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        _creatureB);
    // Remove taunt — should revert to C
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_NONE);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureC);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), ThreatReference::TAUNT_STATE_NONE, ThreatReference::TAUNT_STATE_TAUNT, and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [97/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , TauntUpdate_EmptyThreatList_NoCrash)
{
    // TauntUpdate on a creature with no threats should not crash
    // even though UpdateVictim is now called internally
    _creatureA->TestGetThreatMgr().TauntUpdate();
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        nullptr);
}
TEST_F() [98/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , TauntUpdate_RapidCalls_NoCrash)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    // Rapidly call TauntUpdate (no real auras — clears taunt state each
    // time and calls UpdateVictim). Must not crash or recurse.
    for (int i = 0; i < 50; ++i)
        _creatureA->TestGetThreatMgr().TauntUpdate();
    // C remains victim (highest threat, no taunt active)
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureC);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [99/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ThreatConstants)
{
    constexpr uint32 interval = ThreatManager::THREAT_UPDATE_INTERVAL;
    EXPECT_EQ(interval, 1000u);
    EXPECT_GE(interval, 500u);
    EXPECT_LE(interval, 2000u);
    EXPECT_EQ(static_cast<int>(ThreatReference::ONLINE_STATE_OFFLINE), 0);
    EXPECT_EQ(static_cast<int>(ThreatReference::ONLINE_STATE_SUPPRESSED), 1);
    EXPECT_EQ(static_cast<int>(ThreatReference::ONLINE_STATE_ONLINE), 2);
    EXPECT_EQ(static_cast<uint32>(ThreatReference::TAUNT_STATE_DETAUNT), 0);
    EXPECT_EQ(static_cast<uint32>(ThreatReference::TAUNT_STATE_NONE), 1);
    EXPECT_EQ(static_cast<uint32>(ThreatReference::TAUNT_STATE_TAUNT), 2);
}
References ThreatReference::ONLINE_STATE_OFFLINE, ThreatReference::ONLINE_STATE_ONLINE, ThreatReference::ONLINE_STATE_SUPPRESSED, ThreatReference::TAUNT_STATE_DETAUNT, ThreatReference::TAUNT_STATE_NONE, ThreatReference::TAUNT_STATE_TAUNT, and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [100/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ThreatReference_AddThreat_ZeroAmount_NoOp)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    auto list = _creatureA->TestGetThreatMgr().GetModifiableThreatList();
    ASSERT_EQ(list.size(), 1u);
    // AddThreat(0.0f) has an early return — no heap notification
    list[0]->AddThreat(0.0f);
    EXPECT_FLOAT_EQ(list[0]->GetThreat(), 100.0f);
}
TEST_F() [101/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ThreatReference_ClearThreat_DirectCall_RemovesEntry)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 1u);
    // Get the reference via modifiable list and call ClearThreat() on it
    auto list = _creatureA->TestGetThreatMgr().GetModifiableThreatList();
    ASSERT_EQ(list.size(), 1u);
    list[0]->ClearThreat(); // self-deallocation — pointer is now invalid
    // Entry should be gone
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetThreatListSize(), 0u);
    EXPECT_FALSE(_creatureA->TestGetThreatMgr().IsThreatenedBy(_creatureB));
}
TEST_F() [102/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ThreatReference_GetOwnerAndVictim)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    for (ThreatReference const* ref : _creatureA->TestGetThreatMgr().GetUnsortedThreatList())
    {
        if (ref->GetVictim() == _creatureB)
        {
            EXPECT_EQ(ref->GetOwner(), _creatureA);
            EXPECT_EQ(ref->GetVictim(), _creatureB);
            EXPECT_FLOAT_EQ(ref->GetThreat(), 100.0f);
            EXPECT_TRUE(ref->IsOnline());
            EXPECT_FALSE(ref->IsOffline());
            EXPECT_FALSE(ref->IsSuppressed());
            EXPECT_TRUE(ref->IsAvailable());
            EXPECT_EQ(ref->GetTauntState(), ThreatReference::TAUNT_STATE_NONE);
            EXPECT_FALSE(ref->IsTaunting());
            EXPECT_FALSE(ref->IsDetaunted());
        }
    }
}
References ThreatReference::TAUNT_STATE_NONE.
TEST_F() [103/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ThreatReference_ScaleThreat_Directly)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    auto list = _creatureA->TestGetThreatMgr().GetModifiableThreatList();
    ASSERT_EQ(list.size(), 1u);
    list[0]->ScaleThreat(3.0f);
    EXPECT_FLOAT_EQ(list[0]->GetThreat(), 300.0f);
    list[0]->ModifyThreatByPercent(-50);
    EXPECT_FLOAT_EQ(list[0]->GetThreat(), 150.0f);
}
TEST_F() [104/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , ThreatReference_ScaleThreat_Factor1_NoOp)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    auto list = _creatureA->TestGetThreatMgr().GetModifiableThreatList();
    ASSERT_EQ(list.size(), 1u);
    // ScaleThreat(1.0f) has an early return — no heap notification
    list[0]->ScaleThreat(1.0f);
    EXPECT_FLOAT_EQ(list[0]->GetThreat(), 100.0f);
}
TEST_F() [105/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , Update_EmptyThreatList_DoesNotCrash)
{
    // Update with no threat entries — should be safe no-op
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), nullptr);
}
References ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [106/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , Update_TimerDrivenReselection)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().Update(ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), _creatureB);
    // Add much higher threat to C
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    // Partial update (less than interval) — timer hasn't fired yet
    _creatureA->TestGetThreatMgr().Update(500);
    // GetCurrentVictim triggers immediate UpdateVictim so it will still return C
    // But the timer-based path hasn't fired yet
    // Verify Update doesn't crash on partial timer
    EXPECT_NE(_creatureA->TestGetThreatMgr().GetCurrentVictim(), nullptr);
    // Full interval fires timer-based reselection
    _creatureA->TestGetThreatMgr().Update(500);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), creatureC);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [107/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , Update_ZeroDiff_DoesNotCrash)
{
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    // 0ms update should not crash or do anything unexpected
    _creatureA->TestGetThreatMgr().Update(0);
    EXPECT_EQ(_creatureA->TestGetThreatMgr().GetCurrentVictim(), _creatureB);
}
TEST_F() [108/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , UpdateVictim_FixateStillTakesPrecedence)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 200.0f);
    // Fixate on C
    _creatureA->TestGetThreatMgr().FixateTarget(creatureC);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureC);
    // Taunt from B + immediate UpdateVictim — fixate should still win
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_TAUNT);
    _creatureA->TestGetThreatMgr().UpdateVictimForTesting();
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureC);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetFixateTarget(),
        creatureC);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), ThreatReference::TAUNT_STATE_TAUNT, and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [109/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , UpdateVictim_Idempotent_MultipleCalls)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_TAUNT);
    // Call UpdateVictim many times in a row — must be idempotent
    for (int i = 0; i < 50; ++i)
        _creatureA->TestGetThreatMgr().UpdateVictimForTesting();
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        _creatureB);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), ThreatReference::TAUNT_STATE_TAUNT, and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [110/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , UpdateVictim_ImmediateReselectAfterTauntState)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    // B has low threat, C has high threat
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureC);
    // Set taunt on B, then call UpdateVictim directly (the call that
    // TauntUpdate now makes internally) — WITHOUT waiting for the
    // 1-second Update() timer
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_TAUNT);
    _creatureA->TestGetThreatMgr().UpdateVictimForTesting();
    // Victim should switch immediately to B (taunted)
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        _creatureB);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), ThreatReference::TAUNT_STATE_TAUNT, and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [111/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , UpdateVictim_MultipleTaunters_HighestStateWins)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    TestCreature* creatureD = new TestCreature();
    creatureD->SetupForCombatTest(_map, 4, 12348);
    creatureD->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 200.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureD, 300.0f);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureD);
    // Two taunters: B (state=TAUNT) and C (state=TAUNT+1, i.e. "last taunt")
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_TAUNT);
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        creatureC, static_cast<ThreatReference::TauntState>(
            ThreatReference::TAUNT_STATE_TAUNT + 1));
    _creatureA->TestGetThreatMgr().UpdateVictimForTesting();
    // C has the higher taunt state — should be victim immediately
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        creatureC);
    creatureC->CleanupCombatState();
    creatureD->CleanupCombatState();
    delete creatureC;
    delete creatureD;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), ThreatReference::TAUNT_STATE_TAUNT, and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [112/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , UpdateVictim_RapidTauntToggle_NoCrash)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    // Rapidly toggle taunt state with immediate UpdateVictim each time
    for (int i = 0; i < 50; ++i)
    {
        _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
            _creatureB, ThreatReference::TAUNT_STATE_TAUNT);
        _creatureA->TestGetThreatMgr().UpdateVictimForTesting();
        EXPECT_EQ(
            _creatureA->TestGetThreatMgr().GetCurrentVictim(),
            _creatureB);
        _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
            _creatureB, ThreatReference::TAUNT_STATE_NONE);
        _creatureA->TestGetThreatMgr().UpdateVictimForTesting();
        EXPECT_EQ(
            _creatureA->TestGetThreatMgr().GetCurrentVictim(),
            creatureC);
    }
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), ThreatReference::TAUNT_STATE_NONE, ThreatReference::TAUNT_STATE_TAUNT, and ThreatManager::THREAT_UPDATE_INTERVAL.
TEST_F() [113/113]
anonymous_namespace{ThreatManagerTest.cpp}::TEST_F (ThreatManagerIntegrationTest , UpdateVictim_WithConcurrentThreatChanges_NoCrash)
{
    TestCreature* creatureC = new TestCreature();
    creatureC->SetupForCombatTest(_map, 3, 12347);
    creatureC->SetFaction(90002);
    _creatureA->TestGetThreatMgr().AddThreat(_creatureB, 100.0f);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 500.0f);
    _creatureA->TestGetThreatMgr().Update(
        ThreatManager::THREAT_UPDATE_INTERVAL);
    // Simulate taunt landing while threat is also being modified
    // (e.g. damage events arriving in the same server tick)
    _creatureA->TestGetThreatMgr().SetTauntStateForTesting(
        _creatureB, ThreatReference::TAUNT_STATE_TAUNT);
    _creatureA->TestGetThreatMgr().AddThreat(creatureC, 200.0f);
    _creatureA->TestGetThreatMgr().UpdateVictimForTesting();
    // B should be victim because taunt overrides threat
    EXPECT_EQ(
        _creatureA->TestGetThreatMgr().GetCurrentVictim(),
        _creatureB);
    creatureC->CleanupCombatState();
    delete creatureC;
}
References TestCreature::CleanupCombatState(), TestCreature::SetFaction(), TestCreature::SetupForCombatTest(), ThreatReference::TAUNT_STATE_TAUNT, and ThreatManager::THREAT_UPDATE_INTERVAL.