AzerothCore: anonymous_namespace{SpellImmunityTest.cpp} Namespace Reference
anonymous_namespace{SpellImmunityTest.cpp} Namespace Reference
Classes
struct EffectApplyResult
struct EffectDesc
struct SpellDesc
Enumerations
enum EffectType : uint8_t {
EFFECT_NONE ,
EFFECT_SCHOOL_DAMAGE ,
EFFECT_HEALTH_LEECH ,
EFFECT_POWER_DRAIN ,
EFFECT_POWER_BURN ,
EFFECT_NORMALIZED_WEAPON_DMG ,
EFFECT_WEAPON_PERCENT_DAMAGE ,
EFFECT_APPLY_AURA ,
EFFECT_DUMMY
}
enum AuraType : uint8_t {
AURA_NONE ,
AURA_MOD_DECREASE_SPEED ,
AURA_PERIODIC_DAMAGE ,
AURA_TRANSFORM ,
AURA_MOD_STUN
}
Functions
bool IsDamageEffect (EffectType effect)
bool HasOnlyDamageEffects (SpellDesc const &spell)
bool IsStunSpell (SpellDesc const &spell)
bool IsEffectBlockedByStunImmunity (EffectDesc const &effect, bool immuneToStun)
bool IsFullyImmunedByStunImmunity (SpellDesc const &spell, bool immuneToStun)
bool IsBlockedBySchoolImmunity (bool casterFriendly, bool immunityAppliesToFriendly)
SpellMissInfo ComputeSpellHitResult (bool isImmunedToSpell, bool isImmunedToDamage, SpellDesc const &spell, bool immuneToStun=false)
EffectApplyResult ApplyEffectsWithMovementImmunity (SpellDesc const &spell, bool immuneToMovementImpairing)
SpellDesc MakeDamageOnlySpell ()
SpellDesc MakeFrostboltLikeSpell ()
SpellDesc MakeCycloneLikeSpell ()
SpellDesc MakeSlowOnlySpell ()
Enumeration Type Documentation
AuraType
enum anonymous_namespace{SpellImmunityTest.cpp}::AuraType : uint8_t
Enumerator
AURA_NONE
AURA_MOD_DECREASE_SPEED
AURA_PERIODIC_DAMAGE
AURA_TRANSFORM
AURA_MOD_STUN
    {
        AURA_NONE,
        AURA_MOD_DECREASE_SPEED,
        AURA_PERIODIC_DAMAGE,
        AURA_TRANSFORM,
        AURA_MOD_STUN
    };
EffectType
enum anonymous_namespace{SpellImmunityTest.cpp}::EffectType : uint8_t
Enumerator
EFFECT_NONE
EFFECT_SCHOOL_DAMAGE
EFFECT_HEALTH_LEECH
EFFECT_POWER_DRAIN
EFFECT_POWER_BURN
EFFECT_NORMALIZED_WEAPON_DMG
EFFECT_WEAPON_PERCENT_DAMAGE
EFFECT_APPLY_AURA
EFFECT_DUMMY
    {
        EFFECT_NONE,
        EFFECT_SCHOOL_DAMAGE,
        EFFECT_HEALTH_LEECH,
        EFFECT_POWER_DRAIN,
        EFFECT_POWER_BURN,
        EFFECT_NORMALIZED_WEAPON_DMG,
        EFFECT_WEAPON_PERCENT_DAMAGE,
        EFFECT_APPLY_AURA,
        EFFECT_DUMMY
    };
Function Documentation
ApplyEffectsWithMovementImmunity()
EffectApplyResult anonymous_namespace{SpellImmunityTest.cpp}::ApplyEffectsWithMovementImmunity (SpellDesc const & spell, bool immuneToMovementImpairing)
    {
        EffectApplyResult result;
        for (EffectDesc const& e : spell.effects)
        {
            if (e.effect == EFFECT_NONE)
                continue;
            if (IsDamageEffect(e.effect))
                result.damageApplied = true;
            if (e.effect == EFFECT_APPLY_AURA && e.aura == AURA_MOD_DECREASE_SPEED)
            {
                if (!immuneToMovementImpairing)
                    result.slowApplied = true;
            }
        }
        return result;
    }
References anonymous_namespace{SpellImmunityTest.cpp}::EffectDesc::aura, AURA_MOD_DECREASE_SPEED, anonymous_namespace{SpellImmunityTest.cpp}::EffectApplyResult::damageApplied, anonymous_namespace{SpellImmunityTest.cpp}::EffectDesc::effect, EFFECT_APPLY_AURA, EFFECT_NONE, anonymous_namespace{SpellImmunityTest.cpp}::SpellDesc::effects, IsDamageEffect(), and anonymous_namespace{SpellImmunityTest.cpp}::EffectApplyResult::slowApplied.
Referenced by TEST().
ComputeSpellHitResult()
SpellMissInfo anonymous_namespace{SpellImmunityTest.cpp}::ComputeSpellHitResult (bool isImmunedToSpell, bool isImmunedToDamage, SpellDesc const & spell, bool immuneToStun = false)
    {
        // Mirrors current core ordering:
        // 1) full spell immunity check
        // 2) full immunity from mechanic immunity (all effects blocked)
        // 3) damage immunity only for damage-only spells
        if (isImmunedToSpell)
            return SPELL_MISS_IMMUNE;
        if (IsFullyImmunedByStunImmunity(spell, immuneToStun))
            return SPELL_MISS_IMMUNE;
        if (HasOnlyDamageEffects(spell) && isImmunedToDamage)
            return SPELL_MISS_IMMUNE;
        return SPELL_MISS_NONE;
    }
References HasOnlyDamageEffects(), IsFullyImmunedByStunImmunity(), SPELL_MISS_IMMUNE, and SPELL_MISS_NONE.
Referenced by TEST().
HasOnlyDamageEffects()
bool anonymous_namespace{SpellImmunityTest.cpp}::HasOnlyDamageEffects (SpellDesc const & spell)
    {
        bool hasAny = std::ranges::any_of(spell.effects, [](EffectDesc const& effect)
        {
            return effect.effect != EFFECT_NONE;
        });
        return hasAny && std::ranges::all_of(spell.effects, [](EffectDesc const& effect)
        {
            return effect.effect == EFFECT_NONE || IsDamageEffect(effect.effect);
        });
    }
References anonymous_namespace{SpellImmunityTest.cpp}::SpellDesc::effects.
Referenced by ComputeSpellHitResult(), and TEST().
IsBlockedBySchoolImmunity()
bool anonymous_namespace{SpellImmunityTest.cpp}::IsBlockedBySchoolImmunity (bool casterFriendly, bool immunityAppliesToFriendly)
    {
        return !casterFriendly || immunityAppliesToFriendly;
    }
Referenced by TEST().
IsDamageEffect()
bool anonymous_namespace{SpellImmunityTest.cpp}::IsDamageEffect (EffectType effect)
    {
        switch (effect)
        {
            case EFFECT_SCHOOL_DAMAGE:
            case EFFECT_HEALTH_LEECH:
            case EFFECT_POWER_DRAIN:
            case EFFECT_POWER_BURN:
            case EFFECT_NORMALIZED_WEAPON_DMG:
            case EFFECT_WEAPON_PERCENT_DAMAGE:
                return true;
            default:
                return false;
        }
    }
References EFFECT_HEALTH_LEECH, EFFECT_NORMALIZED_WEAPON_DMG, EFFECT_POWER_BURN, EFFECT_POWER_DRAIN, EFFECT_SCHOOL_DAMAGE, and EFFECT_WEAPON_PERCENT_DAMAGE.
Referenced by ApplyEffectsWithMovementImmunity().
IsEffectBlockedByStunImmunity()
bool anonymous_namespace{SpellImmunityTest.cpp}::IsEffectBlockedByStunImmunity (EffectDesc const & effect, bool immuneToStun)
    {
        if (!immuneToStun)
            return false;
        return effect.effect == EFFECT_APPLY_AURA && effect.aura == AURA_MOD_STUN;
    }
References anonymous_namespace{SpellImmunityTest.cpp}::EffectDesc::aura, AURA_MOD_STUN, anonymous_namespace{SpellImmunityTest.cpp}::EffectDesc::effect, and EFFECT_APPLY_AURA.
Referenced by IsFullyImmunedByStunImmunity().
IsFullyImmunedByStunImmunity()
bool anonymous_namespace{SpellImmunityTest.cpp}::IsFullyImmunedByStunImmunity (SpellDesc const & spell, bool immuneToStun)
    {
        bool hasAnyEffect = false;
        for (EffectDesc const& effect : spell.effects)
        {
            if (effect.effect == EFFECT_NONE)
                continue;
            hasAnyEffect = true;
            if (!IsEffectBlockedByStunImmunity(effect, immuneToStun))
                return false;
        }
        return hasAnyEffect;
    }
References anonymous_namespace{SpellImmunityTest.cpp}::EffectDesc::effect, EFFECT_NONE, anonymous_namespace{SpellImmunityTest.cpp}::SpellDesc::effects, and IsEffectBlockedByStunImmunity().
Referenced by ComputeSpellHitResult().
IsStunSpell()
bool anonymous_namespace{SpellImmunityTest.cpp}::IsStunSpell (SpellDesc const & spell)
    {
        return std::ranges::any_of(spell.effects, [](EffectDesc const& effect)
        {
            return effect.effect == EFFECT_APPLY_AURA && effect.aura == AURA_MOD_STUN;
        });
    }
References anonymous_namespace{SpellImmunityTest.cpp}::SpellDesc::effects.
Referenced by TEST().
MakeCycloneLikeSpell()
SpellDesc anonymous_namespace{SpellImmunityTest.cpp}::MakeCycloneLikeSpell ()
    {
        SpellDesc spell;
        spell.effects[0] = { EFFECT_APPLY_AURA, AURA_TRANSFORM };
        return spell;
    }
References AURA_TRANSFORM, EFFECT_APPLY_AURA, and anonymous_namespace{SpellImmunityTest.cpp}::SpellDesc::effects.
Referenced by TEST().
MakeDamageOnlySpell()
SpellDesc anonymous_namespace{SpellImmunityTest.cpp}::MakeDamageOnlySpell ()
    {
        SpellDesc spell;
        spell.effects[0] = { EFFECT_SCHOOL_DAMAGE, AURA_NONE };
        return spell;
    }
References AURA_NONE, EFFECT_SCHOOL_DAMAGE, and anonymous_namespace{SpellImmunityTest.cpp}::SpellDesc::effects.
Referenced by TEST().
MakeFrostboltLikeSpell()
SpellDesc anonymous_namespace{SpellImmunityTest.cpp}::MakeFrostboltLikeSpell ()
    {
        SpellDesc spell;
        spell.effects[0] = { EFFECT_SCHOOL_DAMAGE, AURA_NONE };
        spell.effects[1] = { EFFECT_APPLY_AURA, AURA_MOD_DECREASE_SPEED };
        return spell;
    }
References AURA_MOD_DECREASE_SPEED, AURA_NONE, EFFECT_APPLY_AURA, EFFECT_SCHOOL_DAMAGE, and anonymous_namespace{SpellImmunityTest.cpp}::SpellDesc::effects.
Referenced by TEST().
MakeSlowOnlySpell()
SpellDesc anonymous_namespace{SpellImmunityTest.cpp}::MakeSlowOnlySpell ()
    {
        // represents effects such as Frost Trap or Desecration, which only slow
        SpellDesc spell;
        spell.effects[0] = { EFFECT_APPLY_AURA, AURA_MOD_DECREASE_SPEED };
        return spell;
    }
References AURA_MOD_DECREASE_SPEED, EFFECT_APPLY_AURA, and anonymous_namespace{SpellImmunityTest.cpp}::SpellDesc::effects.
Referenced by TEST().