AzerothCore: azerothcore-wotlk/src/server/scripts/Spells/spells_script_loader.cpp File Reference
spells_script_loader.cpp File Reference
Functions
void AddSC_deathknight_spell_scripts ()
void AddSC_druid_spell_scripts ()
void AddSC_generic_spell_scripts ()
void AddSC_hunter_spell_scripts ()
void AddSC_mage_spell_scripts ()
void AddSC_paladin_spell_scripts ()
void AddSC_priest_spell_scripts ()
void AddSC_rogue_spell_scripts ()
void AddSC_shaman_spell_scripts ()
void AddSC_warlock_spell_scripts ()
void AddSC_warrior_spell_scripts ()
void AddSC_quest_spell_scripts ()
void AddSC_item_spell_scripts ()
void AddSpellsScripts ()
Function Documentation
AddSC_deathknight_spell_scripts()
void AddSC_deathknight_spell_scripts ()
{
    RegisterSpellScript(spell_dk_wandering_plague);
    RegisterSpellScript(spell_dk_raise_ally);
    RegisterSpellScript(spell_dk_raise_ally_trigger);
    RegisterSpellScript(spell_dk_aotd_taunt);
    RegisterSpellAndAuraScriptPair(spell_dk_death_and_decay, spell_dk_death_and_decay_aura);
    RegisterSpellScript(spell_dk_master_of_ghouls);
    RegisterSpellAndAuraScriptPair(spell_dk_chains_of_ice, spell_dk_chains_of_ice_aura);
    RegisterSpellScript(spell_dk_bloodworms);
    RegisterSpellScript(spell_dk_summon_gargoyle);
    RegisterSpellScript(spell_dk_improved_blood_presence_triggered);
    RegisterSpellScript(spell_dk_wandering_plague_aura);
    RegisterSpellScript(spell_dk_rune_of_the_fallen_crusader);
    RegisterSpellScript(spell_dk_bone_shield);
    RegisterSpellScript(spell_dk_hungering_cold);
    RegisterSpellScript(spell_dk_blood_caked_blade);
    RegisterSpellScript(spell_dk_dancing_rune_weapon);
    RegisterSpellScript(spell_dk_dancing_rune_weapon_visual);
    RegisterSpellScript(spell_dk_scent_of_blood_trigger);
    RegisterSpellScript(spell_dk_pet_scaling);
    RegisterSpellScript(spell_dk_acclimation);
    RegisterSpellScript(spell_dk_advantage_t10_4p);
    RegisterSpellScript(spell_dk_anti_magic_shell_raid);
    RegisterSpellScript(spell_dk_anti_magic_shell_self);
    RegisterSpellScript(spell_dk_anti_magic_zone);
    RegisterSpellScript(spell_dk_blood_boil);
    RegisterSpellScript(spell_dk_blood_gorged);
    RegisterSpellScript(spell_dk_corpse_explosion);
    RegisterSpellScript(spell_dk_death_coil);
    RegisterSpellScript(spell_dk_death_gate);
    RegisterSpellScript(spell_dk_death_grip);
    RegisterSpellScript(spell_dk_death_pact);
    RegisterSpellScript(spell_dk_death_strike);
    RegisterSpellScript(spell_dk_ghoul_explode);
    RegisterSpellScript(spell_dk_icebound_fortitude);
    RegisterSpellScript(spell_dk_improved_blood_presence);
    RegisterSpellScript(spell_dk_improved_frost_presence);
    RegisterSpellScript(spell_dk_improved_unholy_presence);
    RegisterSpellScript(spell_dk_pestilence);
    RegisterSpellScript(spell_dk_presence);
    RegisterSpellScript(spell_dk_raise_dead);
    RegisterSpellScript(spell_dk_rune_tap_party);
    RegisterSpellScript(spell_dk_scent_of_blood);
    RegisterSpellScript(spell_dk_scourge_strike);
    RegisterSpellScript(spell_dk_spell_deflection);
    RegisterSpellScript(spell_dk_vampiric_blood);
    RegisterSpellScript(spell_dk_will_of_the_necropolis);
    RegisterSpellScript(spell_dk_ghoul_thrash);
    RegisterSpellScript(spell_dk_army_of_the_dead_passive);
    // Proc system scripts
    RegisterSpellScript(spell_dk_butchery);
    RegisterSpellScript(spell_dk_mark_of_blood);
    RegisterSpellScript(spell_dk_unholy_blight);
    RegisterSpellScript(spell_dk_vendetta);
    RegisterSpellScript(spell_dk_necrosis);
    RegisterSpellScript(spell_dk_blade_barrier);
    RegisterSpellScript(spell_dk_death_rune);
    RegisterSpellScript(spell_dk_rime);
    RegisterSpellScript(spell_dk_killing_machine);
    RegisterSpellScript(spell_dk_sudden_doom);
    RegisterSpellScript(spell_dk_threat_of_thassarian);
    RegisterSpellScript(spell_dk_glyph_of_death_grip);
    RegisterSpellScript(spell_dk_glyph_of_scourge_strike);
    RegisterSpellScript(spell_dk_glyph_of_scourge_strike_script);
    RegisterSpellScript(spell_dk_pvp_4p_bonus);
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddSpellsScripts().
AddSC_druid_spell_scripts()
void AddSC_druid_spell_scripts ()
{
    RegisterSpellScript(spell_dru_bear_form_passive);
    RegisterSpellScript(spell_dru_t10_balance_4p_bonus);
    RegisterSpellScript(spell_dru_nurturing_instinct);
    RegisterSpellScript(spell_dru_feral_swiftness);
    RegisterSpellScript(spell_dru_omen_of_clarity);
    RegisterSpellScript(spell_dru_brambles_treant);
    RegisterSpellScript(spell_dru_barkskin);
    RegisterSpellScript(spell_dru_glyph_of_barkskin);
    RegisterSpellScript(spell_dru_treant_scaling);
    RegisterSpellScript(spell_dru_berserk);
    RegisterSpellAndAuraScriptPair(spell_dru_dash, spell_dru_dash_aura);
    RegisterSpellScript(spell_dru_enrage);
    RegisterSpellScript(spell_dru_glyph_of_starfire);
    RegisterSpellScript(spell_dru_idol_lifebloom);
    RegisterSpellScript(spell_dru_innervate);
    RegisterSpellScript(spell_dru_lifebloom);
    RegisterSpellScript(spell_dru_living_seed);
    RegisterSpellScript(spell_dru_living_seed_proc);
    RegisterSpellScript(spell_dru_moonkin_form_passive);
    RegisterSpellScript(spell_dru_owlkin_frenzy);
    RegisterSpellScript(spell_dru_predatory_strikes);
    RegisterSpellScript(spell_dru_primal_tenacity);
    RegisterSpellScript(spell_dru_rip);
    RegisterSpellScript(spell_dru_savage_defense);
    RegisterSpellAndAuraScriptPair(spell_dru_savage_roar, spell_dru_savage_roar_aura);
    RegisterSpellScript(spell_dru_starfall_aoe);
    RegisterSpellScript(spell_dru_starfall_dummy);
    RegisterSpellAndAuraScriptPair(spell_dru_survival_instincts, spell_dru_survival_instincts_aura);
    RegisterSpellScript(spell_dru_swift_flight_passive);
    RegisterSpellScript(spell_dru_tiger_s_fury);
    RegisterSpellScript(spell_dru_typhoon);
    RegisterSpellScript(spell_dru_t10_restoration_4p_bonus);
    RegisterSpellAndAuraScriptPair(spell_dru_wild_growth, spell_dru_wild_growth_aura);
    RegisterSpellScript(spell_dru_moonkin_form_passive_proc);
    RegisterSpellScript(spell_dru_rejuvenation_moonglade_2_set);
    // Proc system scripts
    RegisterSpellScript(spell_dru_glyph_of_innervate);
    RegisterSpellScript(spell_dru_glyph_of_rake);
    RegisterSpellScript(spell_dru_leader_of_the_pack);
    RegisterSpellScript(spell_dru_glyph_of_rejuvenation);
    RegisterSpellScript(spell_dru_eclipse);
    RegisterSpellScript(spell_dru_revitalize);
    RegisterSpellScript(spell_dru_t3_2p_bonus);
    RegisterSpellScript(spell_dru_t3_6p_bonus);
    RegisterSpellScript(spell_dru_t3_8p_bonus);
    RegisterSpellScript(spell_dru_t4_2p_bonus);
    RegisterSpellScript(spell_dru_item_t6_trinket);
    RegisterSpellScript(spell_dru_glyph_of_shred);
    RegisterSpellScript(spell_dru_glyph_of_starfire_dummy);
    RegisterSpellScript(spell_dru_t10_restoration_4p_bonus_dummy);
    RegisterSpellScript(spell_dru_maim_interrupt);
    RegisterSpellScript(spell_dru_t9_feral_relic);
    RegisterSpellScript(spell_dru_frenzied_regeneration);
    RegisterSpellScript(spell_dru_insect_swarm);
    RegisterSpellScript(spell_dru_nourish);
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddSpellsScripts().
AddSC_generic_spell_scripts()
void AddSC_generic_spell_scripts ()
{
    RegisterSpellScript(spell_silithyst);
    RegisterSpellScript(spell_gen_5000_gold);
    RegisterSpellScript(spell_gen_arena_drink);
    RegisterSpellScript(spell_gen_model_visible);
    RegisterSpellScript(spell_the_flag_of_ownership);
    RegisterSpellScript(spell_gen_have_item_auras);
    RegisterSpellScript(spell_gen_mine_sweeper);
    RegisterSpellAndAuraScriptPair(spell_gen_reduced_above_60, spell_gen_reduced_above_60_aura);
    RegisterSpellScriptWithArgs(spell_gen_relocaste_dest, "spell_q10838_demoniac_scryer_visual", 0, 0, 20.0, 0);
    RegisterSpellScriptWithArgs(spell_gen_relocaste_dest, "spell_q20438_q24556_aquantos_laundry", 0, 0, 7.0f, 0);
    RegisterSpellScript(spell_gen_allow_proc_from_spells_with_cost);
    RegisterSpellScript(spell_gen_bg_preparation);
    RegisterSpellScriptWithArgs(spell_gen_disabled_above_level, "spell_gen_disabled_above_73", 73);
    RegisterSpellScriptWithArgs(spell_gen_disabled_above_level, "spell_gen_disabled_above_70", 70);
    RegisterSpellScript(spell_pet_hit_expertise_scalling);
    RegisterSpellScript(spell_gen_grow_flower_patch);
    RegisterSpellScript(spell_gen_rallying_cry_of_the_dragonslayer);
    RegisterSpellScript(spell_gen_disabled_above_63);
    RegisterSpellScript(spell_gen_black_magic_enchant);
    RegisterSpellScript(spell_gen_area_aura_select_players);
    RegisterSpellScript(spell_gen_area_aura_select_players_and_caster);
    RegisterSpellScriptWithArgs(spell_gen_select_target_count, "spell_gen_select_target_count_15_1", TARGET_UNIT_SRC_AREA_ENEMY, 1);
    RegisterSpellScriptWithArgs(spell_gen_select_target_count, "spell_gen_select_target_count_15_2", TARGET_UNIT_SRC_AREA_ENEMY, 2);
    RegisterSpellScriptWithArgs(spell_gen_select_target_count, "spell_gen_select_target_count_15_3", TARGET_UNIT_SRC_AREA_ENEMY, 3);
    RegisterSpellScriptWithArgs(spell_gen_select_target_count, "spell_gen_select_target_count_15_5", TARGET_UNIT_SRC_AREA_ENEMY, 5);
    RegisterSpellScriptWithArgs(spell_gen_select_target_count, "spell_gen_select_target_count_7_1", TARGET_UNIT_SRC_AREA_ENTRY, 1);
    RegisterSpellScriptWithArgs(spell_gen_select_target_count, "spell_gen_select_target_count_24_1", TARGET_UNIT_CONE_ENEMY_24, 1);
    RegisterSpellScriptWithArgs(spell_gen_select_target_count, "spell_gen_select_target_count_30_1", TARGET_UNIT_SRC_AREA_ALLY, 1);
    RegisterSpellScriptWithArgs(spell_gen_select_target_count, "spell_gen_select_target_count_15_4", TARGET_UNIT_SRC_AREA_ENEMY, 4);
    RegisterSpellScript(spell_gen_use_spell_base_level_check);
    RegisterSpellScript(spell_gen_proc_from_direct_damage);
    RegisterSpellScript(spell_gen_no_offhand_proc);
    RegisterSpellScript(spell_gen_proc_on_self);
    RegisterSpellScript(spell_gen_proc_not_self);
    RegisterSpellScript(spell_gen_baby_murloc_passive);
    RegisterSpellScript(spell_gen_baby_murloc);
    RegisterSpellAndAuraScriptPair(spell_gen_fixate, spell_gen_fixate_aura);
    RegisterSpellScript(spell_gen_proc_above_75);
    RegisterSpellScript(spell_gen_periodic_knock_away);
    RegisterSpellScript(spell_gen_knock_away);
    RegisterSpellScript(spell_gen_mod_radius_by_caster_scale);
    RegisterSpellScript(spell_gen_proc_reduced_above_60);
    RegisterSpellScript(spell_gen_visual_dummy_stun);
    RegisterSpellScript(spell_gen_random_target32);
    RegisterSpellScript(spell_gen_hate_to_zero);
    RegisterSpellScript(spell_gen_focused_bursts);
    RegisterSpellScript(spell_gen_flurry_of_claws);
    RegisterSpellScript(spell_gen_throw_back);
    RegisterSpellAndAuraScriptPair(spell_gen_haunted, spell_gen_haunted_aura);
    RegisterSpellScript(spell_gen_absorb0_hitlimit1);
    RegisterSpellScript(spell_gen_adaptive_warding);
    RegisterSpellScript(spell_gen_av_drekthar_presence);
    RegisterSpellScript(spell_gen_burn_brutallus);
    RegisterSpellScript(spell_gen_cannibalize);
    RegisterSpellScript(spell_gen_clear_debuffs);
    RegisterSpellScript(spell_gen_create_lance);
    RegisterSpellScript(spell_gen_netherbloom);
    RegisterSpellScript(spell_gen_nightmare_vine);
    RegisterSpellScript(spell_gen_obsidian_armor);
    RegisterSpellScript(spell_gen_parachute);
    RegisterSpellScript(spell_gen_pet_summoned);
    RegisterSpellScript(spell_gen_remove_flight_auras);
    RegisterSpellScript(spell_gen_feign_death_all_flags);
    RegisterSpellScript(spell_gen_feign_death_no_dyn_flag);
    RegisterSpellScript(spell_gen_feign_death_no_prevent_emotes);
    RegisterSpellScript(spell_pvp_trinket_wotf_shared_cd);
    RegisterSpellScript(spell_gen_animal_blood);
    RegisterSpellScript(spell_spawn_blood_pool);
    RegisterSpellScript(spell_gen_divine_storm_cd_reset);
    RegisterSpellScript(spell_gen_profession_research);
    RegisterSpellScript(spell_gen_clone);
    RegisterSpellScript(spell_gen_clone_weapon);
    RegisterSpellScript(spell_gen_clone_weapon_aura);
    RegisterSpellScript(spell_gen_seaforium_blast);
    RegisterSpellScript(spell_gen_turkey_marker);
    RegisterSpellScript(spell_gen_lifeblood);
    RegisterSpellScript(spell_gen_allow_cast_from_item_only);
    RegisterSpellAndAuraScriptPair(spell_gen_vehicle_scaling, spell_gen_vehicle_scaling_aura);
    RegisterSpellScript(spell_gen_oracle_wolvar_reputation);
    RegisterSpellScript(spell_gen_damage_reduction_aura);
    RegisterSpellScript(spell_gen_dummy_trigger);
    RegisterSpellScript(spell_gen_spirit_healer_res);
    RegisterSpellScript(spell_gen_gadgetzan_transporter_backfire);
    RegisterSpellScript(spell_gen_gnomish_transporter);
    RegisterSpellScript(spell_gen_gryphon_wyvern_mount_check);
    RegisterSpellScriptWithArgs(spell_gen_dalaran_disguise, "spell_gen_sunreaver_disguise");
    RegisterSpellScriptWithArgs(spell_gen_dalaran_disguise, "spell_gen_silver_covenant_disguise");
    RegisterSpellScript(spell_gen_elune_candle);
    RegisterSpellScriptWithArgs(spell_gen_break_shield, "spell_gen_break_shield");
    RegisterSpellScriptWithArgs(spell_gen_break_shield, "spell_gen_tournament_counterattack");
    RegisterSpellScript(spell_gen_mounted_charge);
    RegisterSpellScript(spell_gen_moss_covered_feet);
    RegisterSpellScript(spell_gen_defend);
    RegisterSpellScript(spell_gen_tournament_duel);
    RegisterSpellScript(spell_gen_summon_tournament_mount);
    RegisterSpellScript(spell_gen_throw_shield);
    RegisterSpellScript(spell_gen_on_tournament_mount);
    RegisterSpellScript(spell_gen_tournament_pennant);
    RegisterSpellScript(spell_gen_teleporting);
    RegisterSpellScript(spell_gen_ds_flush_knockback);
    RegisterSpellScriptWithArgs(spell_gen_count_pct_from_max_hp, "spell_gen_default_count_pct_from_max_hp");
    RegisterSpellScriptWithArgs(spell_gen_count_pct_from_max_hp, "spell_gen_10pct_count_pct_from_max_hp", 10);
    RegisterSpellScriptWithArgs(spell_gen_count_pct_from_max_hp, "spell_gen_50pct_count_pct_from_max_hp", 50);
    RegisterSpellScriptWithArgs(spell_gen_count_pct_from_max_hp, "spell_gen_26pct_count_pct_from_max_hp", 26);
    RegisterSpellScript(spell_gen_despawn_self);
    RegisterSpellScript(spell_gen_bandage);
    RegisterSpellScript(spell_gen_paralytic_poison);
    RegisterSpellScript(spell_gen_prevent_emotes);
    RegisterSpellScript(spell_gen_blade_warding);
    RegisterSpellScriptWithArgs(spell_gen_lifebloom, "spell_hexlord_lifebloom", SPELL_HEXLORD_MALACRASS_LIFEBLOOM_FINAL_HEAL);
    RegisterSpellScriptWithArgs(spell_gen_lifebloom, "spell_tur_ragepaw_lifebloom", SPELL_TUR_RAGEPAW_LIFEBLOOM_FINAL_HEAL);
    RegisterSpellScriptWithArgs(spell_gen_lifebloom, "spell_cenarion_scout_lifebloom", SPELL_CENARION_SCOUT_LIFEBLOOM_FINAL_HEAL);
    RegisterSpellScriptWithArgs(spell_gen_lifebloom, "spell_twisted_visage_lifebloom", SPELL_TWISTED_VISAGE_LIFEBLOOM_FINAL_HEAL);
    RegisterSpellScriptWithArgs(spell_gen_lifebloom, "spell_faction_champion_dru_lifebloom", SPELL_FACTION_CHAMPIONS_DRU_LIFEBLOOM_FINAL_HEAL);
    RegisterSpellScriptWithArgs(spell_gen_summon_elemental, "spell_gen_summon_fire_elemental", SPELL_SUMMON_FIRE_ELEMENTAL);
    RegisterSpellScriptWithArgs(spell_gen_summon_elemental, "spell_gen_summon_earth_elemental", SPELL_SUMMON_EARTH_ELEMENTAL);
    RegisterSpellScriptWithArgs(spell_gen_mount, "spell_big_blizzard_bear", 0, SPELL_BIG_BLIZZARD_BEAR_60, SPELL_BIG_BLIZZARD_BEAR_100, SPELL_BIG_BLIZZARD_BEAR_150, SPELL_BIG_BLIZZARD_BEAR_280, SPELL_BIG_BLIZZARD_BEAR_310);
    RegisterSpellScriptWithArgs(spell_gen_mount, "spell_magic_broom", 0, SPELL_MAGIC_BROOM_60, SPELL_MAGIC_BROOM_100, SPELL_MAGIC_BROOM_150, SPELL_MAGIC_BROOM_280, 0);
    RegisterSpellScriptWithArgs(spell_gen_mount, "spell_headless_horseman_mount", 0, SPELL_HEADLESS_HORSEMAN_MOUNT_60, SPELL_HEADLESS_HORSEMAN_MOUNT_100, SPELL_HEADLESS_HORSEMAN_MOUNT_150, SPELL_HEADLESS_HORSEMAN_MOUNT_280, 0);
    RegisterSpellScriptWithArgs(spell_gen_mount, "spell_winged_steed_of_the_ebon_blade", 0, 0, 0, SPELL_WINGED_STEED_150, SPELL_WINGED_STEED_280, 0);
    RegisterSpellScriptWithArgs(spell_gen_mount, "spell_big_love_rocket", SPELL_BIG_LOVE_ROCKET_0, SPELL_BIG_LOVE_ROCKET_60, SPELL_BIG_LOVE_ROCKET_100, SPELL_BIG_LOVE_ROCKET_150, SPELL_BIG_LOVE_ROCKET_310, 0);
    RegisterSpellScriptWithArgs(spell_gen_mount, "spell_invincible", 0, SPELL_INVINCIBLE_60, SPELL_INVINCIBLE_100, SPELL_INVINCIBLE_150, SPELL_INVINCIBLE_310, 0);
    RegisterSpellScriptWithArgs(spell_gen_mount, "spell_blazing_hippogryph", 0, 0, 0, SPELL_BLAZING_HIPPOGRYPH_150, SPELL_BLAZING_HIPPOGRYPH_280, 0);
    RegisterSpellScriptWithArgs(spell_gen_mount, "spell_celestial_steed", 0, SPELL_CELESTIAL_STEED_60, SPELL_CELESTIAL_STEED_100, SPELL_CELESTIAL_STEED_150, SPELL_CELESTIAL_STEED_280, SPELL_CELESTIAL_STEED_310);
    RegisterSpellScriptWithArgs(spell_gen_mount, "spell_x53_touring_rocket", 0, 0, 0, SPELL_X53_TOURING_ROCKET_150, SPELL_X53_TOURING_ROCKET_280, SPELL_X53_TOURING_ROCKET_310);
    RegisterSpellScript(spell_gen_upper_deck_create_foam_sword);
    RegisterSpellScript(spell_gen_bonked);
    RegisterSpellScript(spell_gen_gift_of_naaru);
    RegisterSpellAndAuraScriptPair(spell_gen_replenishment, spell_gen_replenishment_aura);
    RegisterSpellScript(spell_gen_spectator_cheer_trigger);
    RegisterSpellScript(spell_gen_vendor_bark_trigger);
    RegisterSpellScript(spell_gen_whisper_gulch_yogg_saron_whisper);
    RegisterSpellScript(spell_gen_eject_all_passengers);
    RegisterSpellScript(spell_gen_eject_passenger);
    RegisterSpellScript(spell_gen_charmed_unit_spell_cooldown);
    RegisterSpellScript(spell_contagion_of_rot);
    RegisterSpellScript(spell_gen_holiday_buff_food);
    RegisterSpellScript(spell_gen_arcane_charge);
    RegisterSpellScript(spell_gen_remove_impairing_auras);
    RegisterSpellScriptWithArgs(spell_gen_consume, "spell_consume_aq20", SPELL_CONSUME_LEECH_AQ20, SPELL_CONSUME_LEECH_HEAL_AQ20);
    RegisterSpellScriptWithArgs(spell_gen_apply_aura_after_expiration, "spell_itch_aq20", SPELL_HIVEZARA_CATALYST, EFFECT_0, SPELL_AURA_DUMMY);
    RegisterSpellScriptWithArgs(spell_gen_apply_aura_after_expiration, "spell_itch_aq40", SPELL_VEKNISS_CATALYST, EFFECT_0, SPELL_AURA_DUMMY);
    RegisterSpellScript(spell_gen_basic_campfire);
    RegisterSpellScript(spell_freezing_circle);
    RegisterSpellScript(spell_gen_threshalisk_charge);
    RegisterSpellScript(spell_gen_shriveling_gaze);
    RegisterSpellScript(spell_gen_curse_of_pain);
    RegisterSpellScript(spell_gen_spirit_of_competition_participant);
    RegisterSpellScript(spell_gen_spirit_of_competition_winner);
    RegisterSpellScript(spell_gen_valthalak_amulet);
    RegisterSpellScript(spell_gen_planting_scourge_banner);
    RegisterSpellScript(spell_gen_jubling_cooldown);
    RegisterSpellScript(spell_gen_yehkinya_bramble);
    RegisterSpellScript(spell_gen_choking_vines);
    RegisterSpellScript(spell_gen_consumption);
    RegisterSpellScript(spell_gen_sober_up);
    RegisterSpellScript(spell_gen_steal_weapon);
    RegisterSpellScript(spell_gen_set_health);
    RegisterSpellScript(spell_pet_intellect_spirit_resilience_scaling);
    RegisterSpellScript(spell_pet_spellhit_expertise_spellpen_scaling);
    RegisterSpellScript(spell_gen_proc_on_victim);
    RegisterSpellScriptWithArgs(spell_gen_translocate, "spell_gen_translocate_down", SPELL_TRANSLOCATION_DOWN);
    RegisterSpellScriptWithArgs(spell_gen_translocate, "spell_gen_translocate_up", SPELL_TRANSLOCATION_UP);
    RegisterSpellScript(spell_gen_cooldown_all);
    RegisterSpellScript(spell_gen_food_heart_emote);
    RegisterSpellScript(spell_gen_showlabel_off);
    RegisterSpellScript(spell_gen_showlabel_on);
    RegisterSpellScript(spell_gen_gm_off);
    RegisterSpellScript(spell_gen_gm_on);
    RegisterSpellScript(spell_gen_invis_off);
    RegisterSpellScript(spell_gen_invis_on);
    RegisterSpellScript(spell_gen_bm_on);
    RegisterSpellScript(spell_gen_bm_off);
    RegisterSpellScript(spell_gen_whisper_to_controller);
    RegisterSpellScript(spell_gen_vampiric_touch);
    // Boss and item proc scripts
    RegisterSpellScript(spell_gen_petrified_bark);
    RegisterSpellScript(spell_gen_earth_shield_toc);
    RegisterSpellScript(spell_gen_retaliation_toc);
    RegisterSpellScript(spell_gen_overlords_brand);
    RegisterSpellScript(spell_gen_overlords_brand_dot);
    RegisterSpellScript(spell_gen_vampiric_might);
    RegisterSpellScript(spell_gen_mirrored_soul);
    RegisterSpellScript(spell_gen_black_bow_of_the_betrayer);
    RegisterSpellScript(spell_gen_filter_party_level_80);
}
References EFFECT_0, RegisterSpellAndAuraScriptPair, RegisterSpellScript, RegisterSpellScriptWithArgs, SPELL_AURA_DUMMY, SPELL_BIG_BLIZZARD_BEAR_100, SPELL_BIG_BLIZZARD_BEAR_150, SPELL_BIG_BLIZZARD_BEAR_280, SPELL_BIG_BLIZZARD_BEAR_310, SPELL_BIG_BLIZZARD_BEAR_60, SPELL_BIG_LOVE_ROCKET_0, SPELL_BIG_LOVE_ROCKET_100, SPELL_BIG_LOVE_ROCKET_150, SPELL_BIG_LOVE_ROCKET_310, SPELL_BIG_LOVE_ROCKET_60, SPELL_BLAZING_HIPPOGRYPH_150, SPELL_BLAZING_HIPPOGRYPH_280, SPELL_CELESTIAL_STEED_100, SPELL_CELESTIAL_STEED_150, SPELL_CELESTIAL_STEED_280, SPELL_CELESTIAL_STEED_310, SPELL_CELESTIAL_STEED_60, SPELL_CENARION_SCOUT_LIFEBLOOM_FINAL_HEAL, SPELL_CONSUME_LEECH_AQ20, SPELL_CONSUME_LEECH_HEAL_AQ20, SPELL_FACTION_CHAMPIONS_DRU_LIFEBLOOM_FINAL_HEAL, SPELL_HEADLESS_HORSEMAN_MOUNT_100, SPELL_HEADLESS_HORSEMAN_MOUNT_150, SPELL_HEADLESS_HORSEMAN_MOUNT_280, SPELL_HEADLESS_HORSEMAN_MOUNT_60, SPELL_HEXLORD_MALACRASS_LIFEBLOOM_FINAL_HEAL, SPELL_HIVEZARA_CATALYST, SPELL_INVINCIBLE_100, SPELL_INVINCIBLE_150, SPELL_INVINCIBLE_310, SPELL_INVINCIBLE_60, SPELL_MAGIC_BROOM_100, SPELL_MAGIC_BROOM_150, SPELL_MAGIC_BROOM_280, SPELL_MAGIC_BROOM_60, SPELL_SUMMON_EARTH_ELEMENTAL, SPELL_SUMMON_FIRE_ELEMENTAL, SPELL_TRANSLOCATION_DOWN, SPELL_TRANSLOCATION_UP, SPELL_TUR_RAGEPAW_LIFEBLOOM_FINAL_HEAL, SPELL_TWISTED_VISAGE_LIFEBLOOM_FINAL_HEAL, SPELL_VEKNISS_CATALYST, SPELL_WINGED_STEED_150, SPELL_WINGED_STEED_280, SPELL_X53_TOURING_ROCKET_150, SPELL_X53_TOURING_ROCKET_280, SPELL_X53_TOURING_ROCKET_310, TARGET_UNIT_CONE_ENEMY_24, TARGET_UNIT_SRC_AREA_ALLY, TARGET_UNIT_SRC_AREA_ENEMY, and TARGET_UNIT_SRC_AREA_ENTRY.
Referenced by AddSpellsScripts().
AddSC_hunter_spell_scripts()
void AddSC_hunter_spell_scripts ()
{
    RegisterSpellScript(spell_hun_check_pet_los);
    RegisterSpellScript(spell_hun_cower);
    RegisterSpellScript(spell_hun_wyvern_sting);
    RegisterSpellScript(spell_hun_animal_handler);
    RegisterSpellScript(spell_hun_generic_scaling);
    RegisterSpellScript(spell_hun_taming_the_beast);
    RegisterSpellScript(spell_hun_glyph_of_arcane_shot);
    RegisterSpellScript(spell_hun_aspect_of_the_beast);
    RegisterSpellScript(spell_hun_ascpect_of_the_viper);
    RegisterSpellScript(spell_hun_chimera_shot);
    RegisterSpellScript(spell_hun_cobra_strikes);
    RegisterSpellScript(spell_hun_cobra_strikes_triggered);
    RegisterSpellScript(spell_hun_disengage);
    RegisterSpellScript(spell_hun_improved_mend_pet);
    RegisterSpellScript(spell_hun_invigoration);
    RegisterSpellScript(spell_hun_last_stand_pet);
    RegisterSpellScript(spell_hun_masters_call);
    RegisterSpellScript(spell_hun_misdirection);
    RegisterSpellScript(spell_hun_misdirection_proc);
    RegisterSpellScript(spell_hun_pet_carrion_feeder);
    RegisterSpellScript(spell_hun_pet_heart_of_the_phoenix);
    RegisterSpellScript(spell_hun_readiness);
    RegisterSpellScript(spell_hun_scatter_shot);
    RegisterSpellScript(spell_hun_sniper_training);
    RegisterSpellScript(spell_hun_tame_beast);
    RegisterSpellScript(spell_hun_viper_attack_speed);
    RegisterSpellScript(spell_hun_volley_trigger);
    RegisterSpellScript(spell_hun_lock_and_load);
    RegisterSpellScript(spell_hun_intimidation);
    RegisterSpellScript(spell_hun_bestial_wrath);
    RegisterSpellScript(spell_hun_target_self_and_pet);
    RegisterSpellScript(spell_hun_explosive_shot);
    RegisterSpellScript(spell_hun_thrill_of_the_hunt);
    RegisterSpellScript(spell_hun_hunting_party);
    RegisterSpellScript(spell_hun_glyph_of_mend_pet);
    // Proc system scripts
    RegisterSpellScript(spell_hun_rapid_recuperation);
    RegisterSpellScript(spell_hun_kill_command);
    RegisterSpellScript(spell_hun_kill_command_pet);
    RegisterSpellScript(spell_hun_piercing_shots);
    RegisterSpellScript(spell_hun_rapid_recuperation_trigger);
    RegisterSpellScript(spell_hun_t9_4p_bonus);
}
References RegisterSpellScript.
Referenced by AddSpellsScripts().
AddSC_item_spell_scripts()
void AddSC_item_spell_scripts ()
{
    RegisterSpellScript(spell_item_massive_seaforium_charge);
    RegisterSpellScript(spell_item_titanium_seal_of_dalaran);
    RegisterSpellScript(spell_item_mind_amplify_dish);
    RegisterSpellScript(spell_item_runescroll_of_fortitude);
    RegisterSpellScript(spell_item_branns_communicator);
    RegisterSpellScript(spell_item_goblin_gumbo_kettle);
    RegisterSpellScript(spell_item_with_mount_speed);
    RegisterSpellScript(spell_item_magic_dust);
    RegisterSpellScript(spell_item_toy_train_set);
    RegisterSpellScript(spell_item_rocket_chicken);
    RegisterSpellScript(spell_item_sleepy_willy);
    RegisterSpellScript(spell_item_lil_phylactery);
    RegisterSpellScript(spell_item_shifting_naaru_silver);
    RegisterSpellScript(spell_item_toxic_wasteling);
    RegisterSpellScript(spell_item_lil_xt);
    RegisterSpellScript(spell_item_essence_of_life);
    RegisterSpellScript(spell_item_skull_of_impeding_doom);
    RegisterSpellScript(spell_item_feast);
    RegisterSpellScript(spell_item_gnomish_universal_remote);
    RegisterSpellScript(spell_item_powerful_anti_venom);
    RegisterSpellScript(spell_item_strong_anti_venom);
    RegisterSpellScript(spell_item_anti_venom);
    RegisterSpellScript(spell_item_gnomish_shrink_ray);
    RegisterSpellScript(spell_item_goblin_weather_machine);
    RegisterSpellScript(spell_item_goblin_weather_machine_aura);
    RegisterSpellScript(spell_item_light_lamp);
    RegisterSpellScript(spell_item_fetch_ball);
    RegisterSpellScript(spell_item_oracle_ablutions);
    RegisterSpellScript(spell_item_trauma);
    RegisterSpellScript(spell_item_blood_draining_enchant);
    RegisterSpellScript(spell_item_dragon_kite_summon_lightning_bunny);
    RegisterSpellScript(spell_item_enchanted_broom_periodic);
    RegisterSpellScript(spell_item_summon_or_dismiss);
    RegisterSpellScript(spell_item_draenic_pale_ale);
    RegisterSpellAndAuraScriptPair(spell_item_direbrew_remote, spell_item_direbrew_remote_aura);
    RegisterSpellScript(spell_item_healing_trance);
    RegisterSpellScript(spell_item_summon_argent_knight);
    RegisterSpellScript(spell_item_instant_statue);
    // 23074 Arcanite Dragonling
    RegisterSpellScriptWithArgs(spell_item_trigger_spell, "spell_item_arcanite_dragonling", SPELL_ARCANITE_DRAGONLING);
    // 23133 Gnomish Battle Chicken
    RegisterSpellScriptWithArgs(spell_item_trigger_spell, "spell_item_gnomish_battle_chicken", SPELL_BATTLE_CHICKEN);
    // 23076 Mechanical Dragonling
    RegisterSpellScriptWithArgs(spell_item_trigger_spell, "spell_item_mechanical_dragonling", SPELL_MECHANICAL_DRAGONLING);
    // 23075 Mithril Mechanical Dragonling
    RegisterSpellScriptWithArgs(spell_item_trigger_spell, "spell_item_mithril_mechanical_dragonling", SPELL_MITHRIL_MECHANICAL_DRAGONLING);
    RegisterSpellScript(spell_item_aegis_of_preservation);
    RegisterSpellScript(spell_item_arcane_shroud);
    RegisterSpellScript(spell_item_brittle_armor);
    RegisterSpellScript(spell_item_blessing_of_ancient_kings);
    RegisterSpellScript(spell_item_valanyr_hammer_of_ancient_kings);
    RegisterSpellScriptWithArgs(spell_item_defibrillate, "spell_item_goblin_jumper_cables", 67, SPELL_GOBLIN_JUMPER_CABLES_FAIL);
    RegisterSpellScriptWithArgs(spell_item_defibrillate, "spell_item_goblin_jumper_cables_xl", 50, SPELL_GOBLIN_JUMPER_CABLES_XL_FAIL);
    RegisterSpellScriptWithArgs(spell_item_defibrillate, "spell_item_gnomish_army_knife", 33);
    RegisterSpellScript(spell_item_desperate_defense);
    RegisterSpellScript(spell_item_deviate_fish);
    RegisterSpellScript(spell_item_party_time);
    RegisterSpellScript(spell_item_echoes_of_light);
    RegisterSpellScript(spell_item_fate_rune_of_unsurpassed_vigor);
    RegisterSpellScript(spell_item_flask_of_the_north);
    RegisterSpellScript(spell_item_gnomish_death_ray);
    RegisterSpellScript(spell_item_make_a_wish);
    RegisterSpellScript(spell_item_mercurial_shield);
    RegisterSpellScript(spell_item_mingos_fortune_generator);
    RegisterSpellScript(spell_item_necrotic_touch);
    RegisterSpellScript(spell_item_net_o_matic);
    RegisterSpellScript(spell_item_noggenfogger_elixir);
    RegisterSpellScript(spell_item_piccolo_of_the_flaming_fire);
    RegisterSpellScript(spell_item_savory_deviate_delight);
    RegisterSpellScript(spell_item_scroll_of_recall);
    RegisterSpellScript(spell_item_dimensional_ripper_area52);
    RegisterSpellScript(spell_item_unsated_craving);
    RegisterSpellScript(spell_item_shadows_fate);
    RegisterSpellScript(spell_item_shadowmourne);
    RegisterSpellScript(spell_item_shadowmourne_soul_fragment);
    RegisterSpellScript(spell_item_six_demon_bag);
    RegisterSpellScript(spell_item_the_eye_of_diminution);
    RegisterSpellScript(spell_item_underbelly_elixir);
    RegisterSpellScript(spell_item_book_of_glyph_mastery);
    RegisterSpellScript(spell_item_map_of_the_geyser_fields);
    RegisterSpellScript(spell_item_vanquished_clutches);
    RegisterSpellScript(spell_item_ashbringer);
    RegisterSpellScript(spell_magic_eater_food);
    RegisterSpellScript(spell_item_refocus);
    RegisterSpellScript(spell_item_shimmering_vessel);
    RegisterSpellScript(spell_item_purify_helboar_meat);
    RegisterSpellScript(spell_item_reindeer_transformation);
    RegisterSpellScript(spell_item_nigh_invulnerability);
    RegisterSpellScript(spell_item_poultryizer);
    RegisterSpellScript(spell_item_socrethars_stone);
    RegisterSpellScript(spell_item_demon_broiled_surprise);
    RegisterSpellScript(spell_item_complete_raptor_capture);
    RegisterSpellScript(spell_item_impale_leviroth);
    RegisterSpellScript(spell_item_brewfest_mount_transformation);
    RegisterSpellScript(spell_item_nitro_boots);
    RegisterSpellScript(spell_item_teach_language);
    RegisterSpellScript(spell_item_rocket_boots);
    RegisterSpellScript(spell_item_healing_injector);
    RegisterSpellScript(spell_item_mana_injector);
    RegisterSpellScript(spell_item_pygmy_oil);
    RegisterSpellScript(spell_item_unusual_compass);
    RegisterSpellScript(spell_item_chicken_cover);
    RegisterSpellScript(spell_item_muisek_vessel);
    RegisterSpellScript(spell_item_greatmothers_soulcatcher);
    RegisterSpellScript(spell_item_eggnog);
    RegisterSpellScript(spell_item_goblin_bomb);
    RegisterSpellScript(spell_item_linken_boomerang);
    RegisterSpellScript(spell_item_recall);
    RegisterSpellScript(spell_item_wraith_scythe_drain_life);
    RegisterSpellScript(spell_item_mirrens_drinking_hat);
    RegisterSpellScript(spell_item_snowman);
    RegisterSpellScript(spell_item_freeze_rookery_egg);
    RegisterSpellScript(spell_item_green_whelp_armor);
    RegisterSpellScript(spell_item_elixir_of_shadows);
    RegisterSpellScript(spell_item_worn_troll_dice);
    RegisterSpellScript(spell_item_venomhide_feed);
    RegisterSpellScript(spell_item_scroll_of_retribution);
    RegisterSpellAndAuraScriptPair(spell_item_eye_of_grillok, spell_item_eye_of_grillok_aura);
    RegisterSpellScript(spell_item_fel_mana_potion);
    RegisterSpellScript(spell_item_gor_dreks_ointment);
    RegisterSpellScript(spell_item_skyguard_blasting_charges);
    RegisterSpellScript(spell_item_luffa);
    RegisterSpellScript(spell_item_spell_reflectors);
    RegisterSpellScript(spell_item_multiphase_goggles);
    RegisterSpellScript(spell_item_bloodsail_admiral_hat);
    RegisterSpellScript(spell_item_brewfest_hops);
    RegisterSpellScript(spell_item_alchemists_stone);
    RegisterSpellScript(spell_item_darkmoon_card_greatness);
    RegisterSpellScript(spell_item_death_choice);
    RegisterSpellScriptWithArgs(spell_item_lightning_capacitor, "spell_item_lightning_capacitor");
    RegisterSpellScriptWithArgs(spell_item_thunder_capacitor, "spell_item_thunder_capacitor");
    RegisterSpellScriptWithArgs(spell_item_toc25_caster_trinket_normal, "spell_item_toc25_caster_trinket_normal");
    RegisterSpellScriptWithArgs(spell_item_toc25_caster_trinket_heroic, "spell_item_toc25_caster_trinket_heroic");
    RegisterSpellScript(spell_item_soul_preserver);
    RegisterSpellScript(spell_item_charm_witch_doctor);
    RegisterSpellScript(spell_item_lifegiving_gem);
    RegisterSpellScript(spell_item_mana_drain);
    RegisterSpellScript(spell_item_mind_control_cap);
    RegisterSpellScript(spell_item_hourglass_sand);
    RegisterSpellScript(spell_item_ultrasafe_transporter);
    RegisterSpellScript(spell_item_power_circle);
    RegisterSpellScript(spell_item_thrallmar_and_honor_hold_favor);
    RegisterSpellScript(spell_item_drums_of_forgotten_kings);
    RegisterSpellScript(spell_item_drums_of_the_wild);
    RegisterSpellScript(spell_item_darkmoon_card_illusion);
    RegisterSpellScript(spell_item_mad_alchemists_potion);
    RegisterSpellScript(spell_item_crazy_alchemists_potion);
    RegisterSpellScript(spell_item_decahedral_dwarven_dice);
    RegisterSpellScript(spell_item_aura_of_madness);
    RegisterSpellScript(spell_item_dementia);
    RegisterSpellScript(spell_item_deadly_precision);
    RegisterSpellScript(spell_item_deadly_precision_dummy);
    RegisterSpellScript(spell_item_deathbringers_will_normal);
    RegisterSpellScript(spell_item_deathbringers_will_heroic);
    RegisterSpellScript(spell_item_discerning_eye_beast_dummy);
    RegisterSpellScript(spell_item_flexweave_underlay);
    RegisterSpellScript(spell_item_frozen_shadoweave);
    RegisterSpellScript(spell_item_healing_touch_refund);
    RegisterSpellScript(spell_item_heartpierce);
    RegisterSpellScript(spell_item_heartpierce_hero);
    RegisterSpellScript(spell_item_mark_of_conquest);
    RegisterSpellScript(spell_item_pendant_of_the_violet_eye);
    RegisterSpellScript(spell_item_persistent_shield);
    RegisterSpellScript(spell_item_pet_healing);
    RegisterSpellScript(spell_item_restless_strength);
    RegisterSpellScript(spell_item_unstable_power);
    RegisterSpellScript(spell_item_commendation_of_kaelthas);
    RegisterSpellScript(spell_item_corpse_tongue_coin);
    RegisterSpellScript(spell_item_corpse_tongue_coin_heroic);
    RegisterSpellScript(spell_item_crystal_spire_of_karabor);
    RegisterSpellScript(spell_item_soul_harvesters_charm);
    RegisterSpellScript(spell_item_sunwell_exalted_caster_neck);
    RegisterSpellScript(spell_item_sunwell_exalted_healer_neck);
    RegisterSpellScript(spell_item_sunwell_exalted_melee_neck);
    RegisterSpellScript(spell_item_sunwell_exalted_tank_neck);
    RegisterSpellScript(spell_item_swift_hand_justice_dummy);
    RegisterSpellScript(spell_item_tiny_abomination_in_a_jar);
    RegisterSpellScript(spell_item_tiny_abomination_in_a_jar_hero);
    RegisterSpellScript(spell_item_totem_of_flowing_water);
    RegisterSpellScript(spell_item_petrified_twilight_scale);
    RegisterSpellScript(spell_item_petrified_twilight_scale_heroic);
    RegisterSpellScript(spell_item_purified_shard_of_the_scale);
    RegisterSpellScript(spell_item_shiny_shard_of_the_scale);
    RegisterSpellScript(spell_item_living_root_of_the_wildheart);
}
References RegisterSpellAndAuraScriptPair, RegisterSpellScript, RegisterSpellScriptWithArgs, SPELL_ARCANITE_DRAGONLING, SPELL_BATTLE_CHICKEN, SPELL_GOBLIN_JUMPER_CABLES_FAIL, SPELL_GOBLIN_JUMPER_CABLES_XL_FAIL, SPELL_MECHANICAL_DRAGONLING, and SPELL_MITHRIL_MECHANICAL_DRAGONLING.
Referenced by AddSpellsScripts().
AddSC_mage_spell_scripts()
void AddSC_mage_spell_scripts ()
{
    RegisterSpellScript(spell_mage_arcane_blast);
    RegisterSpellScript(spell_mage_arcane_missiles);
    RegisterSpellScript(spell_mage_arcane_potency);
    RegisterSpellScript(spell_mage_blazing_speed);
    RegisterSpellScript(spell_mage_burning_determination);
    RegisterSpellScript(spell_mage_molten_armor);
    RegisterSpellScript(spell_mage_mirror_image);
    RegisterSpellScript(spell_mage_burnout);
    RegisterSpellScript(spell_mage_burnout_trigger);
    RegisterSpellScript(spell_mage_pet_scaling);
    RegisterSpellScript(spell_mage_brain_freeze);
    RegisterSpellScript(spell_mage_combustion);
    RegisterSpellScript(spell_mage_glyph_of_eternal_water);
    RegisterSpellScript(spell_mage_combustion_proc);
    RegisterSpellScript(spell_mage_dragon_breath);
    RegisterSpellScript(spell_mage_empowered_fire);
    RegisterSpellScript(spell_mage_gen_extra_effects);
    RegisterSpellScript(spell_mage_frostfire_bolt);
    RegisterSpellScript(spell_mage_glyph_of_ice_block);
    RegisterSpellScript(spell_mage_glyph_of_icy_veins);
    RegisterSpellScript(spell_mage_glyph_of_polymorph);
    RegisterSpellScript(spell_mage_hot_streak);
    RegisterSpellScript(spell_mage_ice_barrier);
    RegisterSpellScript(spell_mage_ice_barrier_aura);
    RegisterSpellScript(spell_mage_ice_block);
    RegisterSpellScript(spell_mage_imp_blizzard);
    RegisterSpellScript(spell_mage_imp_mana_gems);
    RegisterSpellScript(spell_mage_clearcasting);
    RegisterSpellScript(spell_mage_missile_barrage);
    RegisterSpellScript(spell_mage_missile_barrage_proc);
    RegisterSpellScript(spell_mage_blast_wave);
    RegisterSpellScript(spell_mage_cold_snap);
    RegisterSpellScript(spell_mage_fire_frost_ward);
    RegisterSpellScript(spell_mage_focus_magic);
    RegisterSpellScript(spell_mage_ignite);
    RegisterSpellScript(spell_mage_living_bomb);
    RegisterSpellScript(spell_mage_mana_shield);
    RegisterSpellScript(spell_mage_master_of_elements);
    RegisterSpellScript(spell_mage_polymorph_cast_visual);
    RegisterSpellScript(spell_mage_summon_water_elemental);
    RegisterSpellScript(spell_mage_fingers_of_frost);
    RegisterSpellScript(spell_mage_magic_absorption);
}
References RegisterSpellScript.
Referenced by AddSpellsScripts().
AddSC_paladin_spell_scripts()
void AddSC_paladin_spell_scripts ()
{
    RegisterSpellAndAuraScriptPair(spell_pal_seal_of_command, spell_pal_seal_of_command_aura);
    RegisterSpellScript(spell_pal_divine_intervention);
    RegisterSpellScript(spell_pal_divine_purpose);
    RegisterSpellScript(spell_pal_seal_of_light);
    RegisterSpellScript(spell_pal_sacred_shield);
    RegisterSpellScript(spell_pal_ardent_defender);
    RegisterSpellScript(spell_pal_aura_mastery);
    RegisterSpellScript(spell_pal_aura_mastery_immune);
    RegisterSpellScript(spell_pal_beacon_of_light);
    RegisterSpellScript(spell_pal_avenging_wrath);
    RegisterSpellScript(spell_pal_blessing_of_faith);
    RegisterSpellScript(spell_pal_blessing_of_sanctuary);
    RegisterSpellScript(spell_pal_divine_sacrifice);
    RegisterSpellScript(spell_pal_divine_storm);
    RegisterSpellScript(spell_pal_divine_storm_dummy);
    RegisterSpellScript(spell_pal_exorcism_and_holy_wrath_damage);
    RegisterSpellScript(spell_pal_eye_for_an_eye);
    RegisterSpellScript(spell_pal_glyph_of_holy_light);
    RegisterSpellScript(spell_pal_guarded_by_the_light);
    RegisterSpellAndAuraScriptPair(spell_pal_hand_of_sacrifice, spell_pal_hand_of_sacrifice_aura);
    RegisterSpellScript(spell_pal_hand_of_salvation);
    RegisterSpellScript(spell_pal_holy_shock);
    RegisterSpellScript(spell_pal_infusion_of_light);
    RegisterSpellScript(spell_pal_item_t6_trinket);
    RegisterSpellScriptWithArgs(spell_pal_judgement, "spell_pal_judgement_of_justice", SPELL_PALADIN_JUDGEMENT_OF_JUSTICE);
    RegisterSpellScriptWithArgs(spell_pal_judgement, "spell_pal_judgement_of_light", SPELL_PALADIN_JUDGEMENT_OF_LIGHT);
    RegisterSpellScriptWithArgs(spell_pal_judgement, "spell_pal_judgement_of_wisdom", SPELL_PALADIN_JUDGEMENT_OF_WISDOM);
    RegisterSpellScript(spell_pal_judgement_of_command);
    RegisterSpellScript(spell_pal_lay_on_hands);
    RegisterSpellScript(spell_pal_righteous_defense);
    RegisterSpellScript(spell_pal_seal_of_righteousness);
    RegisterSpellScriptWithArgs(spell_pal_seal_of_vengeance_aura, "spell_pal_seal_of_vengeance");
    RegisterSpellScriptWithArgs(spell_pal_seal_of_vengeance_aura, "spell_pal_seal_of_corruption");
    RegisterSpellScript(spell_pal_hand_of_protection);
    RegisterSpellScript(spell_pal_judgements_of_the_wise);
    RegisterSpellScript(spell_pal_righteous_vengeance);
    RegisterSpellScript(spell_pal_sheath_of_light);
    RegisterSpellScript(spell_pal_judgement_of_light_heal);
    RegisterSpellScript(spell_pal_judgement_of_wisdom_mana);
    RegisterSpellScript(spell_pal_spiritual_attunement);
    RegisterSpellScript(spell_pal_t3_6p_bonus);
    RegisterSpellScript(spell_pal_t8_2p_bonus);
    RegisterSpellScript(spell_pal_glyph_of_divinity);
    RegisterSpellScript(spell_pal_glyph_of_holy_light_dummy);
    RegisterSpellScript(spell_pal_heart_of_the_crusader);
    RegisterSpellScript(spell_pal_improved_lay_of_hands);
    RegisterSpellScript(spell_pal_judgements_of_the_just);
    RegisterSpellScript(spell_pal_sacred_shield_dummy);
    RegisterSpellScript(spell_pal_illumination);
    RegisterSpellScript(spell_pal_immunities);
    RegisterSpellScriptWithArgs(spell_pal_improved_aura, "spell_pal_improved_concentraction_aura", SPELL_PALADIN_IMPROVED_CONCENTRACTION_AURA);
    RegisterSpellScriptWithArgs(spell_pal_improved_aura, "spell_pal_improved_devotion_aura", SPELL_PALADIN_IMPROVED_DEVOTION_AURA);
    RegisterSpellScriptWithArgs(spell_pal_improved_aura, "spell_pal_sanctified_retribution", SPELL_PALADIN_SANCTIFIED_RETRIBUTION_AURA);
    RegisterSpellScriptWithArgs(spell_pal_improved_aura, "spell_pal_swift_retribution", SPELL_PALADIN_SANCTIFIED_RETRIBUTION_AURA);
    RegisterSpellScript(spell_pal_light_s_beacon);
}
References RegisterSpellAndAuraScriptPair, RegisterSpellScript, RegisterSpellScriptWithArgs, SPELL_PALADIN_IMPROVED_CONCENTRACTION_AURA, SPELL_PALADIN_IMPROVED_DEVOTION_AURA, SPELL_PALADIN_JUDGEMENT_OF_JUSTICE, SPELL_PALADIN_JUDGEMENT_OF_LIGHT, SPELL_PALADIN_JUDGEMENT_OF_WISDOM, and SPELL_PALADIN_SANCTIFIED_RETRIBUTION_AURA.
Referenced by AddSpellsScripts().
AddSC_priest_spell_scripts()
void AddSC_priest_spell_scripts ()
{
    RegisterSpellScript(spell_pri_shadowfiend_scaling);
    RegisterSpellScript(spell_pri_circle_of_healing);
    RegisterSpellScript(spell_pri_divine_aegis);
    RegisterSpellScript(spell_pri_divine_hymn);
    RegisterSpellScript(spell_pri_glyph_of_prayer_of_healing);
    RegisterSpellScript(spell_pri_guardian_spirit);
    RegisterSpellScript(spell_pri_hymn_of_hope);
    RegisterSpellScript(spell_pri_lightwell);
    RegisterSpellScript(spell_pri_lightwell_renew);
    RegisterSpellScript(spell_pri_mana_burn);
    RegisterSpellScript(spell_pri_mana_leech);
    RegisterSpellScript(spell_pri_mind_sear);
    RegisterSpellScript(spell_pri_pain_and_suffering_dummy);
    RegisterSpellScript(spell_pri_pain_and_suffering_proc);
    RegisterSpellScript(spell_pri_penance);
    RegisterSpellAndAuraScriptPair(spell_pri_power_word_shield, spell_pri_power_word_shield_aura);
    RegisterSpellScript(spell_pri_prayer_of_mending_heal);
    RegisterSpellScript(spell_pri_renew);
    RegisterSpellScript(spell_pri_shadow_word_death);
    RegisterSpellScript(spell_pri_vampiric_touch);
    RegisterSpellScript(spell_pri_mind_control);
    RegisterSpellScript(spell_pri_t4_4p_bonus);
    RegisterSpellScript(spell_pri_shadowfiend_death);
    RegisterSpellScript(spell_pri_vampiric_embrace);
    RegisterSpellScript(spell_pri_glyph_of_dispel_magic);
    RegisterSpellScript(spell_pri_body_and_soul);
    RegisterSpellScript(spell_pri_improved_shadowform);
    // Proc system scripts
    RegisterSpellScript(spell_pri_aq_3p_bonus);
    RegisterSpellScript(spell_pri_blessed_recovery);
    RegisterSpellScript(spell_pri_imp_shadowform);
    RegisterSpellScript(spell_pri_improved_spirit_tap);
    RegisterSpellScript(spell_pri_item_t6_trinket);
    RegisterSpellScript(spell_pri_t3_4p_bonus);
    RegisterSpellScript(spell_pri_t5_heal_2p_bonus);
    RegisterSpellScript(spell_pri_t10_heal_2p_bonus);
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddSpellsScripts().
AddSC_quest_spell_scripts()
void AddSC_quest_spell_scripts ()
{
    RegisterSpellScript(spell_q5561_kodo_roundup_kodo_kombobulator);
    RegisterSpellScript(spell_q5561_kodo_roundup_kodo_kombobulator_despawn);
    RegisterSpellAndAuraScriptPair(spell_q11065_wrangle_some_aether_rays, spell_q11065_wrangle_some_aether_rays_aura);
    RegisterSpellScript(spell_image_of_drakuru_reagent_check);
    RegisterSpellScript(spell_q12014_steady_as_a_rock);
    RegisterSpellAndAuraScriptPair(spell_q11026_a11051_banish_the_demons, spell_q11026_a11051_banish_the_demons_aura);
    RegisterSpellScript(spell_q10525_vision_guide);
    RegisterSpellScript(spell_q10714_on_spirits_wings);
    RegisterSpellScript(spell_q10720_the_smallest_creature);
    RegisterSpellScript(spell_q13086_last_line_of_defence);
    RegisterSpellScript(spell_q12943_shadow_vault_decree);
    RegisterSpellAndAuraScriptPair(spell_q10769_dissension_amongst_the_ranks, spell_q10769_dissension_amongst_the_ranks_aura);
    RegisterSpellScript(spell_q11520_discovering_your_roots);
    RegisterSpellScript(spell_q11670_it_was_the_orcs_honest);
    RegisterSpellScript(spell_quest_test_flight_charging);
    RegisterSpellScript(spell_q12274_a_fall_from_grace_costume);
    RegisterSpellScript(spell_q13369_fate_up_against_your_will);
    RegisterSpellScript(spell_q11198_take_down_tethyr);
    RegisterSpellScript(spell_q11653_youre_not_so_big_now);
    RegisterSpellScript(spell_q10985_light_of_the_naaru);
    RegisterSpellScript(spell_q9718_crow_transform);
    new spell_q55_sacred_cleansing();
    RegisterSpellScript(spell_q1846_bending_shinbone);
    RegisterSpellScript(spell_q2203_thaumaturgy_channel);
    RegisterSpellScript(spell_q5206_test_fetid_skull);
    RegisterSpellScript(spell_q6124_6129_apply_salve);
    RegisterSpellScript(spell_q11396_11399_force_shield_arcane_purple_x3);
    RegisterSpellScript(spell_q11396_11399_scourging_crystal_controller);
    RegisterSpellScript(spell_q11396_11399_scourging_crystal_controller_dummy);
    new spell_q11515_fel_siphon_dummy();
    RegisterSpellScript(spell_q11587_arcane_prisoner_rescue);
    RegisterSpellScript(spell_q11730_ultrasonic_screwdriver);
    RegisterSpellScript(spell_q12459_seeds_of_natures_wrath);
    RegisterSpellScript(spell_q12634_despawn_fruit_tosser);
    RegisterSpellScript(spell_q12683_take_sputum_sample);
    RegisterSpellScript(spell_q12851_going_bearback);
    RegisterSpellScript(spell_q12937_relief_for_the_fallen);
    RegisterSpellScript(spell_q10041_q10040_who_are_they);
    RegisterSpellScript(spell_symbol_of_life_dummy);
    RegisterSpellScript(spell_q12659_ahunaes_knife);
    RegisterSpellScript(spell_q9874_liquid_fire);
    RegisterSpellScript(spell_q12805_lifeblood_dummy);
    RegisterSpellScript(spell_q13280_13283_plant_battle_standard);
    RegisterSpellScript(spell_q14112_14145_chum_the_water);
    RegisterSpellScript(spell_q9452_cast_net);
    RegisterSpellScript(spell_q12987_read_pronouncement);
    RegisterSpellScript(spell_q12277_wintergarde_mine_explosion);
    RegisterSpellScript(spell_q12066_bunny_kill_credit);
    RegisterSpellScript(spell_q12735_song_of_cleansing);
    RegisterSpellScript(spell_q11010_q11102_q11023_aggro_check_aura);
    RegisterSpellScript(spell_q11010_q11102_q11023_aggro_check);
    RegisterSpellScript(spell_q11010_q11102_q11023_aggro_burst);
    RegisterSpellScript(spell_q11010_q11102_q11023_choose_loc);
    RegisterSpellScript(spell_q11010_q11102_q11023_q11008_check_fly_mount);
    RegisterSpellScript(spell_q12661_q12669_q12676_q12677_q12713_summon_stefan);
    RegisterSpellScript(spell_q12730_quenching_mist);
    RegisterSpellScript(spell_q13291_q13292_q13239_q13261_frostbrood_skytalon_grab_decoy);
    RegisterSpellScript(spell_q13291_q13292_q13239_q13261_armored_decoy_summon_skytalon);
    RegisterSpellScript(spell_q13011_bear_flank_master);
    RegisterSpellScript(spell_q12690_burst_at_the_seams);
    RegisterSpellScript(spell_q12308_escape_from_silverbrook_summon_worgen);
    RegisterSpellScript(spell_q12308_escape_from_silverbrook);
    RegisterSpellScript(spell_q12641_death_comes_from_on_high);
    RegisterSpellScript(spell_q12619_emblazon_runeblade);
    RegisterSpellScript(spell_q12619_emblazon_runeblade_effect);
    RegisterSpellScript(spell_q12919_gymers_grab);
    RegisterSpellScript(spell_q12919_gymers_throw);
    RegisterSpellScript(spell_q5056_summon_shy_rotam);
    RegisterSpellScript(spell_q4735_collect_rookery_egg);
    RegisterSpellScript(spell_q10651_q10692_book_of_fel_names);
    RegisterSpellScript(spell_q9847_a_spirit_ally);
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddSpellsScripts().
AddSC_rogue_spell_scripts()
void AddSC_rogue_spell_scripts ()
{
    RegisterSpellScript(spell_rog_savage_combat);
    RegisterSpellScript(spell_rog_combat_potency);
    RegisterSpellScript(spell_rog_blade_flurry);
    RegisterSpellScript(spell_rog_cheat_death);
    RegisterSpellScript(spell_rog_deadly_poison);
    RegisterSpellAndAuraScriptPair(spell_rog_killing_spree, spell_rog_killing_spree_aura);
    RegisterSpellScript(spell_rog_nerves_of_steel);
    RegisterSpellScript(spell_rog_preparation);
    RegisterSpellScript(spell_rog_prey_on_the_weak);
    RegisterSpellScript(spell_rog_rupture);
    RegisterSpellScript(spell_rog_shiv);
    RegisterSpellAndAuraScriptPair(spell_rog_tricks_of_the_trade, spell_rog_tricks_of_the_trade_aura);
    RegisterSpellScript(spell_rog_tricks_of_the_trade_proc);
    RegisterSpellScript(spell_rog_pickpocket);
    RegisterSpellScript(spell_rog_vanish_purge);
    RegisterSpellScript(spell_rog_vanish);
    // Proc system scripts
    RegisterSpellScript(spell_rog_glyph_of_backstab);
    RegisterSpellScriptWithArgs(spell_rog_stealth_buff_tracker<SPELL_ROGUE_MASTER_OF_SUBTLETY_DAMAGE>, "spell_rog_master_of_subtlety");
    RegisterSpellScriptWithArgs(spell_rog_stealth_buff_tracker<SPELL_ROGUE_OVERKILL_TRIGGERED>, "spell_rog_overkill");
    RegisterSpellScript(spell_rog_cut_to_the_chase);
    RegisterSpellScript(spell_rog_deadly_brew);
    RegisterSpellScript(spell_rog_quick_recovery);
    RegisterSpellScript(spell_rog_setup);
    RegisterSpellScript(spell_rog_honor_among_thieves);
    RegisterSpellAndAuraScriptPair(spell_rog_honor_among_thieves_proc, spell_rog_honor_among_thieves_proc_aura);
    RegisterSpellScript(spell_rog_turn_the_tables);
    RegisterSpellScript(spell_rog_turn_the_tables_proc);
    RegisterSpellScript(spell_rog_focused_attacks);
    RegisterSpellScript(spell_rog_mutilate);
    RegisterSpellScript(spell_rog_cold_blood);
}
References RegisterSpellAndAuraScriptPair, RegisterSpellScript, and RegisterSpellScriptWithArgs.
Referenced by AddSpellsScripts().
AddSC_shaman_spell_scripts()
void AddSC_shaman_spell_scripts ()
{
    RegisterSpellScript(spell_sha_totem_of_wrath);
    RegisterSpellScript(spell_sha_spirit_walk);
    RegisterSpellScript(spell_sha_t10_restoration_4p_bonus);
    RegisterSpellScript(spell_sha_totemic_mastery);
    RegisterSpellScript(spell_sha_feral_spirit_scaling);
    RegisterSpellScript(spell_sha_fire_elemental_scaling);
    RegisterSpellScript(spell_sha_ancestral_awakening_proc);
    RegisterSpellScript(spell_sha_astral_shift);
    RegisterSpellScript(spell_sha_bloodlust);
    RegisterSpellScript(spell_sha_chain_heal);
    RegisterSpellScript(spell_sha_cleansing_totem_pulse);
    RegisterSpellScript(spell_sha_earth_shield);
    RegisterSpellScript(spell_sha_earthbind_totem);
    RegisterSpellScript(spell_sha_earthen_power);
    RegisterSpellScript(spell_sha_earthliving_weapon);
    RegisterSpellScript(spell_sha_fire_nova);
    RegisterSpellScript(spell_sha_flame_shock);
    RegisterSpellScript(spell_sha_healing_stream_totem);
    RegisterSpellScript(spell_sha_heroism);
    RegisterSpellScript(spell_sha_item_lightning_shield);
    RegisterSpellScript(spell_sha_item_lightning_shield_trigger);
    RegisterSpellScript(spell_sha_item_mana_surge);
    RegisterSpellScript(spell_sha_elemental_focus);
    RegisterSpellScript(spell_sha_item_t10_elemental_2p_bonus);
    RegisterSpellScript(spell_sha_lava_lash);
    RegisterSpellScript(spell_sha_mana_spring_totem);
    RegisterSpellScript(spell_sha_mana_tide);
    RegisterSpellScript(spell_sha_mana_tide_totem);
    RegisterSpellScript(spell_sha_nature_guardian);
    RegisterSpellScript(spell_sha_sentry_totem);
    RegisterSpellScript(spell_sha_stoneclaw_totem);
    RegisterSpellScript(spell_sha_thunderstorm);
    RegisterSpellScript(spell_sha_flurry_proc);
    RegisterSpellScript(spell_sha_glyph_of_healing_wave);
    RegisterSpellScript(spell_sha_spirit_hunt);
    RegisterSpellScript(spell_sha_frozen_power);
    RegisterSpellScript(spell_sha_lightning_overload);
    RegisterSpellScript(spell_sha_ancestral_awakening);
    RegisterSpellScript(spell_sha_astral_shift_aura);
    RegisterSpellScript(spell_sha_astral_shift_visual_dummy);
    RegisterSpellScript(spell_sha_clearcasting);
    RegisterSpellScript(spell_sha_flametongue_weapon);
    RegisterSpellScript(spell_sha_glyph_of_earth_shield);
    RegisterSpellScript(spell_sha_glyph_of_totem_of_wrath);
    RegisterSpellScript(spell_sha_imp_water_shield);
    RegisterSpellScript(spell_sha_item_t6_trinket);
    RegisterSpellScript(spell_sha_maelstrom_weapon);
    RegisterSpellScript(spell_sha_shamanistic_rage);
    RegisterSpellScript(spell_sha_lightning_shield);
    RegisterSpellScript(spell_sha_static_shock);
    RegisterSpellScript(spell_sha_t10_elemental_4p_bonus);
    RegisterSpellScript(spell_sha_t3_6p_bonus);
    RegisterSpellScript(spell_sha_t3_8p_bonus);
    RegisterSpellScript(spell_sha_t8_elemental_4p_bonus);
    RegisterSpellScript(spell_sha_t9_elemental_4p_bonus);
    RegisterSpellScript(spell_sha_tidal_force_dummy);
    RegisterSpellScript(spell_sha_windfury_weapon);
}
References RegisterSpellScript.
Referenced by AddSpellsScripts().
AddSC_warlock_spell_scripts()
void AddSC_warlock_spell_scripts ()
{
    RegisterSpellScript(spell_warl_nether_protection);
    RegisterSpellScript(spell_warl_eye_of_kilrogg);
    RegisterSpellScript(spell_warl_shadowflame);
    RegisterSpellScript(spell_warl_seduction);
    RegisterSpellScript(spell_warl_improved_demonic_tactics);
    RegisterSpellScript(spell_warl_ritual_of_summoning);
    RegisterSpellScript(spell_warl_demonic_aegis);
    RegisterSpellScript(spell_warl_demonic_knowledge);
    RegisterSpellScript(spell_warl_generic_scaling);
    RegisterSpellScript(spell_warl_infernal_scaling);
    RegisterSpellScript(spell_warl_banish);
    RegisterSpellScript(spell_warl_create_healthstone);
    RegisterSpellScript(spell_warl_curse_of_doom);
    RegisterSpellScript(spell_warl_demonic_circle_summon);
    RegisterSpellScript(spell_warl_demonic_circle_teleport);
    RegisterSpellScript(spell_warl_demonic_empowerment);
    RegisterSpellScript(spell_warl_everlasting_affliction);
    RegisterSpellScript(spell_warl_fel_synergy);
    RegisterSpellScript(spell_warl_glyph_of_shadowflame);
    RegisterSpellAndAuraScriptPair(spell_warl_haunt, spell_warl_haunt_aura);
    RegisterSpellScript(spell_warl_health_funnel);
    RegisterSpellScript(spell_warl_life_tap);
    RegisterSpellScript(spell_warl_ritual_of_doom_effect);
    RegisterSpellScript(spell_warl_seed_of_corruption_damage);
    RegisterSpellScript(spell_warl_shadow_ward);
    RegisterSpellScript(spell_warl_siphon_life);
    RegisterSpellScript(spell_warl_soulshatter);
    RegisterSpellScript(spell_warl_unstable_affliction);
    RegisterSpellScript(spell_warl_drain_soul);
    RegisterSpellScript(spell_warl_shadowburn);
    RegisterSpellScript(spell_warl_voidwalker_pet_passive);
    RegisterSpellScript(spell_warl_curse_of_agony);
    RegisterSpellScript(spell_warl_glyph_of_corruption_nightfall);
    RegisterSpellScript(spell_warl_nightfall);
    RegisterSpellScript(spell_warl_decimation);
    RegisterSpellScript(spell_warl_demonic_pact);
    RegisterSpellScript(spell_warl_glyph_of_life_tap);
    RegisterSpellScript(spell_warl_improved_drain_soul);
    RegisterSpellScript(spell_warl_seed_of_corruption_dummy);
    RegisterSpellScript(spell_warl_seed_of_corruption_generic);
    RegisterSpellScript(spell_warl_soul_leech);
    RegisterSpellScript(spell_warl_t4_2p_bonus_fire);
    RegisterSpellScript(spell_warl_t4_2p_bonus_shadow);
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddSpellsScripts().
AddSC_warrior_spell_scripts()
void AddSC_warrior_spell_scripts ()
{
    RegisterSpellScript(spell_warr_mocking_blow);
    RegisterSpellScript(spell_warr_intervene);
    RegisterSpellScript(spell_warr_improved_spell_reflection);
    RegisterSpellAndAuraScriptPair(spell_warr_improved_spell_reflection_trigger, spell_warr_improved_spell_reflection_trigger_aura);
    RegisterSpellScript(spell_warr_victory_rush);
    RegisterSpellScript(spell_warr_bloodthirst);
    RegisterSpellScript(spell_warr_bloodthirst_heal);
    RegisterSpellScript(spell_warr_charge);
    RegisterSpellScript(spell_warr_concussion_blow);
    RegisterSpellScript(spell_warr_damage_shield);
    RegisterSpellScript(spell_warr_deep_wounds);
    RegisterSpellScript(spell_warr_execute);
    RegisterSpellScript(spell_warr_glyph_of_sunder_armor);
    RegisterSpellScript(spell_warr_intimidating_shout);
    RegisterSpellScript(spell_warr_last_stand);
    RegisterSpellScript(spell_warr_overpower);
    RegisterSpellScript(spell_warr_rend);
    RegisterSpellScript(spell_warr_retaliation);
    RegisterSpellScript(spell_warr_shattering_throw);
    RegisterSpellScript(spell_warr_slam);
    RegisterSpellScript(spell_warr_sweeping_strikes);
    RegisterSpellScript(spell_warr_vigilance);
    RegisterSpellScript(spell_warr_vigilance_redirect_threat);
    RegisterSpellScript(spell_warr_vigilance_trigger);
    RegisterSpellScript(spell_warr_warriors_wrath);
    RegisterSpellScript(spell_warr_t3_prot_8p_bonus);
    RegisterSpellScript(spell_warr_heroic_strike);
    RegisterSpellScript(spell_war_sudden_death_aura);
    RegisterSpellScript(spell_warr_second_wind);
    RegisterSpellScript(spell_warr_deep_wounds_aura);
    RegisterSpellScript(spell_warr_extra_proc);
    RegisterSpellScript(spell_warr_sword_and_board);
    RegisterSpellScript(spell_warr_glyph_of_blocking);
    RegisterSpellScript(spell_warr_item_t10_prot_4p_bonus);
}
References RegisterSpellAndAuraScriptPair, and RegisterSpellScript.
Referenced by AddSpellsScripts().
AddSpellsScripts()
void AddSpellsScripts ()
{
    AddSC_deathknight_spell_scripts();
    AddSC_druid_spell_scripts();
    AddSC_generic_spell_scripts();
    AddSC_hunter_spell_scripts();
    AddSC_mage_spell_scripts();
    AddSC_paladin_spell_scripts();
    AddSC_priest_spell_scripts();
    AddSC_rogue_spell_scripts();
    AddSC_shaman_spell_scripts();
    AddSC_warlock_spell_scripts();
    AddSC_warrior_spell_scripts();
    AddSC_quest_spell_scripts();
    AddSC_item_spell_scripts();
}
References AddSC_deathknight_spell_scripts(), AddSC_druid_spell_scripts(), AddSC_generic_spell_scripts(), AddSC_hunter_spell_scripts(), AddSC_item_spell_scripts(), AddSC_mage_spell_scripts(), AddSC_paladin_spell_scripts(), AddSC_priest_spell_scripts(), AddSC_quest_spell_scripts(), AddSC_rogue_spell_scripts(), AddSC_shaman_spell_scripts(), AddSC_warlock_spell_scripts(), and AddSC_warrior_spell_scripts().