AzerothCore: anonymous_namespace{ResetAttackTimerTest.cpp} Namespace Reference
anonymous_namespace{ResetAttackTimerTest.cpp} Namespace Reference
Functions
int32_t OldResetFormula (int32_t currentTimer, int32_t fullTime)
int32_t NewResetFormula (int32_t, int32_t fullTime)
int32_t CalcFullTime (uint32_t baseAttackTime, float modSpeedPct)
Detailed Description
Tests for Unit::resetAttackTimer arithmetic.
Unit::resetAttackTimer resets the swing timer after an attack lands. The timer value determines when the next attack can occur.
Old (buggy) formula: int32 time = int32(GetAttackTime(type) * m_modAttackSpeedPct[type]); m_attackTimer[type] = std::min(m_attackTimer[type] + time, time);
New (fixed) formula: m_attackTimer[type] = int32(GetAttackTime(type) * m_modAttackSpeedPct[type]);
The old formula carried forward negative timer debt, allowing burst attacks after lag spikes or parry-haste timer reductions.
Function Documentation
CalcFullTime()
int32_t anonymous_namespace{ResetAttackTimerTest.cpp}::CalcFullTime (uint32_t baseAttackTime, float modSpeedPct)
    {
        return static_cast<int32_t>(baseAttackTime * modSpeedPct);
    }
Referenced by TEST().
NewResetFormula()
int32_t anonymous_namespace{ResetAttackTimerTest.cpp}::NewResetFormula (int32_t , int32_t fullTime)
    {
        return fullTime;
    }
Referenced by TEST().
OldResetFormula()
int32_t anonymous_namespace{ResetAttackTimerTest.cpp}::OldResetFormula (int32_t currentTimer, int32_t fullTime)
    {
        return std::min(currentTimer + fullTime, fullTime);
    }
Referenced by TEST().