AzerothCore: anonymous_namespace{PoolQuestReloadTest.cpp} Namespace Reference
anonymous_namespace{PoolQuestReloadTest.cpp} Namespace Reference
Classes
class PoolQuestReloadTest
Functions
TEST_F (PoolQuestReloadTest, Spawn1ObjectAddsQuestToCreatureRelationMap)
TEST_F (PoolQuestReloadTest, ReloadCreatureQuestStarterRemovesPooledQuest)
TEST_F (PoolQuestReloadTest, Spawn1ObjectAfterReloadRestoresQuest)
TEST_F (PoolQuestReloadTest, NonPooledQuestSurvivesReload)
Variables
static constexpr uint32 TEST_QUEST_ID = 99998
static constexpr uint32 TEST_CREATURE_ID = 99999
Function Documentation
TEST_F() [1/4]
anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_F (PoolQuestReloadTest , NonPooledQuestSurvivesReload)
{
    static constexpr uint32 REGULAR_QUEST_ID = 99990;
    // A non-pooled quest is added directly to the creature quest map
    // (this is what LoadQuestRelationsHelper does for quests without pool_entry)
    creatureQuestMap->insert(QuestRelations::value_type(TEST_CREATURE_ID, REGULAR_QUEST_ID));
    // Simulate reload: clear and repopulate
    creatureQuestMap->clear();
    // Non-pooled quests get re-inserted directly (simulating the DB reload)
    creatureQuestMap->insert(QuestRelations::value_type(TEST_CREATURE_ID, REGULAR_QUEST_ID));
    EXPECT_EQ(CountQuestOnCreature(TEST_CREATURE_ID, REGULAR_QUEST_ID), 1u)
        << "Non-pooled quests survive reload because they are re-inserted directly";
    // Cleanup
    auto range = creatureQuestMap->equal_range(TEST_CREATURE_ID);
    for (auto it = range.first; it != range.second; )
    {
        if (it->second == REGULAR_QUEST_ID)
            it = creatureQuestMap->erase(it);
        else
            ++it;
    }
}
References anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::CountQuestOnCreature(), and TEST_CREATURE_ID.
TEST_F() [2/4]
anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_F (PoolQuestReloadTest , ReloadCreatureQuestStarterRemovesPooledQuest)
{
    // 1. Spawn the pool quest onto the NPC (normal startup behavior)
    SimulateSpawn1Object(TEST_QUEST_ID);
    ASSERT_EQ(CountQuestOnCreature(TEST_CREATURE_ID, TEST_QUEST_ID), 1u)
        << "Precondition: quest must be on creature before reload";
    // 2. Simulate `.reload creature_queststarter`
    SimulateReload();
    // 3. THE BUG: quest is gone from the NPC even though it's still
    //    the active daily in the pool
    EXPECT_EQ(CountQuestOnCreature(TEST_CREATURE_ID, TEST_QUEST_ID), 0u)
        << "BUG: After reload, pooled quest vanishes from creature "
           "because Spawn1Object is never called";
    // 4. Verify mQuestCreatureRelation still has the mapping
    //    (the pool system KNOWS about the quest, it's just not on the NPC)
    auto range = sPoolMgr->mQuestCreatureRelation.equal_range(TEST_QUEST_ID);
    EXPECT_NE(range.first, range.second)
        << "Pool mapping should still exist after reload";
}
References anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::CountQuestOnCreature(), anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::SimulateReload(), anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::SimulateSpawn1Object(), sPoolMgr, TEST_CREATURE_ID, and TEST_QUEST_ID.
TEST_F() [3/4]
anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_F (PoolQuestReloadTest , Spawn1ObjectAddsQuestToCreatureRelationMap)
{
    // Initially the quest should NOT be on the creature
    EXPECT_EQ(CountQuestOnCreature(TEST_CREATURE_ID, TEST_QUEST_ID), 0u)
        << "Quest should not be on creature before Spawn1Object";
    // Spawn1Object reads from mQuestCreatureRelation and inserts into
    // the creature quest relation map
    SimulateSpawn1Object(TEST_QUEST_ID);
    EXPECT_EQ(CountQuestOnCreature(TEST_CREATURE_ID, TEST_QUEST_ID), 1u)
        << "Quest should appear on creature after Spawn1Object";
}
References anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::CountQuestOnCreature(), anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::SimulateSpawn1Object(), TEST_CREATURE_ID, and TEST_QUEST_ID.
TEST_F() [4/4]
anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_F (PoolQuestReloadTest , Spawn1ObjectAfterReloadRestoresQuest)
{
    // Setup: spawn, reload (quest disappears)
    SimulateSpawn1Object(TEST_QUEST_ID);
    SimulateReload();
    ASSERT_EQ(CountQuestOnCreature(TEST_CREATURE_ID, TEST_QUEST_ID), 0u)
        << "Precondition: quest must be missing after reload";
    // Fix: call Spawn1Object again for the active pool quest
    SimulateSpawn1Object(TEST_QUEST_ID);
    EXPECT_EQ(CountQuestOnCreature(TEST_CREATURE_ID, TEST_QUEST_ID), 1u)
        << "Spawn1Object after reload should restore the quest on the NPC";
}
References anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::CountQuestOnCreature(), anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::SimulateReload(), anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::SimulateSpawn1Object(), TEST_CREATURE_ID, and TEST_QUEST_ID.
Variable Documentation
TEST_CREATURE_ID
constexpr uint32 anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_CREATURE_ID = 99999 static constexpr
Referenced by anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::SetUp(), anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::SimulateReload(), anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::TearDown(), TEST_F(), and TEST_F().
TEST_QUEST_ID
constexpr uint32 anonymous_namespace{PoolQuestReloadTest.cpp}::TEST_QUEST_ID = 99998 static constexpr
Referenced by anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::SetUp(), anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::SimulateReload(), anonymous_namespace{PoolQuestReloadTest.cpp}::PoolQuestReloadTest::TearDown(), TEST_F(), and TEST_F().