AzerothCore: anonymous_namespace{RBACTest.cpp} Namespace Reference
anonymous_namespace{RBACTest.cpp} Namespace Reference
Classes
class RBACAccountMgrPermissionLookupTest
class RBACAccountMgrTestHelperEdgeCasesTest
class RBACCircularLinkProtectionTest
class RBACCommandResultTest
Tests to verify all RBACCommandResult values are handled.
class RBACComplexHierarchyTest
class RBACDataAccessorsTest
class RBACDataTest
Tests for RBACData class functionality with full server setup.
class RBACDefaultPermissionsTest
Tests for default permissions based on security level.
class RBACDefaultPermissionsWithRolesTest
class RBACDeniedExpansionTest
Tests for denied permission expansion.
class RBACDenySpecificFromRoleTest
class RBACDoubleRevokeTest
class RBACEmptyAndBoundaryTest
class RBACExpandPermissionsDanglingLinkTest
class RBACFullRoleHierarchyTest
class RBACGetPermissionsTest
class RBACLinkedPermissionsTest
Tests for permission inheritance through linked permissions.
class RBACLoadFromDBCallbackSimulationTest
class RBACMultipleInstancesIndependenceTest
class RBACPermissionDefaultConstructorTest
class RBACPermissionEnumConsistencyTest
class RBACPermissionExpansionTest
Tests for permission expansion through linked permissions.
class RBACPermissionRemoveLinkedTest
class RBACPermissionTest
Tests for RBACPermission class functionality.
class RBACRevokeEdgeCasesTest
class RBACSecurityLevelTest
Tests for security level accessor.
class RBACSetSecurityLevelForTestBehaviorTest
Functions
TEST_F (RBACPermissionTest, Constructor_SetsIdAndName)
TEST_F (RBACPermissionTest, LinkedPermissions_InitiallyEmpty)
TEST_F (RBACPermissionTest, AddLinkedPermission_AddsToSet)
TEST_F (RBACPermissionTest, AddLinkedPermission_NoDuplicates)
TEST_F (RBACDataTest, Constructor_SetsAccountData)
TEST_F (RBACDataTest, InitialState_EmptyPermissions)
TEST_F (RBACDataTest, GrantPermission_Success)
TEST_F (RBACDataTest, GrantPermission_AlreadyGranted_ReturnsError)
TEST_F (RBACDataTest, GrantPermission_WhenDenied_ReturnsError)
TEST_F (RBACDataTest, GrantPermission_InvalidId_ReturnsError)
TEST_F (RBACDataTest, DenyPermission_Success)
TEST_F (RBACDataTest, DenyPermission_AlreadyDenied_ReturnsError)
TEST_F (RBACDataTest, DenyPermission_WhenGranted_ReturnsError)
TEST_F (RBACDataTest, DenyPermission_InvalidId_ReturnsError)
TEST_F (RBACDataTest, RevokePermission_FromGranted_Success)
TEST_F (RBACDataTest, RevokePermission_FromDenied_Success)
TEST_F (RBACDataTest, RevokePermission_NotInList_ReturnsError)
TEST_F (RBACDataTest, HasPermission_WhenGranted_ReturnsTrue)
TEST_F (RBACDataTest, HasPermission_WhenDenied_ReturnsFalse)
TEST_F (RBACDataTest, HasPermission_WhenNotSet_ReturnsFalse)
TEST_F (RBACDataTest, MultiplePermissions_IndependentTracking)
TEST_F (RBACDataTest, RevokeAndRegrant_WorksCorrectly)
TEST_F (RBACDataTest, RevokeAndDeny_WorksCorrectly)
TEST_F (RBACCommandResultTest, AllResultValuesAreDefined)
TEST_F (RBACLinkedPermissionsTest, GrantedPermission_IsInGrantedList)
TEST_F (RBACLinkedPermissionsTest, DeniedPermission_IsInDeniedList)
TEST_F (RBACLinkedPermissionsTest, DeniedPermission_OverridesGranted)
TEST_F (RBACSecurityLevelTest, Constructor_PreservesSecurityLevel)
TEST_F (RBACSecurityLevelTest, SetSecurityLevelForTest_UpdatesLevel)
TEST_F (RBACPermissionExpansionTest, GrantRole_ExpandsLinkedPermissions)
TEST_F (RBACPermissionExpansionTest, GrantRole_RecursiveExpansion)
TEST_F (RBACPermissionExpansionTest, DenyRole_PreventsLinkedPermissions)
TEST_F (RBACPermissionExpansionTest, DenyRole_OverridesIndividualGrant)
TEST_F (RBACDefaultPermissionsTest, GetDefaultPermissions_ReturnsCorrectSet)
TEST_F (RBACDefaultPermissionsTest, GetDefaultPermissions_EmptySecLevel_ReturnsEmpty)
TEST_F (RBACDefaultPermissionsTest, SecurityLevel_DeterminesDefaultPermissions)
TEST_F (RBACDefaultPermissionsTest, HigherSecLevel_GetsOnlyOwnDefaults)
TEST_F (RBACDeniedExpansionTest, DenyRole_ExpandsDeniedLinkedPermissions)
TEST_F (RBACDeniedExpansionTest, GrantAndDenySameRole_DenyWins)
TEST_F (RBACPermissionRemoveLinkedTest, RemoveLinkedPermission_RemovesFromSet)
TEST_F (RBACPermissionRemoveLinkedTest, RemoveNonExistent_IsNoOp)
TEST_F (RBACPermissionRemoveLinkedTest, RemoveAll_LeavesEmpty)
TEST_F (RBACGetPermissionsTest, Empty_WhenNothingGranted)
TEST_F (RBACGetPermissionsTest, MatchesHasPermission)
TEST_F (RBACGetPermissionsTest, ExcludesDeniedPermissions)
TEST_F (RBACGetPermissionsTest, IncludesExpandedLinkedPermissions)
TEST_F (RBACGetPermissionsTest, ReflectsStateAfterRecalculate)
TEST_F (RBACRevokeEdgeCasesTest, RevokeUnregistered_ReturnsCantRevoke)
TEST_F (RBACRevokeEdgeCasesTest, RevokeFromEmpty_ReturnsError)
TEST_F (RBACRevokeEdgeCasesTest, RevokeGranted_ThenDeny)
TEST_F (RBACRevokeEdgeCasesTest, RevokeDenied_ThenGrant)
TEST_F (RBACRevokeEdgeCasesTest, RevokeDoesNotAffectOtherPermissions)
TEST_F (RBACComplexHierarchyTest, ThreeLevelDeep)
TEST_F (RBACComplexHierarchyTest, DiamondInheritance)
TEST_F (RBACComplexHierarchyTest, WideRole)
TEST_F (RBACComplexHierarchyTest, TwoOverlappingRoles_NoDuplicateInGetPermissions)
TEST_F (RBACComplexHierarchyTest, RevokeOneOverlappingRole_KeepsSharedFromOther)
TEST_F (RBACDenySpecificFromRoleTest, DenyOneChild_SiblingsStillGranted)
TEST_F (RBACDenySpecificFromRoleTest, DenyPermNotInRole_RolePermsUnaffected)
TEST_F (RBACDenySpecificFromRoleTest, GrantTwoRoles_DenyOneRole)
TEST_F (RBACDefaultPermissionsWithRolesTest, DefaultRoleExpandsLinked)
TEST_F (RBACDefaultPermissionsWithRolesTest, DefaultRole_DenyLinkedChild)
TEST_F (RBACDefaultPermissionsWithRolesTest, SecLevels_NoCrossContamination)
TEST_F (RBACPermissionEnumConsistencyTest, MaxGreaterThanHighestDefined)
TEST_F (RBACPermissionEnumConsistencyTest, RoleIdsWithinRange)
TEST_F (RBACPermissionEnumConsistencyTest, NonContiguousIds_Work)
TEST_F (RBACEmptyAndBoundaryTest, FreshData_AllEmpty)
TEST_F (RBACEmptyAndBoundaryTest, HasPermission_Zero_ReturnsFalse)
TEST_F (RBACEmptyAndBoundaryTest, HasPermission_Max_ReturnsFalse)
TEST_F (RBACEmptyAndBoundaryTest, GrantDenyRevokeSequence)
TEST_F (RBACEmptyAndBoundaryTest, MultipleRecalculates_Idempotent)
TEST_F (RBACEmptyAndBoundaryTest, RecalculateOnEmpty_Safe)
TEST_F (RBACCircularLinkProtectionTest, MutualLink_BothGranted)
TEST_F (RBACCircularLinkProtectionTest, SelfReferencing_Terminates)
TEST_F (RBACCircularLinkProtectionTest, CircularChainOf3_AllGranted)
TEST_F (RBACFullRoleHierarchyTest, GrantPlayerRole_OnlyPlayerPerms)
TEST_F (RBACFullRoleHierarchyTest, GrantGMRole_FullChain)
TEST_F (RBACFullRoleHierarchyTest, GrantAdminRole_AllPerms)
TEST_F (RBACFullRoleHierarchyTest, GrantAdmin_DenyModRole_ModAndPlayerDenied)
TEST_F (RBACFullRoleHierarchyTest, GrantAdmin_DenyOneCommandPerm)
TEST_F (RBACPermissionDefaultConstructorTest, DefaultConstructor_ZeroIdEmptyName)
TEST_F (RBACPermissionDefaultConstructorTest, ConstructorWithIdOnly)
TEST_F (RBACAccountMgrPermissionLookupTest, GetRBACPermission_ValidId_ReturnsPermission)
TEST_F (RBACAccountMgrPermissionLookupTest, GetRBACPermission_InvalidId_ReturnsNull)
TEST_F (RBACAccountMgrPermissionLookupTest, GetRBACPermissionList_ContainsRegistered)
TEST_F (RBACAccountMgrPermissionLookupTest, GetRBACPermissionList_SizeMatchesRegistered)
TEST_F (RBACAccountMgrTestHelperEdgeCasesTest, AddPermissionForTest_DuplicateIsNoOp)
TEST_F (RBACAccountMgrTestHelperEdgeCasesTest, AddLinkedPermission_UnregisteredParent_NoOp)
TEST_F (RBACAccountMgrTestHelperEdgeCasesTest, ClearPermissions_RemovesEverything)
TEST_F (RBACExpandPermissionsDanglingLinkTest, DanglingLink_SkippedGracefully)
TEST_F (RBACExpandPermissionsDanglingLinkTest, DenyDanglingLink_SkippedGracefully)
TEST_F (RBACLoadFromDBCallbackSimulationTest, NullResult_AppliesDefaultsAndRecalculates)
TEST_F (RBACLoadFromDBCallbackSimulationTest, NullResult_NoDefaultsForHighSecLevel)
TEST_F (RBACDoubleRevokeTest, RevokeGrantedTwice_SecondFails)
TEST_F (RBACDoubleRevokeTest, RevokeDeniedTwice_SecondFails)
TEST_F (RBACMultipleInstancesIndependenceTest, TwoInstances_NoCrossContamination)
TEST_F (RBACMultipleInstancesIndependenceTest, ModifyingOne_DoesNotAffectOther)
TEST_F (RBACSetSecurityLevelForTestBehaviorTest, DoesNotRecalculate)
TEST_F (RBACSetSecurityLevelForTestBehaviorTest, UpdatesLevelOnly)
TEST_F (RBACDataAccessorsTest, GetName_ReturnsAccountName)
TEST_F (RBACDataAccessorsTest, GetName_EmptyString)
TEST_F (RBACDataAccessorsTest, GetId_ReturnsAccountId)
TEST_F (RBACDataAccessorsTest, GrantedDeniedGlobal_AllConsistent)
Variables
constexpr uint32 TEST_PERM_1 = 1
constexpr uint32 TEST_PERM_2 = 2
constexpr uint32 TEST_PERM_3 = 3
constexpr uint32 TEST_PERM_ROLE = 100
constexpr uint32 TEST_PERM_INVALID = 99999
constexpr uint32 TEST_ACCOUNT_ID = 1
constexpr uint32 TEST_REALM_ID = 1
constexpr uint8 TEST_SEC_LEVEL = 3
const std::string TEST_ACCOUNT_NAME = "TestAccount"
Function Documentation
TEST_F() [1/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACAccountMgrPermissionLookupTest , GetRBACPermission_InvalidId_ReturnsNull)
{
    rbac::RBACPermission const* perm = sAccountMgr->GetRBACPermission(TEST_PERM_INVALID);
    EXPECT_EQ(perm, nullptr);
}
References sAccountMgr, and TEST_PERM_INVALID.
TEST_F() [2/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACAccountMgrPermissionLookupTest , GetRBACPermission_ValidId_ReturnsPermission)
{
    rbac::RBACPermission const* perm = sAccountMgr->GetRBACPermission(TEST_PERM_1);
    ASSERT_NE(perm, nullptr);
    EXPECT_EQ(perm->GetId(), TEST_PERM_1);
    EXPECT_EQ(perm->GetName(), "Permission One");
}
References rbac::RBACPermission::GetId(), rbac::RBACPermission::GetName(), sAccountMgr, and TEST_PERM_1.
TEST_F() [3/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACAccountMgrPermissionLookupTest , GetRBACPermissionList_ContainsRegistered)
{
    rbac::RBACPermissionsContainer const& list = sAccountMgr->GetRBACPermissionList();
    EXPECT_TRUE(list.find(TEST_PERM_1) != list.end());
    EXPECT_TRUE(list.find(TEST_PERM_2) != list.end());
    EXPECT_TRUE(list.find(TEST_PERM_INVALID) == list.end());
}
References sAccountMgr, TEST_PERM_1, TEST_PERM_2, and TEST_PERM_INVALID.
TEST_F() [4/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACAccountMgrPermissionLookupTest , GetRBACPermissionList_SizeMatchesRegistered)
{
    rbac::RBACPermissionsContainer const& list = sAccountMgr->GetRBACPermissionList();
    EXPECT_EQ(list.size(), 2u);
}
References sAccountMgr.
TEST_F() [5/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACAccountMgrTestHelperEdgeCasesTest , AddLinkedPermission_UnregisteredParent_NoOp)
{
    // Link to non-existent parent: should silently do nothing
    sAccountMgr->AddLinkedPermissionForTest(TEST_PERM_INVALID, TEST_PERM_1);
    EXPECT_EQ(sAccountMgr->GetRBACPermission(TEST_PERM_INVALID), nullptr);
}
References sAccountMgr, TEST_PERM_1, and TEST_PERM_INVALID.
TEST_F() [6/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACAccountMgrTestHelperEdgeCasesTest , AddPermissionForTest_DuplicateIsNoOp)
{
    sAccountMgr->AddPermissionForTest(TEST_PERM_1, "Original Name");
    sAccountMgr->AddPermissionForTest(TEST_PERM_1, "Different Name");
    rbac::RBACPermission const* perm = sAccountMgr->GetRBACPermission(TEST_PERM_1);
    ASSERT_NE(perm, nullptr);
    EXPECT_EQ(perm->GetName(), "Original Name");
}
References rbac::RBACPermission::GetName(), sAccountMgr, and TEST_PERM_1.
TEST_F() [7/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACAccountMgrTestHelperEdgeCasesTest , ClearPermissions_RemovesEverything)
{
    sAccountMgr->AddPermissionForTest(TEST_PERM_1, "One");
    sAccountMgr->AddPermissionForTest(TEST_PERM_2, "Two");
    sAccountMgr->AddDefaultPermissionForTest(0, TEST_PERM_1);
    sAccountMgr->ClearPermissionsForTest();
    EXPECT_EQ(sAccountMgr->GetRBACPermission(TEST_PERM_1), nullptr);
    EXPECT_EQ(sAccountMgr->GetRBACPermission(TEST_PERM_2), nullptr);
    EXPECT_TRUE(sAccountMgr->GetRBACPermissionList().empty());
    EXPECT_TRUE(sAccountMgr->GetRBACDefaultPermissions(0).empty());
}
References sAccountMgr, TEST_PERM_1, and TEST_PERM_2.
TEST_F() [8/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACCircularLinkProtectionTest , CircularChainOf3_AllGranted)
{
    sAccountMgr->AddLinkedPermissionForTest(PERM_A, PERM_B);
    sAccountMgr->AddLinkedPermissionForTest(PERM_B, PERM_C);
    sAccountMgr->AddLinkedPermissionForTest(PERM_C, PERM_A);
    rbac::RBACData data(1, "Test", TEST_REALM_ID, 0);
    data.GrantPermission(PERM_A);
    data.RecalculatePermissions();
    EXPECT_TRUE(data.HasPermission(PERM_A));
    EXPECT_TRUE(data.HasPermission(PERM_B));
    EXPECT_TRUE(data.HasPermission(PERM_C));
    EXPECT_EQ(data.GetPermissions().size(), 3u);
}
References rbac::RBACData::GetPermissions(), rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), sAccountMgr, and TEST_REALM_ID.
TEST_F() [9/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACCircularLinkProtectionTest , MutualLink_BothGranted)
{
    sAccountMgr->AddLinkedPermissionForTest(PERM_A, PERM_B);
    sAccountMgr->AddLinkedPermissionForTest(PERM_B, PERM_A);
    rbac::RBACData data(1, "Test", TEST_REALM_ID, 0);
    data.GrantPermission(PERM_A);
    data.RecalculatePermissions();
    EXPECT_TRUE(data.HasPermission(PERM_A));
    EXPECT_TRUE(data.HasPermission(PERM_B));
}
References rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), sAccountMgr, and TEST_REALM_ID.
TEST_F() [10/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACCircularLinkProtectionTest , SelfReferencing_Terminates)
{
    sAccountMgr->AddLinkedPermissionForTest(PERM_A, PERM_A);
    rbac::RBACData data(1, "Test", TEST_REALM_ID, 0);
    data.GrantPermission(PERM_A);
    data.RecalculatePermissions();
    EXPECT_TRUE(data.HasPermission(PERM_A));
    EXPECT_EQ(data.GetPermissions().size(), 1u);
}
References rbac::RBACData::GetPermissions(), rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), sAccountMgr, and TEST_REALM_ID.
TEST_F() [11/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACCommandResultTest , AllResultValuesAreDefined)
{
    // Verify enum values exist and are distinct
    EXPECT_NE(rbac::RBAC_OK, rbac::RBAC_CANT_ADD_ALREADY_ADDED);
    EXPECT_NE(rbac::RBAC_OK, rbac::RBAC_CANT_REVOKE_NOT_IN_LIST);
    EXPECT_NE(rbac::RBAC_OK, rbac::RBAC_IN_GRANTED_LIST);
    EXPECT_NE(rbac::RBAC_OK, rbac::RBAC_IN_DENIED_LIST);
    EXPECT_NE(rbac::RBAC_OK, rbac::RBAC_ID_DOES_NOT_EXISTS);
}
References rbac::RBAC_CANT_ADD_ALREADY_ADDED, rbac::RBAC_CANT_REVOKE_NOT_IN_LIST, rbac::RBAC_ID_DOES_NOT_EXISTS, rbac::RBAC_IN_DENIED_LIST, rbac::RBAC_IN_GRANTED_LIST, and rbac::RBAC_OK.
TEST_F() [12/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACComplexHierarchyTest , DiamondInheritance)
{
    rbacData->GrantPermission(ROLE_X);
    rbacData->GrantPermission(ROLE_Y);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(PERM_SHARED));
    EXPECT_TRUE(rbacData->HasPermission(PERM_X_ONLY));
    EXPECT_TRUE(rbacData->HasPermission(PERM_Y_ONLY));
}
TEST_F() [13/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACComplexHierarchyTest , RevokeOneOverlappingRole_KeepsSharedFromOther)
{
    rbacData->GrantPermission(ROLE_X);
    rbacData->GrantPermission(ROLE_Y);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(PERM_SHARED));
    rbacData->RevokePermission(ROLE_X);
    rbacData->RecalculatePermissions();
    // PERM_SHARED still accessible through ROLE_Y
    EXPECT_TRUE(rbacData->HasPermission(PERM_SHARED));
    EXPECT_TRUE(rbacData->HasPermission(PERM_Y_ONLY));
    EXPECT_FALSE(rbacData->HasPermission(PERM_X_ONLY));
}
TEST_F() [14/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACComplexHierarchyTest , ThreeLevelDeep)
{
    rbacData->GrantPermission(ROLE_ADMIN);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(ROLE_ADMIN));
    EXPECT_TRUE(rbacData->HasPermission(ROLE_GM));
    EXPECT_TRUE(rbacData->HasPermission(ROLE_MOD));
    EXPECT_TRUE(rbacData->HasPermission(PERM_A));
    EXPECT_TRUE(rbacData->HasPermission(PERM_B));
    EXPECT_TRUE(rbacData->HasPermission(PERM_C));
    EXPECT_TRUE(rbacData->HasPermission(PERM_D));
}
TEST_F() [15/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACComplexHierarchyTest , TwoOverlappingRoles_NoDuplicateInGetPermissions)
{
    // Both ROLE_X and ROLE_Y link to PERM_SHARED
    rbacData->GrantPermission(ROLE_X);
    rbacData->GrantPermission(ROLE_Y);
    rbacData->RecalculatePermissions();
    auto const& perms = rbacData->GetPermissions();
    // ROLE_X, ROLE_Y, PERM_SHARED, PERM_X_ONLY, PERM_Y_ONLY = 5
    EXPECT_EQ(perms.size(), 5u);
    EXPECT_EQ(perms.count(PERM_SHARED), 1u);
}
TEST_F() [16/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACComplexHierarchyTest , WideRole)
{
    rbacData->GrantPermission(ROLE_WIDE);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(ROLE_WIDE));
    EXPECT_TRUE(rbacData->HasPermission(PERM_A));
    EXPECT_TRUE(rbacData->HasPermission(PERM_L));
    EXPECT_EQ(rbacData->GetPermissions().size(), 13u); // ROLE_WIDE + 12 perms
}
TEST_F() [17/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataAccessorsTest , GetId_ReturnsAccountId)
{
    rbac::RBACData data(42, "Test", TEST_REALM_ID, 0);
    EXPECT_EQ(data.GetId(), 42u);
}
References rbac::RBACData::GetId(), and TEST_REALM_ID.
TEST_F() [18/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataAccessorsTest , GetName_EmptyString)
{
    rbac::RBACData data(1, "", TEST_REALM_ID, 0);
    EXPECT_EQ(data.GetName(), "");
}
References rbac::RBACData::GetName(), and TEST_REALM_ID.
TEST_F() [19/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataAccessorsTest , GetName_ReturnsAccountName)
{
    rbac::RBACData data(42, "MyAccount", TEST_REALM_ID, 0);
    EXPECT_EQ(data.GetName(), "MyAccount");
}
References rbac::RBACData::GetName(), and TEST_REALM_ID.
TEST_F() [20/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataAccessorsTest , GrantedDeniedGlobal_AllConsistent)
{
    rbac::RBACData data(1, "Test", TEST_REALM_ID, 0);
    data.GrantPermission(TEST_PERM_1);
    EXPECT_EQ(data.GetGrantedPermissions().size(), 1u);
    EXPECT_TRUE(data.GetDeniedPermissions().empty());
    // Before recalculate, global perms are still empty
    EXPECT_TRUE(data.GetPermissions().empty());
    data.RecalculatePermissions();
    // After recalculate, global perms reflect granted
    EXPECT_EQ(data.GetPermissions().size(), 1u);
    EXPECT_TRUE(data.HasPermission(TEST_PERM_1));
}
References rbac::RBACData::GetDeniedPermissions(), rbac::RBACData::GetGrantedPermissions(), rbac::RBACData::GetPermissions(), rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), TEST_PERM_1, and TEST_REALM_ID.
TEST_F() [21/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , Constructor_SetsAccountData)
{
    EXPECT_EQ(rbacData->GetId(), TEST_ACCOUNT_ID);
    EXPECT_EQ(rbacData->GetName(), TEST_ACCOUNT_NAME);
    EXPECT_EQ(rbacData->GetSecurityLevel(), TEST_SEC_LEVEL);
}
References TEST_ACCOUNT_ID, TEST_ACCOUNT_NAME, and TEST_SEC_LEVEL.
TEST_F() [22/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , DenyPermission_AlreadyDenied_ReturnsError)
{
    rbacData->DenyPermission(TEST_PERM_1);
    rbac::RBACCommandResult result = rbacData->DenyPermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_CANT_ADD_ALREADY_ADDED);
}
References rbac::RBAC_CANT_ADD_ALREADY_ADDED, and TEST_PERM_1.
TEST_F() [23/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , DenyPermission_InvalidId_ReturnsError)
{
    rbac::RBACCommandResult result = rbacData->DenyPermission(TEST_PERM_INVALID);
    EXPECT_EQ(result, rbac::RBAC_ID_DOES_NOT_EXISTS);
}
References rbac::RBAC_ID_DOES_NOT_EXISTS, and TEST_PERM_INVALID.
TEST_F() [24/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , DenyPermission_Success)
{
    rbac::RBACCommandResult result = rbacData->DenyPermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_OK);
    EXPECT_TRUE(rbacData->GetDeniedPermissions().count(TEST_PERM_1) > 0);
}
References rbac::RBAC_OK, and TEST_PERM_1.
TEST_F() [25/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , DenyPermission_WhenGranted_ReturnsError)
{
    rbacData->GrantPermission(TEST_PERM_1);
    rbac::RBACCommandResult result = rbacData->DenyPermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_IN_GRANTED_LIST);
}
References rbac::RBAC_IN_GRANTED_LIST, and TEST_PERM_1.
TEST_F() [26/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , GrantPermission_AlreadyGranted_ReturnsError)
{
    rbacData->GrantPermission(TEST_PERM_1);
    rbac::RBACCommandResult result = rbacData->GrantPermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_CANT_ADD_ALREADY_ADDED);
}
References rbac::RBAC_CANT_ADD_ALREADY_ADDED, and TEST_PERM_1.
TEST_F() [27/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , GrantPermission_InvalidId_ReturnsError)
{
    rbac::RBACCommandResult result = rbacData->GrantPermission(TEST_PERM_INVALID);
    EXPECT_EQ(result, rbac::RBAC_ID_DOES_NOT_EXISTS);
}
References rbac::RBAC_ID_DOES_NOT_EXISTS, and TEST_PERM_INVALID.
TEST_F() [28/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , GrantPermission_Success)
{
    rbac::RBACCommandResult result = rbacData->GrantPermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_OK);
    EXPECT_TRUE(rbacData->GetGrantedPermissions().count(TEST_PERM_1) > 0);
}
References rbac::RBAC_OK, and TEST_PERM_1.
TEST_F() [29/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , GrantPermission_WhenDenied_ReturnsError)
{
    rbacData->DenyPermission(TEST_PERM_1);
    rbac::RBACCommandResult result = rbacData->GrantPermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_IN_DENIED_LIST);
}
References rbac::RBAC_IN_DENIED_LIST, and TEST_PERM_1.
TEST_F() [30/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , HasPermission_WhenDenied_ReturnsFalse)
{
    rbacData->DenyPermission(TEST_PERM_1);
    rbacData->RecalculatePermissions();
    EXPECT_FALSE(rbacData->HasPermission(TEST_PERM_1));
}
References TEST_PERM_1.
TEST_F() [31/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , HasPermission_WhenGranted_ReturnsTrue)
{
    rbacData->GrantPermission(TEST_PERM_1);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(TEST_PERM_1));
}
References TEST_PERM_1.
TEST_F() [32/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , HasPermission_WhenNotSet_ReturnsFalse)
{
    EXPECT_FALSE(rbacData->HasPermission(TEST_PERM_1));
}
References TEST_PERM_1.
TEST_F() [33/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , InitialState_EmptyPermissions)
{
    EXPECT_TRUE(rbacData->GetGrantedPermissions().empty());
    EXPECT_TRUE(rbacData->GetDeniedPermissions().empty());
}
TEST_F() [34/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , MultiplePermissions_IndependentTracking)
{
    rbacData->GrantPermission(TEST_PERM_1);
    rbacData->DenyPermission(TEST_PERM_2);
    rbacData->GrantPermission(TEST_PERM_3);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(TEST_PERM_1));
    EXPECT_FALSE(rbacData->HasPermission(TEST_PERM_2));
    EXPECT_TRUE(rbacData->HasPermission(TEST_PERM_3));
    EXPECT_EQ(rbacData->GetGrantedPermissions().size(), 2u);
    EXPECT_EQ(rbacData->GetDeniedPermissions().size(), 1u);
}
References TEST_PERM_1, TEST_PERM_2, and TEST_PERM_3.
TEST_F() [35/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , RevokeAndDeny_WorksCorrectly)
{
    rbacData->GrantPermission(TEST_PERM_1);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(TEST_PERM_1));
    rbacData->RevokePermission(TEST_PERM_1);
    rbacData->RecalculatePermissions();
    EXPECT_FALSE(rbacData->HasPermission(TEST_PERM_1));
    // Now can deny
    rbac::RBACCommandResult result = rbacData->DenyPermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_OK);
    rbacData->RecalculatePermissions();
    EXPECT_FALSE(rbacData->HasPermission(TEST_PERM_1));
    EXPECT_TRUE(rbacData->GetDeniedPermissions().count(TEST_PERM_1) > 0);
}
References rbac::RBAC_OK, and TEST_PERM_1.
TEST_F() [36/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , RevokeAndRegrant_WorksCorrectly)
{
    rbacData->GrantPermission(TEST_PERM_1);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(TEST_PERM_1));
    rbacData->RevokePermission(TEST_PERM_1);
    rbacData->RecalculatePermissions();
    EXPECT_FALSE(rbacData->HasPermission(TEST_PERM_1));
    // Now can grant again
    rbac::RBACCommandResult result = rbacData->GrantPermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_OK);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(TEST_PERM_1));
}
References rbac::RBAC_OK, and TEST_PERM_1.
TEST_F() [37/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , RevokePermission_FromDenied_Success)
{
    rbacData->DenyPermission(TEST_PERM_1);
    rbac::RBACCommandResult result = rbacData->RevokePermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_OK);
    EXPECT_TRUE(rbacData->GetDeniedPermissions().empty());
}
References rbac::RBAC_OK, and TEST_PERM_1.
TEST_F() [38/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , RevokePermission_FromGranted_Success)
{
    rbacData->GrantPermission(TEST_PERM_1);
    rbac::RBACCommandResult result = rbacData->RevokePermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_OK);
    EXPECT_TRUE(rbacData->GetGrantedPermissions().empty());
}
References rbac::RBAC_OK, and TEST_PERM_1.
TEST_F() [39/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDataTest , RevokePermission_NotInList_ReturnsError)
{
    rbac::RBACCommandResult result = rbacData->RevokePermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_CANT_REVOKE_NOT_IN_LIST);
}
References rbac::RBAC_CANT_REVOKE_NOT_IN_LIST, and TEST_PERM_1.
TEST_F() [40/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDefaultPermissionsTest , GetDefaultPermissions_EmptySecLevel_ReturnsEmpty)
{
    // Security level 255 has no default permissions set
    rbac::RBACPermissionContainer const& emptyPerms = sAccountMgr->GetRBACDefaultPermissions(255);
    EXPECT_TRUE(emptyPerms.empty());
}
References sAccountMgr.
TEST_F() [41/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDefaultPermissionsTest , GetDefaultPermissions_ReturnsCorrectSet)
{
    rbac::RBACPermissionContainer const& playerPerms = sAccountMgr->GetRBACDefaultPermissions(SEC_PLAYER);
    EXPECT_EQ(playerPerms.size(), 2u);
    EXPECT_TRUE(playerPerms.count(PERM_PLAYER_1) > 0);
    EXPECT_TRUE(playerPerms.count(PERM_PLAYER_2) > 0);
    rbac::RBACPermissionContainer const& modPerms = sAccountMgr->GetRBACDefaultPermissions(SEC_MODERATOR);
    EXPECT_EQ(modPerms.size(), 1u);
    EXPECT_TRUE(modPerms.count(PERM_MOD_1) > 0);
    rbac::RBACPermissionContainer const& gmPerms = sAccountMgr->GetRBACDefaultPermissions(SEC_GAMEMASTER);
    EXPECT_EQ(gmPerms.size(), 1u);
    EXPECT_TRUE(gmPerms.count(PERM_GM_1) > 0);
    rbac::RBACPermissionContainer const& adminPerms = sAccountMgr->GetRBACDefaultPermissions(SEC_ADMINISTRATOR);
    EXPECT_EQ(adminPerms.size(), 1u);
    EXPECT_TRUE(adminPerms.count(PERM_ADMIN_1) > 0);
}
References sAccountMgr, SEC_ADMINISTRATOR, SEC_GAMEMASTER, SEC_MODERATOR, and SEC_PLAYER.
TEST_F() [42/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDefaultPermissionsTest , HigherSecLevel_GetsOnlyOwnDefaults)
{
    // Create RBACData for an admin account (sec level 3)
    rbac::RBACData adminData(4, "AdminAccount", TEST_REALM_ID, SEC_ADMINISTRATOR);
    // Manually grant the default permissions for admin level
    rbac::RBACPermissionContainer const& adminDefaults = sAccountMgr->GetRBACDefaultPermissions(SEC_ADMINISTRATOR);
    for (uint32 perm : adminDefaults)
        adminData.GrantPermission(perm);
    adminData.RecalculatePermissions();
    // Admin gets their own default permissions
    EXPECT_TRUE(adminData.HasPermission(PERM_ADMIN_1));
    // Note: In a real setup, admin would typically have a role that links to
    // lower permissions. Here we're just testing that default permissions
    // are applied per security level, not inherited.
    // Without explicit roles linking them, admin doesn't automatically get
    // player/mod/gm permissions.
    EXPECT_FALSE(adminData.HasPermission(PERM_PLAYER_1));
    EXPECT_FALSE(adminData.HasPermission(PERM_MOD_1));
    EXPECT_FALSE(adminData.HasPermission(PERM_GM_1));
}
References rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), sAccountMgr, SEC_ADMINISTRATOR, and TEST_REALM_ID.
TEST_F() [43/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDefaultPermissionsTest , SecurityLevel_DeterminesDefaultPermissions)
{
    // Create RBACData for a player account (sec level 0)
    rbac::RBACData playerData(1, "PlayerAccount", TEST_REALM_ID, SEC_PLAYER);
    // Manually grant the default permissions (simulating LoadFromDBCallback)
    rbac::RBACPermissionContainer const& playerDefaults = sAccountMgr->GetRBACDefaultPermissions(SEC_PLAYER);
    for (uint32 perm : playerDefaults)
        playerData.GrantPermission(perm);
    playerData.RecalculatePermissions();
    // Player should have player permissions
    EXPECT_TRUE(playerData.HasPermission(PERM_PLAYER_1));
    EXPECT_TRUE(playerData.HasPermission(PERM_PLAYER_2));
    // Player should NOT have higher level permissions
    EXPECT_FALSE(playerData.HasPermission(PERM_MOD_1));
    EXPECT_FALSE(playerData.HasPermission(PERM_GM_1));
    EXPECT_FALSE(playerData.HasPermission(PERM_ADMIN_1));
}
References rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), sAccountMgr, SEC_PLAYER, and TEST_REALM_ID.
TEST_F() [44/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDefaultPermissionsWithRolesTest , DefaultRole_DenyLinkedChild)
{
    rbac::RBACData data(1, "Player", TEST_REALM_ID, SEC_PLAYER);
    rbac::RBACPermissionContainer const& defaults = sAccountMgr->GetRBACDefaultPermissions(SEC_PLAYER);
    for (uint32 perm : defaults)
        data.GrantPermission(perm);
    data.DenyPermission(PERM_B);
    data.RecalculatePermissions();
    EXPECT_TRUE(data.HasPermission(ROLE_PLAYER));
    EXPECT_TRUE(data.HasPermission(PERM_A));
    EXPECT_FALSE(data.HasPermission(PERM_B));
}
References rbac::RBACData::DenyPermission(), rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), sAccountMgr, SEC_PLAYER, and TEST_REALM_ID.
TEST_F() [45/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDefaultPermissionsWithRolesTest , DefaultRoleExpandsLinked)
{
    rbac::RBACData data(1, "Player", TEST_REALM_ID, SEC_PLAYER);
    // Simulate LoadFromDBCallback: grant defaults then recalculate
    rbac::RBACPermissionContainer const& defaults = sAccountMgr->GetRBACDefaultPermissions(SEC_PLAYER);
    for (uint32 perm : defaults)
        data.GrantPermission(perm);
    data.RecalculatePermissions();
    EXPECT_TRUE(data.HasPermission(ROLE_PLAYER));
    EXPECT_TRUE(data.HasPermission(PERM_A));
    EXPECT_TRUE(data.HasPermission(PERM_B));
}
References rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), sAccountMgr, SEC_PLAYER, and TEST_REALM_ID.
TEST_F() [46/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDefaultPermissionsWithRolesTest , SecLevels_NoCrossContamination)
{
    rbac::RBACData playerData(1, "Player", TEST_REALM_ID, SEC_PLAYER);
    rbac::RBACData modData(2, "Mod", TEST_REALM_ID, SEC_MODERATOR);
    // Grant defaults for each
    for (uint32 p : sAccountMgr->GetRBACDefaultPermissions(SEC_PLAYER))
        playerData.GrantPermission(p);
    playerData.RecalculatePermissions();
    for (uint32 p : sAccountMgr->GetRBACDefaultPermissions(SEC_MODERATOR))
        modData.GrantPermission(p);
    modData.RecalculatePermissions();
    // Player has player perms, not mod perms
    EXPECT_TRUE(playerData.HasPermission(PERM_A));
    EXPECT_FALSE(playerData.HasPermission(PERM_MOD_1));
    // Mod has mod perms, not player perms (unless explicitly granted)
    EXPECT_TRUE(modData.HasPermission(PERM_MOD_1));
    EXPECT_FALSE(modData.HasPermission(PERM_A));
}
References rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), sAccountMgr, SEC_MODERATOR, SEC_PLAYER, and TEST_REALM_ID.
TEST_F() [47/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDeniedExpansionTest , DenyRole_ExpandsDeniedLinkedPermissions)
{
    // First grant individual permissions that would be linked from GM
    rbacData->GrantPermission(PERM_KICK);
    rbacData->GrantPermission(PERM_BAN);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(PERM_KICK));
    EXPECT_TRUE(rbacData->HasPermission(PERM_BAN));
    // Now deny the GM role
    rbacData->DenyPermission(ROLE_GM);
    rbacData->RecalculatePermissions();
    // The GM role and its linked permissions should be denied
    // Even though kick/ban were granted individually, denying the role
    // that links them should expand to deny those permissions
    EXPECT_FALSE(rbacData->HasPermission(ROLE_GM));
    EXPECT_FALSE(rbacData->HasPermission(PERM_KICK));
    EXPECT_FALSE(rbacData->HasPermission(PERM_BAN));
}
TEST_F() [48/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDeniedExpansionTest , GrantAndDenySameRole_DenyWins)
{
    // Grant the GM role
    rbacData->GrantPermission(ROLE_GM);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(ROLE_GM));
    EXPECT_TRUE(rbacData->HasPermission(PERM_KICK));
    // Revoke and then deny
    rbacData->RevokePermission(ROLE_GM);
    rbacData->DenyPermission(ROLE_GM);
    rbacData->RecalculatePermissions();
    // Deny should win - no access
    EXPECT_FALSE(rbacData->HasPermission(ROLE_GM));
    EXPECT_FALSE(rbacData->HasPermission(PERM_KICK));
    EXPECT_FALSE(rbacData->HasPermission(PERM_BAN));
}
TEST_F() [49/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDenySpecificFromRoleTest , DenyOneChild_SiblingsStillGranted)
{
    rbacData->GrantPermission(ROLE_MOD);
    rbacData->DenyPermission(PERM_BAN);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(ROLE_MOD));
    EXPECT_TRUE(rbacData->HasPermission(PERM_KICK));
    EXPECT_TRUE(rbacData->HasPermission(PERM_MUTE));
    EXPECT_FALSE(rbacData->HasPermission(PERM_BAN));
}
TEST_F() [50/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDenySpecificFromRoleTest , DenyPermNotInRole_RolePermsUnaffected)
{
    rbacData->GrantPermission(ROLE_MOD);
    rbacData->DenyPermission(PERM_SHUTDOWN);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(ROLE_MOD));
    EXPECT_TRUE(rbacData->HasPermission(PERM_KICK));
    EXPECT_TRUE(rbacData->HasPermission(PERM_BAN));
    EXPECT_TRUE(rbacData->HasPermission(PERM_MUTE));
    EXPECT_FALSE(rbacData->HasPermission(PERM_SHUTDOWN));
}
TEST_F() [51/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDenySpecificFromRoleTest , GrantTwoRoles_DenyOneRole)
{
    rbacData->GrantPermission(ROLE_MOD);
    rbacData->GrantPermission(ROLE_ADMIN);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(PERM_SHUTDOWN));
    EXPECT_TRUE(rbacData->HasPermission(PERM_KICK));
    // Revoke and deny ROLE_ADMIN
    rbacData->RevokePermission(ROLE_ADMIN);
    rbacData->DenyPermission(ROLE_ADMIN);
    rbacData->RecalculatePermissions();
    // ROLE_ADMIN and its unique perm (SHUTDOWN) denied
    EXPECT_FALSE(rbacData->HasPermission(ROLE_ADMIN));
    EXPECT_FALSE(rbacData->HasPermission(PERM_SHUTDOWN));
    // ROLE_MOD perms remain
    EXPECT_TRUE(rbacData->HasPermission(ROLE_MOD));
    EXPECT_TRUE(rbacData->HasPermission(PERM_KICK));
    EXPECT_TRUE(rbacData->HasPermission(PERM_BAN));
    EXPECT_TRUE(rbacData->HasPermission(PERM_MUTE));
}
TEST_F() [52/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDoubleRevokeTest , RevokeDeniedTwice_SecondFails)
{
    rbacData->DenyPermission(TEST_PERM_1);
    EXPECT_EQ(rbacData->RevokePermission(TEST_PERM_1), rbac::RBAC_OK);
    EXPECT_EQ(rbacData->RevokePermission(TEST_PERM_1), rbac::RBAC_CANT_REVOKE_NOT_IN_LIST);
}
References rbac::RBAC_CANT_REVOKE_NOT_IN_LIST, rbac::RBAC_OK, and TEST_PERM_1.
TEST_F() [53/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACDoubleRevokeTest , RevokeGrantedTwice_SecondFails)
{
    rbacData->GrantPermission(TEST_PERM_1);
    EXPECT_EQ(rbacData->RevokePermission(TEST_PERM_1), rbac::RBAC_OK);
    EXPECT_EQ(rbacData->RevokePermission(TEST_PERM_1), rbac::RBAC_CANT_REVOKE_NOT_IN_LIST);
}
References rbac::RBAC_CANT_REVOKE_NOT_IN_LIST, rbac::RBAC_OK, and TEST_PERM_1.
TEST_F() [54/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACEmptyAndBoundaryTest , FreshData_AllEmpty)
{
    EXPECT_TRUE(rbacData->GetGrantedPermissions().empty());
    EXPECT_TRUE(rbacData->GetDeniedPermissions().empty());
    EXPECT_TRUE(rbacData->GetPermissions().empty());
}
TEST_F() [55/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACEmptyAndBoundaryTest , GrantDenyRevokeSequence)
{
    rbac::RBACCommandResult r1 = rbacData->GrantPermission(TEST_PERM_1);
    EXPECT_EQ(r1, rbac::RBAC_OK);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(TEST_PERM_1));
    rbac::RBACCommandResult r2 = rbacData->RevokePermission(TEST_PERM_1);
    EXPECT_EQ(r2, rbac::RBAC_OK);
    rbac::RBACCommandResult r3 = rbacData->DenyPermission(TEST_PERM_1);
    EXPECT_EQ(r3, rbac::RBAC_OK);
    rbacData->RecalculatePermissions();
    EXPECT_FALSE(rbacData->HasPermission(TEST_PERM_1));
    rbac::RBACCommandResult r4 = rbacData->RevokePermission(TEST_PERM_1);
    EXPECT_EQ(r4, rbac::RBAC_OK);
    rbacData->RecalculatePermissions();
    EXPECT_FALSE(rbacData->HasPermission(TEST_PERM_1));
}
References rbac::RBAC_OK, and TEST_PERM_1.
TEST_F() [56/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACEmptyAndBoundaryTest , HasPermission_Max_ReturnsFalse)
{
    EXPECT_FALSE(rbacData->HasPermission(rbac::RBAC_PERM_MAX));
}
References rbac::RBAC_PERM_MAX.
TEST_F() [57/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACEmptyAndBoundaryTest , HasPermission_Zero_ReturnsFalse)
{
    EXPECT_FALSE(rbacData->HasPermission(0));
}
TEST_F() [58/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACEmptyAndBoundaryTest , MultipleRecalculates_Idempotent)
{
    rbacData->GrantPermission(TEST_PERM_1);
    rbacData->RecalculatePermissions();
    auto perms1 = rbacData->GetPermissions();
    rbacData->RecalculatePermissions();
    auto perms2 = rbacData->GetPermissions();
    rbacData->RecalculatePermissions();
    auto perms3 = rbacData->GetPermissions();
    EXPECT_EQ(perms1, perms2);
    EXPECT_EQ(perms2, perms3);
}
References TEST_PERM_1.
TEST_F() [59/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACEmptyAndBoundaryTest , RecalculateOnEmpty_Safe)
{
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->GetPermissions().empty());
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->GetPermissions().empty());
}
TEST_F() [60/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACExpandPermissionsDanglingLinkTest , DanglingLink_SkippedGracefully)
{
    rbacData->GrantPermission(ROLE_WITH_DANGLING);
    rbacData->RecalculatePermissions();
    // Valid perm expanded, dangling silently skipped
    EXPECT_TRUE(rbacData->HasPermission(ROLE_WITH_DANGLING));
    EXPECT_TRUE(rbacData->HasPermission(PERM_VALID));
    EXPECT_FALSE(rbacData->HasPermission(PERM_DANGLING));
    // Only 2: the role + the valid perm (dangling not included)
    EXPECT_EQ(rbacData->GetPermissions().size(), 2u);
}
TEST_F() [61/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACExpandPermissionsDanglingLinkTest , DenyDanglingLink_SkippedGracefully)
{
    rbacData->GrantPermission(PERM_VALID);
    // PERM_DANGLING can't be denied since it's not registered
    rbac::RBACCommandResult result = rbacData->DenyPermission(PERM_DANGLING);
    EXPECT_EQ(result, rbac::RBAC_ID_DOES_NOT_EXISTS);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(PERM_VALID));
}
References rbac::RBAC_ID_DOES_NOT_EXISTS.
TEST_F() [62/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACFullRoleHierarchyTest , GrantAdmin_DenyModRole_ModAndPlayerDenied)
{
    rbac::RBACData data(1, "Admin", TEST_REALM_ID, 0);
    data.GrantPermission(ROLE_ADMIN);
    data.DenyPermission(ROLE_MOD);
    data.RecalculatePermissions();
    // Admin + GM perms remain
    EXPECT_TRUE(data.HasPermission(ROLE_ADMIN));
    EXPECT_TRUE(data.HasPermission(ROLE_GM));
    EXPECT_TRUE(data.HasPermission(PERM_GM_1));
    EXPECT_TRUE(data.HasPermission(PERM_GM_2));
    EXPECT_TRUE(data.HasPermission(PERM_ADMIN_1));
    EXPECT_TRUE(data.HasPermission(PERM_ADMIN_2));
    // Mod role and its full chain denied (Mod + Player perms)
    EXPECT_FALSE(data.HasPermission(ROLE_MOD));
    EXPECT_FALSE(data.HasPermission(ROLE_PLAYER));
    EXPECT_FALSE(data.HasPermission(PERM_MOD_1));
    EXPECT_FALSE(data.HasPermission(PERM_MOD_2));
    EXPECT_FALSE(data.HasPermission(PERM_PLAYER_1));
    EXPECT_FALSE(data.HasPermission(PERM_PLAYER_2));
}
References rbac::RBACData::DenyPermission(), rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), and TEST_REALM_ID.
TEST_F() [63/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACFullRoleHierarchyTest , GrantAdmin_DenyOneCommandPerm)
{
    rbac::RBACData data(1, "Admin", TEST_REALM_ID, 0);
    data.GrantPermission(ROLE_ADMIN);
    data.DenyPermission(PERM_GM_1);
    data.RecalculatePermissions();
    // Only PERM_GM_1 is denied
    EXPECT_FALSE(data.HasPermission(PERM_GM_1));
    // Everything else still works
    EXPECT_TRUE(data.HasPermission(ROLE_ADMIN));
    EXPECT_TRUE(data.HasPermission(ROLE_GM));
    EXPECT_TRUE(data.HasPermission(ROLE_MOD));
    EXPECT_TRUE(data.HasPermission(ROLE_PLAYER));
    EXPECT_TRUE(data.HasPermission(PERM_GM_2));
    EXPECT_TRUE(data.HasPermission(PERM_ADMIN_1));
    EXPECT_TRUE(data.HasPermission(PERM_ADMIN_2));
    EXPECT_TRUE(data.HasPermission(PERM_MOD_1));
    EXPECT_TRUE(data.HasPermission(PERM_PLAYER_1));
    // 11 total: 12 - 1 denied
    EXPECT_EQ(data.GetPermissions().size(), 11u);
}
References rbac::RBACData::DenyPermission(), rbac::RBACData::GetPermissions(), rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), and TEST_REALM_ID.
TEST_F() [64/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACFullRoleHierarchyTest , GrantAdminRole_AllPerms)
{
    rbac::RBACData data(1, "Admin", TEST_REALM_ID, 0);
    data.GrantPermission(ROLE_ADMIN);
    data.RecalculatePermissions();
    EXPECT_TRUE(data.HasPermission(ROLE_ADMIN));
    EXPECT_TRUE(data.HasPermission(ROLE_GM));
    EXPECT_TRUE(data.HasPermission(ROLE_MOD));
    EXPECT_TRUE(data.HasPermission(ROLE_PLAYER));
    EXPECT_TRUE(data.HasPermission(PERM_PLAYER_1));
    EXPECT_TRUE(data.HasPermission(PERM_PLAYER_2));
    EXPECT_TRUE(data.HasPermission(PERM_MOD_1));
    EXPECT_TRUE(data.HasPermission(PERM_MOD_2));
    EXPECT_TRUE(data.HasPermission(PERM_GM_1));
    EXPECT_TRUE(data.HasPermission(PERM_GM_2));
    EXPECT_TRUE(data.HasPermission(PERM_ADMIN_1));
    EXPECT_TRUE(data.HasPermission(PERM_ADMIN_2));
    // 12 total: 4 roles + 8 perms
    EXPECT_EQ(data.GetPermissions().size(), 12u);
}
References rbac::RBACData::GetPermissions(), rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), and TEST_REALM_ID.
TEST_F() [65/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACFullRoleHierarchyTest , GrantGMRole_FullChain)
{
    rbac::RBACData data(1, "GM", TEST_REALM_ID, 0);
    data.GrantPermission(ROLE_GM);
    data.RecalculatePermissions();
    // GM + Mod + Player perms
    EXPECT_TRUE(data.HasPermission(ROLE_GM));
    EXPECT_TRUE(data.HasPermission(ROLE_MOD));
    EXPECT_TRUE(data.HasPermission(ROLE_PLAYER));
    EXPECT_TRUE(data.HasPermission(PERM_PLAYER_1));
    EXPECT_TRUE(data.HasPermission(PERM_PLAYER_2));
    EXPECT_TRUE(data.HasPermission(PERM_MOD_1));
    EXPECT_TRUE(data.HasPermission(PERM_MOD_2));
    EXPECT_TRUE(data.HasPermission(PERM_GM_1));
    EXPECT_TRUE(data.HasPermission(PERM_GM_2));
    EXPECT_FALSE(data.HasPermission(PERM_ADMIN_1));
    EXPECT_FALSE(data.HasPermission(PERM_ADMIN_2));
    // 9 total: 3 roles + 6 perms
    EXPECT_EQ(data.GetPermissions().size(), 9u);
}
References rbac::RBACData::GetPermissions(), rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), and TEST_REALM_ID.
TEST_F() [66/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACFullRoleHierarchyTest , GrantPlayerRole_OnlyPlayerPerms)
{
    rbac::RBACData data(1, "Player", TEST_REALM_ID, 0);
    data.GrantPermission(ROLE_PLAYER);
    data.RecalculatePermissions();
    EXPECT_TRUE(data.HasPermission(ROLE_PLAYER));
    EXPECT_TRUE(data.HasPermission(PERM_PLAYER_1));
    EXPECT_TRUE(data.HasPermission(PERM_PLAYER_2));
    EXPECT_FALSE(data.HasPermission(PERM_MOD_1));
    EXPECT_FALSE(data.HasPermission(PERM_GM_1));
    EXPECT_FALSE(data.HasPermission(PERM_ADMIN_1));
    // 3 total: ROLE_PLAYER + 2 player perms
    EXPECT_EQ(data.GetPermissions().size(), 3u);
}
References rbac::RBACData::GetPermissions(), rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), and TEST_REALM_ID.
TEST_F() [67/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACGetPermissionsTest , Empty_WhenNothingGranted)
{
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->GetPermissions().empty());
}
TEST_F() [68/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACGetPermissionsTest , ExcludesDeniedPermissions)
{
    rbacData->GrantPermission(PERM_A);
    rbacData->GrantPermission(PERM_C);
    rbacData->DenyPermission(PERM_B);
    rbacData->RecalculatePermissions();
    auto const& perms = rbacData->GetPermissions();
    EXPECT_TRUE(perms.count(PERM_A) > 0);
    EXPECT_TRUE(perms.count(PERM_C) > 0);
    EXPECT_EQ(perms.count(PERM_B), 0u);
}
TEST_F() [69/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACGetPermissionsTest , IncludesExpandedLinkedPermissions)
{
    rbacData->GrantPermission(ROLE_R);
    rbacData->RecalculatePermissions();
    auto const& perms = rbacData->GetPermissions();
    EXPECT_TRUE(perms.count(ROLE_R) > 0);
    EXPECT_TRUE(perms.count(PERM_A) > 0);
    EXPECT_TRUE(perms.count(PERM_B) > 0);
    EXPECT_EQ(perms.count(PERM_C), 0u);
}
TEST_F() [70/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACGetPermissionsTest , MatchesHasPermission)
{
    rbacData->GrantPermission(PERM_A);
    rbacData->GrantPermission(PERM_C);
    rbacData->RecalculatePermissions();
    auto const& perms = rbacData->GetPermissions();
    for (uint32 p : perms)
        EXPECT_TRUE(rbacData->HasPermission(p));
    EXPECT_FALSE(rbacData->HasPermission(PERM_B));
}
TEST_F() [71/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACGetPermissionsTest , ReflectsStateAfterRecalculate)
{
    rbacData->GrantPermission(PERM_A);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->GetPermissions().count(PERM_A) > 0);
    rbacData->RevokePermission(PERM_A);
    rbacData->RecalculatePermissions();
    EXPECT_EQ(rbacData->GetPermissions().count(PERM_A), 0u);
}
TEST_F() [72/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACLinkedPermissionsTest , DeniedPermission_IsInDeniedList)
{
    rbacData->DenyPermission(TEST_PERM_1);
    auto const& denied = rbacData->GetDeniedPermissions();
    EXPECT_TRUE(denied.count(TEST_PERM_1) > 0);
}
References TEST_PERM_1.
TEST_F() [73/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACLinkedPermissionsTest , DeniedPermission_OverridesGranted)
{
    // Grant permission, then revoke and deny
    rbacData->GrantPermission(TEST_PERM_1);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(TEST_PERM_1));
    rbacData->RevokePermission(TEST_PERM_1);
    rbacData->DenyPermission(TEST_PERM_1);
    rbacData->RecalculatePermissions();
    EXPECT_FALSE(rbacData->HasPermission(TEST_PERM_1));
}
References TEST_PERM_1.
TEST_F() [74/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACLinkedPermissionsTest , GrantedPermission_IsInGrantedList)
{
    rbacData->GrantPermission(TEST_PERM_1);
    auto const& granted = rbacData->GetGrantedPermissions();
    EXPECT_TRUE(granted.count(TEST_PERM_1) > 0);
}
References TEST_PERM_1.
TEST_F() [75/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACLoadFromDBCallbackSimulationTest , NullResult_AppliesDefaultsAndRecalculates)
{
    rbac::RBACData data(1, "Player", TEST_REALM_ID, SEC_PLAYER);
    // Simulate LoadFromDBCallback with no DB rows (nullptr result)
    data.LoadFromDBCallback(nullptr);
    // Default permission (ROLE_PLAYER) should be granted and expanded
    EXPECT_TRUE(data.HasPermission(ROLE_PLAYER));
    EXPECT_TRUE(data.HasPermission(PERM_A));
    EXPECT_TRUE(data.HasPermission(PERM_B));
    EXPECT_EQ(data.GetPermissions().size(), 3u);
}
References rbac::RBACData::GetPermissions(), rbac::RBACData::HasPermission(), rbac::RBACData::LoadFromDBCallback(), SEC_PLAYER, and TEST_REALM_ID.
TEST_F() [76/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACLoadFromDBCallbackSimulationTest , NullResult_NoDefaultsForHighSecLevel)
{
    // Sec level 3 has no defaults configured
    rbac::RBACData data(1, "Admin", TEST_REALM_ID, 3);
    data.LoadFromDBCallback(nullptr);
    EXPECT_TRUE(data.GetPermissions().empty());
}
References rbac::RBACData::GetPermissions(), rbac::RBACData::LoadFromDBCallback(), and TEST_REALM_ID.
TEST_F() [77/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACMultipleInstancesIndependenceTest , ModifyingOne_DoesNotAffectOther)
{
    rbac::RBACData data1(1, "Account1", TEST_REALM_ID, 0);
    rbac::RBACData data2(2, "Account2", TEST_REALM_ID, 0);
    data1.GrantPermission(TEST_PERM_1);
    data1.GrantPermission(TEST_PERM_2);
    data2.GrantPermission(TEST_PERM_1);
    data1.RecalculatePermissions();
    data2.RecalculatePermissions();
    // Revoke from data1, data2 unaffected
    data1.RevokePermission(TEST_PERM_1);
    data1.RecalculatePermissions();
    EXPECT_FALSE(data1.HasPermission(TEST_PERM_1));
    EXPECT_TRUE(data2.HasPermission(TEST_PERM_1));
}
References rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), rbac::RBACData::RevokePermission(), TEST_PERM_1, TEST_PERM_2, and TEST_REALM_ID.
TEST_F() [78/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACMultipleInstancesIndependenceTest , TwoInstances_NoCrossContamination)
{
    rbac::RBACData data1(1, "Account1", TEST_REALM_ID, 0);
    rbac::RBACData data2(2, "Account2", TEST_REALM_ID, 0);
    data1.GrantPermission(TEST_PERM_1);
    data2.GrantPermission(TEST_PERM_2);
    data1.RecalculatePermissions();
    data2.RecalculatePermissions();
    EXPECT_TRUE(data1.HasPermission(TEST_PERM_1));
    EXPECT_FALSE(data1.HasPermission(TEST_PERM_2));
    EXPECT_FALSE(data2.HasPermission(TEST_PERM_1));
    EXPECT_TRUE(data2.HasPermission(TEST_PERM_2));
}
References rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), TEST_PERM_1, TEST_PERM_2, and TEST_REALM_ID.
TEST_F() [79/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionDefaultConstructorTest , ConstructorWithIdOnly)
{
    rbac::RBACPermission perm(42);
    EXPECT_EQ(perm.GetId(), 42u);
    EXPECT_EQ(perm.GetName(), "");
    EXPECT_TRUE(perm.GetLinkedPermissions().empty());
}
References rbac::RBACPermission::GetId(), rbac::RBACPermission::GetLinkedPermissions(), and rbac::RBACPermission::GetName().
TEST_F() [80/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionDefaultConstructorTest , DefaultConstructor_ZeroIdEmptyName)
{
    rbac::RBACPermission perm;
    EXPECT_EQ(perm.GetId(), 0u);
    EXPECT_EQ(perm.GetName(), "");
    EXPECT_TRUE(perm.GetLinkedPermissions().empty());
}
References rbac::RBACPermission::GetId(), rbac::RBACPermission::GetLinkedPermissions(), and rbac::RBACPermission::GetName().
TEST_F() [81/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionEnumConsistencyTest , MaxGreaterThanHighestDefined)
{
    EXPECT_GT(static_cast<uint32>(rbac::RBAC_PERM_MAX), 911u);
}
References rbac::RBAC_PERM_MAX.
TEST_F() [82/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionEnumConsistencyTest , NonContiguousIds_Work)
{
    rbac::RBACData data(1, "Test", TEST_REALM_ID, 0);
    data.GrantPermission(500);
    data.GrantPermission(900);
    data.DenyPermission(700);
    data.RecalculatePermissions();
    EXPECT_TRUE(data.HasPermission(500));
    EXPECT_TRUE(data.HasPermission(900));
    EXPECT_FALSE(data.HasPermission(700));
}
References rbac::RBACData::DenyPermission(), rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), and TEST_REALM_ID.
TEST_F() [83/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionEnumConsistencyTest , RoleIdsWithinRange)
{
    EXPECT_LT(static_cast<uint32>(rbac::RBAC_ROLE_ADMINISTRATOR), static_cast<uint32>(rbac::RBAC_PERM_MAX));
    EXPECT_LT(static_cast<uint32>(rbac::RBAC_ROLE_GAMEMASTER), static_cast<uint32>(rbac::RBAC_PERM_MAX));
    EXPECT_LT(static_cast<uint32>(rbac::RBAC_ROLE_MODERATOR), static_cast<uint32>(rbac::RBAC_PERM_MAX));
    EXPECT_LT(static_cast<uint32>(rbac::RBAC_ROLE_PLAYER), static_cast<uint32>(rbac::RBAC_PERM_MAX));
}
References rbac::RBAC_PERM_MAX, rbac::RBAC_ROLE_ADMINISTRATOR, rbac::RBAC_ROLE_GAMEMASTER, rbac::RBAC_ROLE_MODERATOR, and rbac::RBAC_ROLE_PLAYER.
TEST_F() [84/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionExpansionTest , DenyRole_OverridesIndividualGrant)
{
    // Grant kick permission individually
    rbacData->GrantPermission(PERM_KICK);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(PERM_KICK));
    // Deny the GM role (which links to kick)
    rbacData->DenyPermission(ROLE_GM);
    rbacData->RecalculatePermissions();
    // Denying a role expands to deny all linked permissions
    // Even though kick was granted individually, denying GM role
    // expands to deny kick as well (RBAC deny expansion)
    EXPECT_FALSE(rbacData->HasPermission(PERM_KICK));
    EXPECT_FALSE(rbacData->HasPermission(ROLE_GM));
    EXPECT_FALSE(rbacData->HasPermission(PERM_BAN));
}
TEST_F() [85/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionExpansionTest , DenyRole_PreventsLinkedPermissions)
{
    // Grant teleport individually
    rbacData->GrantPermission(PERM_TELEPORT);
    // Grant admin role (gives kick, ban, shutdown via expansion)
    rbacData->GrantPermission(ROLE_ADMIN);
    rbacData->RecalculatePermissions();
    // Verify all permissions are granted
    EXPECT_TRUE(rbacData->HasPermission(ROLE_ADMIN));
    EXPECT_TRUE(rbacData->HasPermission(PERM_KICK));
    EXPECT_TRUE(rbacData->HasPermission(PERM_TELEPORT));
    // Now revoke admin and deny the GM role
    rbacData->RevokePermission(ROLE_ADMIN);
    rbacData->DenyPermission(ROLE_GM);
    rbacData->RecalculatePermissions();
    // GM role and its linked permissions should be denied
    EXPECT_FALSE(rbacData->HasPermission(ROLE_GM));
    EXPECT_FALSE(rbacData->HasPermission(PERM_KICK));
    EXPECT_FALSE(rbacData->HasPermission(PERM_BAN));
    // Teleport was granted directly, not through GM, so should still work
    EXPECT_TRUE(rbacData->HasPermission(PERM_TELEPORT));
}
TEST_F() [86/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionExpansionTest , GrantRole_ExpandsLinkedPermissions)
{
    // Grant GM role
    rbacData->GrantPermission(ROLE_GM);
    rbacData->RecalculatePermissions();
    // Should have access to GM role and linked permissions (kick, ban)
    EXPECT_TRUE(rbacData->HasPermission(ROLE_GM));
    EXPECT_TRUE(rbacData->HasPermission(PERM_KICK));
    EXPECT_TRUE(rbacData->HasPermission(PERM_BAN));
    // Should NOT have access to unlinked permissions
    EXPECT_FALSE(rbacData->HasPermission(PERM_SHUTDOWN));
    EXPECT_FALSE(rbacData->HasPermission(PERM_TELEPORT));
}
TEST_F() [87/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionExpansionTest , GrantRole_RecursiveExpansion)
{
    // Grant Admin role (which links to GM role, which links to kick/ban)
    rbacData->GrantPermission(ROLE_ADMIN);
    rbacData->RecalculatePermissions();
    // Should have access to Admin role
    EXPECT_TRUE(rbacData->HasPermission(ROLE_ADMIN));
    // Should have access to directly linked permissions (GM role, shutdown)
    EXPECT_TRUE(rbacData->HasPermission(ROLE_GM));
    EXPECT_TRUE(rbacData->HasPermission(PERM_SHUTDOWN));
    // Should have access to recursively linked permissions (from GM role)
    EXPECT_TRUE(rbacData->HasPermission(PERM_KICK));
    EXPECT_TRUE(rbacData->HasPermission(PERM_BAN));
    // Should NOT have access to unlinked permissions
    EXPECT_FALSE(rbacData->HasPermission(PERM_TELEPORT));
}
TEST_F() [88/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionRemoveLinkedTest , RemoveAll_LeavesEmpty)
{
    permission->RemoveLinkedPermission(TEST_PERM_2);
    permission->RemoveLinkedPermission(TEST_PERM_3);
    EXPECT_TRUE(permission->GetLinkedPermissions().empty());
}
References TEST_PERM_2, and TEST_PERM_3.
TEST_F() [89/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionRemoveLinkedTest , RemoveLinkedPermission_RemovesFromSet)
{
    EXPECT_EQ(permission->GetLinkedPermissions().size(), 2u);
    permission->RemoveLinkedPermission(TEST_PERM_2);
    EXPECT_EQ(permission->GetLinkedPermissions().size(), 1u);
    EXPECT_EQ(permission->GetLinkedPermissions().count(TEST_PERM_2), 0u);
    EXPECT_EQ(permission->GetLinkedPermissions().count(TEST_PERM_3), 1u);
}
References TEST_PERM_2, and TEST_PERM_3.
TEST_F() [90/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionRemoveLinkedTest , RemoveNonExistent_IsNoOp)
{
    permission->RemoveLinkedPermission(TEST_PERM_INVALID);
    EXPECT_EQ(permission->GetLinkedPermissions().size(), 2u);
}
References TEST_PERM_INVALID.
TEST_F() [91/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionTest , AddLinkedPermission_AddsToSet)
{
    permission->AddLinkedPermission(TEST_PERM_2);
    permission->AddLinkedPermission(TEST_PERM_3);
    auto const& linked = permission->GetLinkedPermissions();
    EXPECT_EQ(linked.size(), 2u);
    EXPECT_TRUE(linked.count(TEST_PERM_2) > 0);
    EXPECT_TRUE(linked.count(TEST_PERM_3) > 0);
}
References TEST_PERM_2, and TEST_PERM_3.
TEST_F() [92/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionTest , AddLinkedPermission_NoDuplicates)
{
    permission->AddLinkedPermission(TEST_PERM_2);
    permission->AddLinkedPermission(TEST_PERM_2);
    permission->AddLinkedPermission(TEST_PERM_2);
    EXPECT_EQ(permission->GetLinkedPermissions().size(), 1u);
}
References TEST_PERM_2.
TEST_F() [93/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionTest , Constructor_SetsIdAndName)
{
    EXPECT_EQ(permission->GetId(), TEST_PERM_1);
    EXPECT_EQ(permission->GetName(), "Test Permission");
}
References TEST_PERM_1.
TEST_F() [94/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACPermissionTest , LinkedPermissions_InitiallyEmpty)
{
    EXPECT_TRUE(permission->GetLinkedPermissions().empty());
}
TEST_F() [95/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACRevokeEdgeCasesTest , RevokeDenied_ThenGrant)
{
    rbacData->DenyPermission(TEST_PERM_1);
    rbacData->RecalculatePermissions();
    EXPECT_FALSE(rbacData->HasPermission(TEST_PERM_1));
    rbacData->RevokePermission(TEST_PERM_1);
    rbac::RBACCommandResult result = rbacData->GrantPermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_OK);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(TEST_PERM_1));
}
References rbac::RBAC_OK, and TEST_PERM_1.
TEST_F() [96/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACRevokeEdgeCasesTest , RevokeDoesNotAffectOtherPermissions)
{
    rbacData->GrantPermission(TEST_PERM_1);
    rbacData->GrantPermission(TEST_PERM_2);
    rbacData->DenyPermission(TEST_PERM_3);
    rbacData->RevokePermission(TEST_PERM_1);
    EXPECT_TRUE(rbacData->GetGrantedPermissions().count(TEST_PERM_2) > 0);
    EXPECT_TRUE(rbacData->GetDeniedPermissions().count(TEST_PERM_3) > 0);
    EXPECT_EQ(rbacData->GetGrantedPermissions().count(TEST_PERM_1), 0u);
}
References TEST_PERM_1, TEST_PERM_2, and TEST_PERM_3.
TEST_F() [97/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACRevokeEdgeCasesTest , RevokeFromEmpty_ReturnsError)
{
    rbac::RBACCommandResult result = rbacData->RevokePermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_CANT_REVOKE_NOT_IN_LIST);
}
References rbac::RBAC_CANT_REVOKE_NOT_IN_LIST, and TEST_PERM_1.
TEST_F() [98/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACRevokeEdgeCasesTest , RevokeGranted_ThenDeny)
{
    rbacData->GrantPermission(TEST_PERM_1);
    rbacData->RecalculatePermissions();
    EXPECT_TRUE(rbacData->HasPermission(TEST_PERM_1));
    rbacData->RevokePermission(TEST_PERM_1);
    rbac::RBACCommandResult result = rbacData->DenyPermission(TEST_PERM_1);
    EXPECT_EQ(result, rbac::RBAC_OK);
    rbacData->RecalculatePermissions();
    EXPECT_FALSE(rbacData->HasPermission(TEST_PERM_1));
    EXPECT_TRUE(rbacData->GetDeniedPermissions().count(TEST_PERM_1) > 0);
}
References rbac::RBAC_OK, and TEST_PERM_1.
TEST_F() [99/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACRevokeEdgeCasesTest , RevokeUnregistered_ReturnsCantRevoke)
{
    rbac::RBACCommandResult result = rbacData->RevokePermission(TEST_PERM_INVALID);
    EXPECT_EQ(result, rbac::RBAC_CANT_REVOKE_NOT_IN_LIST);
}
References rbac::RBAC_CANT_REVOKE_NOT_IN_LIST, and TEST_PERM_INVALID.
TEST_F() [100/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACSecurityLevelTest , Constructor_PreservesSecurityLevel)
{
    rbac::RBACData rbacLevel0(1, "Player", 1, 0);
    EXPECT_EQ(rbacLevel0.GetSecurityLevel(), 0);
    rbac::RBACData rbacLevel1(2, "Moderator", 1, 1);
    EXPECT_EQ(rbacLevel1.GetSecurityLevel(), 1);
    rbac::RBACData rbacLevel2(3, "GameMaster", 1, 2);
    EXPECT_EQ(rbacLevel2.GetSecurityLevel(), 2);
    rbac::RBACData rbacLevel3(4, "Administrator", 1, 3);
    EXPECT_EQ(rbacLevel3.GetSecurityLevel(), 3);
}
References rbac::RBACData::GetSecurityLevel().
TEST_F() [101/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACSecurityLevelTest , SetSecurityLevelForTest_UpdatesLevel)
{
    rbac::RBACData rbac(1, "TestAccount", 1, 0);
    EXPECT_EQ(rbac.GetSecurityLevel(), 0);
    // Use test-friendly setter that doesn't call LoadFromDB
    rbac.SetSecurityLevelForTest(3);
    EXPECT_EQ(rbac.GetSecurityLevel(), 3);
}
TEST_F() [102/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACSetSecurityLevelForTestBehaviorTest , DoesNotRecalculate)
{
    rbac::RBACData data(1, "Test", TEST_REALM_ID, 0);
    data.GrantPermission(TEST_PERM_1);
    data.RecalculatePermissions();
    EXPECT_TRUE(data.HasPermission(TEST_PERM_1));
    // Changing sec level via test helper should NOT clear/recalculate perms
    data.SetSecurityLevelForTest(3);
    EXPECT_EQ(data.GetSecurityLevel(), 3);
    EXPECT_TRUE(data.HasPermission(TEST_PERM_1));
}
References rbac::RBACData::GetSecurityLevel(), rbac::RBACData::GrantPermission(), rbac::RBACData::HasPermission(), rbac::RBACData::RecalculatePermissions(), rbac::RBACData::SetSecurityLevelForTest(), TEST_PERM_1, and TEST_REALM_ID.
TEST_F() [103/103]
anonymous_namespace{RBACTest.cpp}::TEST_F (RBACSetSecurityLevelForTestBehaviorTest , UpdatesLevelOnly)
{
    rbac::RBACData data(1, "Test", TEST_REALM_ID, 0);
    EXPECT_EQ(data.GetSecurityLevel(), 0);
    data.SetSecurityLevelForTest(1);
    EXPECT_EQ(data.GetSecurityLevel(), 1);
    data.SetSecurityLevelForTest(255);
    EXPECT_EQ(data.GetSecurityLevel(), 255);
}
References rbac::RBACData::GetSecurityLevel(), rbac::RBACData::SetSecurityLevelForTest(), and TEST_REALM_ID.
Variable Documentation
TEST_ACCOUNT_ID
constexpr uint32 anonymous_namespace{RBACTest.cpp}::TEST_ACCOUNT_ID = 1 constexpr
Referenced by anonymous_namespace{RBACTest.cpp}::RBACDataTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACLinkedPermissionsTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACPermissionExpansionTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDeniedExpansionTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACGetPermissionsTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACRevokeEdgeCasesTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACComplexHierarchyTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDenySpecificFromRoleTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACEmptyAndBoundaryTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACExpandPermissionsDanglingLinkTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDoubleRevokeTest::SetUp(), and TEST_F().
TEST_ACCOUNT_NAME
const std::string anonymous_namespace{RBACTest.cpp}::TEST_ACCOUNT_NAME = "TestAccount"
Referenced by anonymous_namespace{RBACTest.cpp}::RBACDataTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACLinkedPermissionsTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACPermissionExpansionTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDeniedExpansionTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACGetPermissionsTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACRevokeEdgeCasesTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACComplexHierarchyTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDenySpecificFromRoleTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACEmptyAndBoundaryTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACExpandPermissionsDanglingLinkTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDoubleRevokeTest::SetUp(), and TEST_F().
TEST_PERM_1
constexpr uint32 anonymous_namespace{RBACTest.cpp}::TEST_PERM_1 = 1 constexpr
Referenced by anonymous_namespace{RBACTest.cpp}::RBACPermissionTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDataTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACLinkedPermissionsTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACSecurityLevelTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACPermissionRemoveLinkedTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACRevokeEdgeCasesTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACEmptyAndBoundaryTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACAccountMgrPermissionLookupTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDoubleRevokeTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACMultipleInstancesIndependenceTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACSetSecurityLevelForTestBehaviorTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDataAccessorsTest::SetUp(), and TEST_F().
TEST_PERM_2
constexpr uint32 anonymous_namespace{RBACTest.cpp}::TEST_PERM_2 = 2 constexpr
Referenced by anonymous_namespace{RBACTest.cpp}::RBACDataTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACLinkedPermissionsTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACPermissionRemoveLinkedTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACRevokeEdgeCasesTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACAccountMgrPermissionLookupTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACMultipleInstancesIndependenceTest::SetUp(), and TEST_F().
TEST_PERM_3
constexpr uint32 anonymous_namespace{RBACTest.cpp}::TEST_PERM_3 = 3 constexpr
Referenced by anonymous_namespace{RBACTest.cpp}::RBACDataTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACLinkedPermissionsTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACPermissionRemoveLinkedTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACRevokeEdgeCasesTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACMultipleInstancesIndependenceTest::SetUp(), and TEST_F().
TEST_PERM_INVALID
constexpr uint32 anonymous_namespace{RBACTest.cpp}::TEST_PERM_INVALID = 99999 constexpr
Referenced by TEST_F().
TEST_PERM_ROLE
constexpr uint32 anonymous_namespace{RBACTest.cpp}::TEST_PERM_ROLE = 100 constexpr
Referenced by anonymous_namespace{RBACTest.cpp}::RBACDataTest::SetUp(), and anonymous_namespace{RBACTest.cpp}::RBACLinkedPermissionsTest::SetUp().
TEST_REALM_ID
constexpr uint32 anonymous_namespace{RBACTest.cpp}::TEST_REALM_ID = 1 constexpr
Referenced by anonymous_namespace{RBACTest.cpp}::RBACDataTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACLinkedPermissionsTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACPermissionExpansionTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDeniedExpansionTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACGetPermissionsTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACRevokeEdgeCasesTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACComplexHierarchyTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDenySpecificFromRoleTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACEmptyAndBoundaryTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACExpandPermissionsDanglingLinkTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDoubleRevokeTest::SetUp(), and TEST_F().
TEST_SEC_LEVEL
constexpr uint8 anonymous_namespace{RBACTest.cpp}::TEST_SEC_LEVEL = 3 constexpr
Referenced by anonymous_namespace{RBACTest.cpp}::RBACDataTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACLinkedPermissionsTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACPermissionExpansionTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDeniedExpansionTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACGetPermissionsTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACRevokeEdgeCasesTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACComplexHierarchyTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDenySpecificFromRoleTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACEmptyAndBoundaryTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACExpandPermissionsDanglingLinkTest::SetUp(), anonymous_namespace{RBACTest.cpp}::RBACDoubleRevokeTest::SetUp(), and TEST_F().