AzerothCore: azerothcore-wotlk/src/server/scripts/Pet/pets_script_loader.cpp File Reference
pets_script_loader.cpp File Reference
Functions
void AddSC_deathknight_pet_scripts ()
void AddSC_generic_pet_scripts ()
void AddSC_hunter_pet_scripts ()
void AddSC_mage_pet_scripts ()
void AddSC_priest_pet_scripts ()
void AddSC_shaman_pet_scripts ()
void AddPetScripts ()
Function Documentation
AddPetScripts()
void AddPetScripts ()
{
    AddSC_deathknight_pet_scripts();
    AddSC_generic_pet_scripts();
    AddSC_hunter_pet_scripts();
    AddSC_mage_pet_scripts();
    AddSC_priest_pet_scripts();
    AddSC_shaman_pet_scripts();
}
References AddSC_deathknight_pet_scripts(), AddSC_generic_pet_scripts(), AddSC_hunter_pet_scripts(), AddSC_mage_pet_scripts(), AddSC_priest_pet_scripts(), and AddSC_shaman_pet_scripts().
AddSC_deathknight_pet_scripts()
void AddSC_deathknight_pet_scripts ()
{
    RegisterCreatureAI(npc_pet_dk_ebon_gargoyle);
    RegisterCreatureAI(npc_pet_dk_ghoul);
    RegisterCreatureAI(npc_pet_dk_risen_ally);
    RegisterCreatureAI(npc_pet_dk_army_of_the_dead);
    RegisterCreatureAI(npc_pet_dk_dancing_rune_weapon);
    RegisterSpellScript(spell_pet_dk_gargoyle_strike);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddPetScripts().
AddSC_generic_pet_scripts()
void AddSC_generic_pet_scripts ()
{
    RegisterCreatureAI(npc_pet_gen_soul_trader_beacon);
    RegisterCreatureAI(npc_pet_gen_argent_pony_bridle);
    RegisterCreatureAI(npc_pet_gen_target_following_bomb);
    RegisterCreatureAI(npc_pet_gen_gnomish_flame_turret);
    RegisterCreatureAI(npc_pet_gen_valkyr_guardian);
    RegisterSpellScript(spell_pet_gen_valkyr_guardian_smite);
    RegisterCreatureAI(npc_pet_gen_imp_in_a_bottle);
    RegisterCreatureAI(npc_pet_gen_wind_rider_cub);
    RegisterCreatureAI(npc_pet_gen_plump_turkey);
    RegisterCreatureAI(npc_pet_gen_toxic_wasteling);
    RegisterCreatureAI(npc_pet_gen_fetch_ball);
    RegisterCreatureAI(npc_pet_gen_moth);
    RegisterCreatureAI(npc_pet_darting_hatchling);
    RegisterCreatureAI(npc_pet_proto_drake_whelp);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddPetScripts().
AddSC_hunter_pet_scripts()
void AddSC_hunter_pet_scripts ()
{
    RegisterCreatureAI(npc_pet_hunter_snake_trap);
    RegisterSpellScript(spell_pet_guard_dog);
    RegisterSpellScript(spell_pet_silverback);
    RegisterSpellScript(spell_pet_culling_the_herd);
}
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddPetScripts().
AddSC_mage_pet_scripts()
void AddSC_mage_pet_scripts ()
{
    RegisterCreatureAI(npc_pet_mage_mirror_image);
}
References RegisterCreatureAI.
Referenced by AddPetScripts().
AddSC_priest_pet_scripts()
void AddSC_priest_pet_scripts ()
{
    RegisterCreatureAI(npc_pet_pri_lightwell);
}
References RegisterCreatureAI.
Referenced by AddPetScripts().
AddSC_shaman_pet_scripts()
void AddSC_shaman_pet_scripts ()
{
    RegisterCreatureAI(npc_pet_shaman_earth_elemental);
    RegisterCreatureAI(npc_pet_shaman_fire_elemental);
}
References RegisterCreatureAI.
Referenced by AddPetScripts().