AzerothCore: anonymous_namespace{WildGrowthTickScalingTest.cpp} Namespace Reference
anonymous_namespace{WildGrowthTickScalingTest.cpp} Namespace Reference
Functions
template<typename T >
T CalcPct (T base, float pct)
Mirrors CalculatePct from Define.h: base * pct / 100.
int32_t CalcWildGrowthTickAmount (int32_t baseTick, uint32_t tickNumber, float baseReduction)
Mirrors spell_dru_wild_growth_aura::HandleTickUpdate.
std::vector< int32_t > CalcAllTicks (int32_t baseTick, float baseReduction=DEFAULT_REDUCTION)
Calculate all tick amounts for a Wild Growth cast.
Variables
constexpr int32_t TOTAL_TICKS = 7
constexpr float DEFAULT_REDUCTION = 2.0f
Function Documentation
CalcAllTicks()
std::vector< int32_t > anonymous_namespace{WildGrowthTickScalingTest.cpp}::CalcAllTicks (int32_t baseTick, float baseReduction = DEFAULT_REDUCTION)
Calculate all tick amounts for a Wild Growth cast.
    {
        std::vector<int32_t> ticks;
        ticks.reserve(TOTAL_TICKS);
        for (uint32_t i = 1; i <= TOTAL_TICKS; ++i)
            ticks.push_back(CalcWildGrowthTickAmount(baseTick, i, baseReduction));
        return ticks;
    }
References CalcWildGrowthTickAmount(), and TOTAL_TICKS.
Referenced by TEST_F().
CalcPct()
template<typename T > T anonymous_namespace{WildGrowthTickScalingTest.cpp}::CalcPct (T base, float pct)
Mirrors CalculatePct from Define.h: base * pct / 100.
    {
        return static_cast<T>(base * pct / 100.0f);
    }
Referenced by CalcWildGrowthTickAmount().
CalcWildGrowthTickAmount()
int32_t anonymous_namespace{WildGrowthTickScalingTest.cpp}::CalcWildGrowthTickAmount (int32_t baseTick, uint32_t tickNumber, float baseReduction)
Mirrors spell_dru_wild_growth_aura::HandleTickUpdate.
    {
        float reduction = baseReduction * static_cast<float>(tickNumber - 1);
        float bonus = 6.0f - reduction;
        return static_cast<int32_t>(baseTick + CalcPct(baseTick, bonus));
    }
References CalcPct().
Referenced by CalcAllTicks(), and TEST_F().
Variable Documentation
DEFAULT_REDUCTION
constexpr float anonymous_namespace{WildGrowthTickScalingTest.cpp}::DEFAULT_REDUCTION = 2.0f constexpr
Referenced by TEST_F().
TOTAL_TICKS
constexpr int32_t anonymous_namespace{WildGrowthTickScalingTest.cpp}::TOTAL_TICKS = 7 constexpr
Referenced by CalcAllTicks(), and TEST_F().