AzerothCore: azerothcore-wotlk/src/common/Configuration/Config.cpp File Reference
Config.cpp File Reference
#include "Config.h"
#include "Log.h"
#include "StringConvert.h"
#include "StringFormat.h"
#include "Tokenize.h"
#include "Util.h"
#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <fstream>
#include <locale>
#include <mutex>
#include <unordered_map>
#include <unordered_set>
Namespaces
namespace anonymous_namespace{Config.cpp}
Macros
#define TEMPLATE_CONFIG_OPTION(__typename) template __typename ConfigMgr::GetOption<__typename>(std::string const& name, __typename const& def, bool showLogs /*= true*/) const;
Functions
bool anonymous_namespace{Config.cpp}::IsAppConfig (std::string_view fileName)
bool anonymous_namespace{Config.cpp}::IsLoggingSystemOptions (std::string_view optionName)
Optional< ConfigSeverity > anonymous_namespace{Config.cpp}::ParseSeverity (std::string_view value)
template<typename Format , typename... Args>
void anonymous_namespace{Config.cpp}::PrintError (std::string_view filename, Format &&fmt, Args &&... args)
template<typename Format , typename... Args>
void anonymous_namespace{Config.cpp}::LogWithSeverity (ConfigSeverity severity, std::string_view filename, Format &&fmt, Args &&... args)
ConfigPolicy anonymous_namespace{Config.cpp}::ApplyPolicyString (ConfigPolicy policy, std::string_view input)
ConfigPolicy anonymous_namespace{Config.cpp}::ApplyPolicyFromArgs (ConfigPolicy policy, std::vector< std::string > const &args)
void anonymous_namespace{Config.cpp}::AddKey (std::string const &optionName, std::string const &optionKey, std::string_view fileName, bool isOptional, bool isReload)
bool anonymous_namespace{Config.cpp}::ParseFile (std::string const &file, bool isOptional, bool isReload)
bool anonymous_namespace{Config.cpp}::LoadFile (std::string const &file, bool isOptional, bool isReload)
std::string anonymous_namespace{Config.cpp}::IniKeyToEnvVarKey (std::string const &key)
std::string anonymous_namespace{Config.cpp}::GetEnvVarName (std::string const &configName)
Optional< std::string > anonymous_namespace{Config.cpp}::EnvVarForIniKey (std::string const &key)
Optional< std::string > GetEnvFromCache (std::string const &configName, std::string const &envVarName)
template<>
std::string ConfigMgr::GetValueDefault< std::string > (std::string const &name, std::string const &def, bool showLogs) const
Variables
std::string anonymous_namespace{Config.cpp}::_filename
std::vector< std::string > anonymous_namespace{Config.cpp}::_additonalFiles
std::vector< std::string > anonymous_namespace{Config.cpp}::_args
std::unordered_map< std::string, std::string > anonymous_namespace{Config.cpp}::_configOptions
std::unordered_map< std::string, std::string > anonymous_namespace{Config.cpp}::_envVarCache
std::mutex anonymous_namespace{Config.cpp}::_configLock
ConfigPolicy anonymous_namespace{Config.cpp}::_policy
std::unordered_set< std::string > anonymous_namespace{Config.cpp}::_criticalConfigOptions
Macro Definition Documentation
TEMPLATE_CONFIG_OPTION
#define TEMPLATE_CONFIG_OPTION (__typename) template __typename ConfigMgr::GetOption<__typename>(std::string const& name, __typename const& def, bool showLogs /*= true*/) const;
Function Documentation
ConfigMgr::GetValueDefault< std::string >()
template<> std::string ConfigMgr::GetValueDefault< std::string > (std::string const & name, std::string const & def, bool showLogs) const
{
    auto const& itr = _configOptions.find(name);
    bool notFound = itr == _configOptions.end();
    auto envVarName = GetEnvVarName(name);
    Optional<std::string> envVar = GetEnvFromCache(name, envVarName);
    if (envVar)
    {
        // If showLogs and this key/value pair wasn't found in the currently saved config
        if (showLogs && (notFound || itr->second != envVar->c_str()))
        {
            LOG_INFO("server.loading", "> Config: Found config value '{}' from environment variable '{}'.", name, envVarName);
            AddKey(name, *envVar, "ENVIRONMENT", false, false);
        }
        return *envVar;
    }
    else if (notFound)
    {
        if (showLogs)
        {
            bool isCritical = _criticalConfigOptions.find(name) != _criticalConfigOptions.end();
            ConfigSeverity severity = isCritical ? _policy.criticalOptionSeverity : _policy.missingOptionSeverity;
            if (isCritical)
            {
                LogWithSeverity(severity, _filename,
                    "> Config:\n\nFATAL ERROR: Missing property {} in config file {}, add \"{} = {}\" to this file or define '{}' as an environment variable.\n\nYour server cannot start without this option!",
                    name, _filename, name, def, envVarName);
            }
            else
            {
                std::string configs = _filename;
                if (!_moduleConfigFiles.empty())
                    configs += " or module config";
                LogWithSeverity(severity, _filename,
                    "> Config: Missing property {} in config file {}, add \"{} = {}\" to this file or define '{}' as an environment variable.",
                    name, configs, name, def, envVarName);
            }
        }
        return def;
    }
    return itr->second;
}
References anonymous_namespace{Config.cpp}::_configOptions, anonymous_namespace{Config.cpp}::_criticalConfigOptions, anonymous_namespace{Config.cpp}::_filename, anonymous_namespace{Config.cpp}::_policy, anonymous_namespace{Config.cpp}::AddKey(), ConfigPolicy::criticalOptionSeverity, GetEnvFromCache(), anonymous_namespace{Config.cpp}::GetEnvVarName(), LOG_INFO, anonymous_namespace{Config.cpp}::LogWithSeverity(), and ConfigPolicy::missingOptionSeverity.
GetEnvFromCache()
Optional< std::string > GetEnvFromCache (std::string const & configName, std::string const & envVarName)
{
    auto foundInCache = _envVarCache.find(envVarName);
    Optional<std::string> foundInEnv;
    // If it's not in the cache
    if (foundInCache == _envVarCache.end())
    {
        // Check the env itself
        foundInEnv = EnvVarForIniKey(configName);
        if (foundInEnv)
        {
            // If it's found in the env, put it in the cache
            _envVarCache.emplace(envVarName, *foundInEnv);
        }
        // Return the result of checking env
        return foundInEnv;
    }
    return foundInCache->second;
}
References anonymous_namespace{Config.cpp}::_envVarCache, and anonymous_namespace{Config.cpp}::EnvVarForIniKey().
Referenced by ConfigMgr::GetValueDefault< std::string >(), and ConfigMgr::GetValueDefault().