AzerothCore: azerothcore-wotlk/src/server/game/Events/HolidayDateCalculator.cpp File Reference
HolidayDateCalculator.cpp File Reference
#include "HolidayDateCalculator.h"
#include "SharedDefines.h"
#include <cmath>
Functions
double sind (double deg)
static bool IsLeapYear (int year)
static int DaysInMonth (int year, int month)
static void NormalizeDate (std::tm &date)
Variables
constexpr double PI = 3.14159265358979323846
constexpr double DEG_TO_RAD = PI / 180.0
static const std::vector< HolidayRule > HolidayRules
Function Documentation
DaysInMonth()
static int DaysInMonth (int year, int month) static
{
    static int const table[] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
    return (month == 2 && IsLeapYear(year)) ? 29 : table[month - 1];
}
References IsLeapYear().
Referenced by NormalizeDate().
IsLeapYear()
static bool IsLeapYear (int year) static
{
    return (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);
}
Referenced by DaysInMonth(), and TEST_F().
NormalizeDate()
static void NormalizeDate (std::tm & date) static
{
    int year = date.tm_year + 1900;
    int month = date.tm_mon + 1;
    int day = date.tm_mday;
    while (month > 12)
    {
        month -= 12;
        ++year;
    }
    while (month < 1)
    {
        month += 12;
        --year;
    }
    while (day > DaysInMonth(year, month))
    {
        day -= DaysInMonth(year, month);
        ++month;
        if (month > 12)
        {
            month = 1;
            ++year;
        }
    }
    while (day < 1)
    {
        --month;
        if (month < 1)
        {
            month = 12;
            --year;
        }
        day += DaysInMonth(year, month);
    }
    date.tm_year = year - 1900;
    date.tm_mon = month - 1;
    date.tm_mday = day;
    // Zeller's congruence; remap 0=Sat to POSIX 0=Sun.
    int zy = year;
    int zm = month;
    if (zm < 3)
    {
        zm += 12;
        --zy;
    }
    int const K = zy % 100;
    int const J = zy / 100;
    int const h = (day + (13 * (zm + 1)) / 5 + K + K / 4 + J / 4 + 5 * J) % 7;
    date.tm_wday = (h + 6) % 7;
}
References DaysInMonth().
Referenced by HolidayDateCalculator::CalculateAutumnEquinox(), HolidayDateCalculator::CalculateEasterSunday(), HolidayDateCalculator::CalculateHolidayDate(), HolidayDateCalculator::CalculateLunarNewYear(), HolidayDateCalculator::CalculateNthWeekday(), HolidayDateCalculator::CalculateWeekdayOnOrAfter(), HolidayDateCalculator::CalculateWinterSolstice(), and HolidayDateCalculator::GetDarkmoonFaireDates().
sind()
double sind (double deg) inline
{ return std::sin(deg * DEG_TO_RAD); }
References DEG_TO_RAD.
Referenced by HolidayDateCalculator::CalculateNewMoon().
Variable Documentation
DEG_TO_RAD
constexpr double DEG_TO_RAD = PI / 180.0 constexpr
Referenced by HolidayDateCalculator::CalculateAutumnEquinox(), HolidayDateCalculator::CalculateWinterSolstice(), and sind().
HolidayRules
const std::vector<HolidayRule> HolidayRules static
Referenced by HolidayDateCalculator::GetHolidayRules(), and HolidayDateCalculator::GetPackedHolidayDate().
PI
constexpr double PI = 3.14159265358979323846 constexpr