AzerothCore: anonymous_namespace{Config.cpp} Namespace Reference
anonymous_namespace{Config.cpp} Namespace Reference
Functions
bool IsAppConfig (std::string_view fileName)
bool IsLoggingSystemOptions (std::string_view optionName)
Optional< ConfigSeverity > ParseSeverity (std::string_view value)
template<typename Format , typename... Args>
void PrintError (std::string_view filename, Format &&fmt, Args &&... args)
template<typename Format , typename... Args>
void LogWithSeverity (ConfigSeverity severity, std::string_view filename, Format &&fmt, Args &&... args)
ConfigPolicy ApplyPolicyString (ConfigPolicy policy, std::string_view input)
ConfigPolicy ApplyPolicyFromArgs (ConfigPolicy policy, std::vector< std::string > const &args)
void AddKey (std::string const &optionName, std::string const &optionKey, std::string_view fileName, bool isOptional, bool isReload)
bool ParseFile (std::string const &file, bool isOptional, bool isReload)
bool LoadFile (std::string const &file, bool isOptional, bool isReload)
std::string IniKeyToEnvVarKey (std::string const &key)
std::string GetEnvVarName (std::string const &configName)
Optional< std::string > EnvVarForIniKey (std::string const &key)
Variables
std::string _filename
std::vector< std::string > _additonalFiles
std::vector< std::string > _args
std::unordered_map< std::string, std::string > _configOptions
std::unordered_map< std::string, std::string > _envVarCache
std::mutex _configLock
ConfigPolicy _policy
std::unordered_set< std::string > _criticalConfigOptions
Function Documentation
AddKey()
void anonymous_namespace{Config.cpp}::AddKey (std::string const & optionName, std::string const & optionKey, std::string_view fileName, bool isOptional, bool isReload)
    {
        auto const& itr = _configOptions.find(optionName);
        // Check old option
        if (isOptional && itr == _configOptions.end())
        {
            if (!IsLoggingSystemOptions(optionName) && !isReload)
            {
                LogWithSeverity(_policy.unknownOptionSeverity, fileName, "> Config::LoadFile: Found incorrect option '{}' in config file '{}'. Skip", optionName, fileName);
#ifdef CONFIG_ABORT_INCORRECT_OPTIONS
                ABORT("> Core can't start if found incorrect options");
#endif
                return;
            }
        }
        // Check exit option
        if (itr != _configOptions.end())
        {
            _configOptions.erase(optionName);
        }
        _configOptions.emplace(optionName, optionKey);
    }
References _configOptions, _policy, ABORT, IsLoggingSystemOptions(), LogWithSeverity(), and ConfigPolicy::unknownOptionSeverity.
Referenced by ConfigMgr::GetValueDefault< std::string >(), and ParseFile().
ApplyPolicyFromArgs()
ConfigPolicy anonymous_namespace{Config.cpp}::ApplyPolicyFromArgs (ConfigPolicy policy, std::vector< std::string > const & args)
    {
        for (std::size_t i = 0; i < args.size(); ++i)
        {
            std::string const& arg = args[i];
            std::string_view value;
            constexpr std::string_view shortOpt = "--config-policy";
            if (arg.rfind(shortOpt, 0) == 0)
            {
                if (arg.size() == shortOpt.size() && (i + 1) < args.size())
                {
                    value = args[i + 1];
                    ++i;
                }
                else if (arg.size() > shortOpt.size() && arg[shortOpt.size()] == '=')
                {
                    value = std::string_view(arg).substr(shortOpt.size() + 1);
                }
                if (!value.empty())
                    policy = ApplyPolicyString(policy, value);
            }
        }
        return policy;
    }
References ApplyPolicyString().
ApplyPolicyString()
ConfigPolicy anonymous_namespace{Config.cpp}::ApplyPolicyString (ConfigPolicy policy, std::string_view input)
    {
        if (input.empty())
            return policy;
        std::vector<std::pair<std::string, ConfigSeverity>> overrides;
        Optional<ConfigSeverity> defaultOverride;
        std::string tokenBuffer(input);
        for (std::string_view rawToken : Acore::Tokenize(tokenBuffer, ',', false))
        {
            std::string token = Acore::String::Trim(std::string(rawToken), std::locale());
            if (token.empty())
                continue;
            auto separator = token.find('=');
            if (separator == std::string::npos)
                continue;
            std::string key = Acore::String::Trim(token.substr(0, separator), std::locale());
            std::string value = Acore::String::Trim(token.substr(separator + 1), std::locale());
            if (key.empty() || value.empty())
                continue;
            auto severity = ParseSeverity(value);
            if (!severity)
                continue;
            std::transform(key.begin(), key.end(), key.begin(), [](unsigned char c) { return std::tolower(c); });
            if (key == "default")
            {
                defaultOverride = severity;
                continue;
            }
            overrides.emplace_back(std::move(key), *severity);
        }
        if (defaultOverride)
        {
            policy.defaultSeverity = *defaultOverride;
            policy.missingFileSeverity = *defaultOverride;
            policy.missingOptionSeverity = *defaultOverride;
            policy.criticalOptionSeverity = *defaultOverride;
            policy.unknownOptionSeverity = *defaultOverride;
            policy.valueErrorSeverity = *defaultOverride;
        }
        for (auto const& [key, severity] : overrides)
        {
            if (key == "missing_file" || key == "file")
                policy.missingFileSeverity = severity;
            else if (key == "missing_option" || key == "option")
                policy.missingOptionSeverity = severity;
            else if (key == "critical_option" || key == "critical")
                policy.criticalOptionSeverity = severity;
            else if (key == "unknown_option" || key == "unknown")
                policy.unknownOptionSeverity = severity;
            else if (key == "value_error" || key == "value")
                policy.valueErrorSeverity = severity;
        }
        return policy;
    }
References ConfigPolicy::criticalOptionSeverity, ConfigPolicy::defaultSeverity, ConfigPolicy::missingFileSeverity, ConfigPolicy::missingOptionSeverity, ParseSeverity(), Acore::Tokenize(), Acore::String::Trim(), ConfigPolicy::unknownOptionSeverity, and ConfigPolicy::valueErrorSeverity.
Referenced by ApplyPolicyFromArgs().
EnvVarForIniKey()
Optional< std::string > anonymous_namespace{Config.cpp}::EnvVarForIniKey (std::string const & key)
    {
        std::string envKey = GetEnvVarName(key);
        char* val = std::getenv(envKey.c_str());
        if (!val)
            return std::nullopt;
        return std::string(val);
    }
References GetEnvVarName().
Referenced by GetEnvFromCache().
GetEnvVarName()
std::string anonymous_namespace{Config.cpp}::GetEnvVarName (std::string const & configName)
    {
        return "AC_" + IniKeyToEnvVarKey(configName);
    }
References IniKeyToEnvVarKey().
Referenced by ConfigMgr::GetValueDefault< std::string >(), and EnvVarForIniKey().
IniKeyToEnvVarKey()
std::string anonymous_namespace{Config.cpp}::IniKeyToEnvVarKey (std::string const & key)
    {
        std::string result;
        const char* str = key.c_str();
        std::size_t n = key.length();
        char curr;
        bool isEnd;
        bool nextIsUpper;
        bool currIsNumeric;
        bool nextIsNumeric;
        for (std::size_t i = 0; i < n; ++i)
        {
            curr = str[i];
            if (curr == ' ' || curr == '.' || curr == '-')
            {
                result += '_';
                continue;
            }
            isEnd = i == n - 1;
            if (!isEnd)
            {
                nextIsUpper = isupper(str[i + 1]);
                // handle "aB" to "A_B"
                if (!isupper(curr) && nextIsUpper)
                {
                    result += static_cast<char>(std::toupper(curr));
                    result += '_';
                    continue;
                }
                currIsNumeric = isNumeric(curr);
                nextIsNumeric = isNumeric(str[i + 1]);
                // handle "a1" to "a_1"
                if (!currIsNumeric && nextIsNumeric)
                {
                    result += static_cast<char>(std::toupper(curr));
                    result += '_';
                    continue;
                }
                // handle "1a" to "1_a"
                if (currIsNumeric && !nextIsNumeric)
                {
                    result += static_cast<char>(std::toupper(curr));
                    result += '_';
                    continue;
                }
            }
            result += static_cast<char>(std::toupper(curr));
        }
        return result;
    }
References isNumeric().
Referenced by GetEnvVarName().
IsAppConfig()
bool anonymous_namespace{Config.cpp}::IsAppConfig (std::string_view fileName)
    {
        std::size_t foundAuth = fileName.find("authserver.conf");
        std::size_t foundWorld = fileName.find("worldserver.conf");
        std::size_t foundImport = fileName.find("dbimport.conf");
        return foundAuth != std::string_view::npos || foundWorld != std::string_view::npos || foundImport != std::string_view::npos;
    }
Referenced by LogWithSeverity(), and PrintError().
IsLoggingSystemOptions()
bool anonymous_namespace{Config.cpp}::IsLoggingSystemOptions (std::string_view optionName)
    {
        std::size_t foundAppender = optionName.find("Appender.");
        std::size_t foundLogger = optionName.find("Logger.");
        return foundAppender != std::string_view::npos || foundLogger != std::string_view::npos;
    }
Referenced by AddKey().
LoadFile()
bool anonymous_namespace{Config.cpp}::LoadFile (std::string const & file, bool isOptional, bool isReload)
    {
        try
        {
            return ParseFile(file, isOptional, isReload);
        }
        catch (const std::exception& e)
        {
            PrintError(file, "> {}", e.what());
        }
        return false;
    }
References ParseFile(), and PrintError().
LogWithSeverity()
template<typename Format , typename... Args> void anonymous_namespace{Config.cpp}::LogWithSeverity (ConfigSeverity severity, std::string_view filename, Format && fmt, Args &&... args) inline
    {
        std::string message = Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...);
        switch (severity)
        {
            case ConfigSeverity::Skip:
                return;
            case ConfigSeverity::Warn:
            {
                if (IsAppConfig(filename))
                    fmt::print("{}\n", message);
                LOG_WARN("server.loading", message);
                return;
            }
            case ConfigSeverity::Error:
            {
                if (IsAppConfig(filename))
                    fmt::print("{}\n", message);
                LOG_ERROR("server.loading", message);
                return;
            }
            case ConfigSeverity::Fatal:
            {
                if (IsAppConfig(filename))
                    fmt::print("{}\n", message);
                LOG_FATAL("server.loading", message);
                ABORT(message);
            }
        }
    }
References ABORT, Error, Fatal, IsAppConfig(), LOG_ERROR, LOG_FATAL, LOG_WARN, Skip, Acore::StringFormat(), and Warn.
Referenced by AddKey(), ConfigMgr::GetValueDefault< std::string >(), and ParseFile().
ParseFile()
bool anonymous_namespace{Config.cpp}::ParseFile (std::string const & file, bool isOptional, bool isReload)
    {
        std::ifstream in(file);
        if (in.fail())
        {
            ConfigSeverity severity = isOptional ? ConfigSeverity::Skip : _policy.missingFileSeverity;
            LogWithSeverity(severity, file, "> Config::LoadFile: Failed open {}file '{}'", isOptional ? "optional " : "", file);
            // Treat SKIP as a successful no-op so the app can proceed
            return severity == ConfigSeverity::Skip;
        }
        uint32 count = 0;
        uint32 lineNumber = 0;
        std::unordered_map<std::string /*name*/, std::string /*value*/> fileConfigs;
        auto IsDuplicateOption = [&](std::string const& confOption)
        {
            auto const& itr = fileConfigs.find(confOption);
            if (itr != fileConfigs.end())
            {
                PrintError(file, "> Config::LoadFile: Duplicate key name '{}' in config file '{}'", confOption, file);
                return true;
            }
            return false;
        };
        while (in.good())
        {
            lineNumber++;
            std::string line;
            std::getline(in, line);
            // read line error
            if (!in.good() && !in.eof())
                throw ConfigException(Acore::StringFormat("> Config::LoadFile: Failure to read line number {} in file '{}'", lineNumber, file));
            // remove whitespace in line
            line = Acore::String::Trim(line, in.getloc());
            if (line.empty())
                continue;
            // comments and headers
            if (line[0] == '#' || line[0] == '[')
                continue;
            auto const equal_pos = line.find('=');
            if (equal_pos == std::string::npos || equal_pos == line.length())
            {
                PrintError(file, "> Config::LoadFile: Failure to read line number {} in file '{}'. Skip this line", lineNumber, file);
                continue;
            }
            auto entry = Acore::String::Trim(line.substr(0, equal_pos), in.getloc());
            auto value = Acore::String::Trim(line.substr(equal_pos + 1, std::string::npos), in.getloc());
            value.erase(std::remove(value.begin(), value.end(), '"'), value.end());
            // Skip if 2+ same options in one config file
            if (IsDuplicateOption(entry))
                continue;
            // Add to temp container
            fileConfigs.emplace(entry, value);
            count++;
        }
        // No lines read
        if (!count)
        {
            ConfigSeverity severity = isOptional ? ConfigSeverity::Skip : _policy.missingFileSeverity;
            LogWithSeverity(severity, file, "> Config::LoadFile: Empty file '{}'", file);
            // Treat SKIP as a successful no-op
            return severity == ConfigSeverity::Skip;
        }
        // Add correct keys if file load without errors
        for (auto const& [entry, key] : fileConfigs)
        {
            AddKey(entry, key, file, isOptional, isReload);
        }
        return true;
    }
References _policy, AddKey(), LogWithSeverity(), ConfigPolicy::missingFileSeverity, PrintError(), Skip, Acore::StringFormat(), and Acore::String::Trim().
Referenced by LoadFile().
ParseSeverity()
Optional< ConfigSeverity > anonymous_namespace{Config.cpp}::ParseSeverity (std::string_view value)
    {
        if (value.empty())
            return std::nullopt;
        std::string lowered(value);
        std::transform(lowered.begin(), lowered.end(), lowered.begin(), [](unsigned char c) { return std::tolower(c); });
        if (lowered == "skip")
            return ConfigSeverity::Skip;
        if (lowered == "warn" || lowered == "warning")
            return ConfigSeverity::Warn;
        if (lowered == "error")
            return ConfigSeverity::Error;
        if (lowered == "fatal" || lowered == "abort" || lowered == "panic")
            return ConfigSeverity::Fatal;
        return std::nullopt;
    }
References Error, Fatal, Skip, and Warn.
Referenced by ApplyPolicyString().
PrintError()
template<typename Format , typename... Args> void anonymous_namespace{Config.cpp}::PrintError (std::string_view filename, Format && fmt, Args &&... args) inline
    {
        std::string message = Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...);
        if (IsAppConfig(filename))
        {
            fmt::print("{}\n", message);
        }
        else
        {
            LOG_ERROR("server.loading", message);
        }
    }
References IsAppConfig(), LOG_ERROR, and Acore::StringFormat().
Referenced by LoadFile(), and ParseFile().
Variable Documentation
_additonalFiles
std::vector<std::string> anonymous_namespace{Config.cpp}::_additonalFiles
_args
std::vector<std::string> anonymous_namespace{Config.cpp}::_args
_configLock
std::mutex anonymous_namespace{Config.cpp}::_configLock
_configOptions
std::unordered_map<std::string , std::string > anonymous_namespace{Config.cpp}::_configOptions
Referenced by AddKey(), and ConfigMgr::GetValueDefault< std::string >().
_criticalConfigOptions
std::unordered_set<std::string> anonymous_namespace{Config.cpp}::_criticalConfigOptions
Initial value:
=
    {
        "RealmID",
        "LoginDatabaseInfo",
        "WorldDatabaseInfo",
        "CharacterDatabaseInfo",
    }
Referenced by ConfigMgr::GetValueDefault< std::string >().
_envVarCache
std::unordered_map<std::string , std::string > anonymous_namespace{Config.cpp}::_envVarCache
Referenced by GetEnvFromCache().
_filename
std::string anonymous_namespace{Config.cpp}::_filename
Referenced by ConfigMgr::GetValueDefault< std::string >().
_policy
ConfigPolicy anonymous_namespace{Config.cpp}::_policy
Referenced by AddKey(), ConfigMgr::GetValueDefault< std::string >(), and ParseFile().